import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createGraph } from '../src/graph.mjs';
import { createModel } from '../src/model.mjs';
import { createRuntime } from '../src/runtime.mjs';
import { openStore } from '../src/store.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';

const TENANT = '11111111-2222-4333-8444-555555555555';
const NOW = 2_000_000_000_000;
const GRAPH_SECRET_ENV = 'ROTATION_GRAPH_SECRET';
const MODEL_KEY_ENV = 'ROTATION_MODEL_KEY';
const MODEL_URL = 'https://models.example.test/v1';

function config() {
  return {
    id: 'credential-rotation', state_root: './state',
    mailbox: {
      provider: 'microsoft-graph', tenant_id: TENANT, client_id: 'synthetic-client-id',
      client_secret_env: GRAPH_SECRET_ENV, address: 'agent@example.org', intake: 'delta-poll', delivery: 'direct-reply',
      sender_authentication: { mode: 'exchange-authenticated', trusted_authserv_ids: ['mx.example.test'], transport_headers_verified: false }
    },
    model: {
      api: 'chat-completions', base_url: MODEL_URL, api_key_env: MODEL_KEY_ENV,
      name: 'synthetic-model', timeout_ms: 2000, capabilities: { tools: false, images: false, pdf: false }
    },
    policy: { senders: ['alice@example.org'], recipients: ['alice@example.org'], approvers: [], tools: {} },
    mcp: {}, limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000, output_tokens: 2000, queue_messages: 100 },
    retention: { content_hours: 24, audit_days: 30 }
  };
}

function completionResponse() {
  return new Response(JSON.stringify({
    id: 'synthetic-completion', object: 'chat.completion', created: 1, model: 'synthetic-model',
    choices: [{ index: 0, message: { role: 'assistant', content: 'Probe succeeded.' }, finish_reason: 'stop' }],
    usage: { prompt_tokens: 7, completion_tokens: 3 }
  }), { headers: { 'content-type': 'application/json' } });
}

function syntheticFetch(ledger) {
  return async (input, init = {}) => {
    const url = String(input);
    const method = init.method ?? 'GET';
    const headers = new Headers(init.headers);
    const request = { url, method, authorization: headers.get('authorization'), body: init.body };
    ledger.push(request);
    if (url.includes('/oauth2/v2.0/token')) {
      const form = new URLSearchParams(String(init.body));
      const secret = form.get('client_secret');
      assert.equal(form.get('client_id'), 'synthetic-client-id');
      assert.equal(form.get('grant_type'), 'client_credentials');
      assert.equal(form.get('scope'), 'https://graph.microsoft.com/.default');
      return new Response(JSON.stringify({ access_token: `synthetic-access-for-${secret}`, expires_in: 3600 }), {
        headers: { 'content-type': 'application/json' }
      });
    }
    if (url.startsWith('https://graph.microsoft.com/')) {
      assert.equal(method, 'GET');
      assert.match(request.authorization, /^Bearer synthetic-access-for-/);
      assert.match(url, /\/mailFolders\/inbox\/messages\?/);
      return new Response(JSON.stringify({ value: [] }), { headers: { 'content-type': 'application/json' } });
    }
    if (url === `${MODEL_URL}/chat/completions`) {
      assert.equal(method, 'POST');
      assert.match(request.authorization, /^Bearer /);
      return completionResponse();
    }
    throw new Error('Unexpected synthetic adapter request.');
  };
}

function pendingRun(id, sequence, status, extra = {}) {
  return {
    id, messageKey: `message-${id}`, conversationKey: `conversation-${id}`, sequence, status,
    createdAt: NOW, budget: { modelCalls: 2, toolCalls: 1, activeMs: 37 }, configHash: 'before-rotation',
    mail: {
      id: `message-${id}`, conversationId: `conversation-${id}`, sender: 'alice@example.org', replyTo: 'alice@example.org',
      to: ['agent@example.org'], cc: [], subject: 'Synthetic retained work', body: 'Synthetic request.',
      receivedAt: '2026-01-01T00:00:00Z', authenticated: true, autoGenerated: false, attachments: false
    },
    ...extra
  };
}

test('replacement OAuth and model credentials work through actual adapters without changing queued state or issuing writes', async t => {
  const root = await mkdtemp(join(tmpdir(), 'ma-credential-rotation-'));
  t.after(async () => { await rm(root, { recursive: true, force: true }); });
  const cfg = config();
  const original = structuredClone(cfg);
  const env = { [GRAPH_SECRET_ENV]: 'synthetic-old-graph-secret', [MODEL_KEY_ENV]: 'synthetic-old-model-key' };

  // Exercise the previous deployment credentials through the actual provider adapters.
  const previousRequests = [];
  const previousFetch = syntheticFetch(previousRequests);
  const oldGraph = createGraph(cfg.mailbox, { env, fetchImpl: previousFetch, clock: () => NOW });
  const oldModel = createModel(cfg.model, { apiKey: env[MODEL_KEY_ENV], fetchImpl: previousFetch });
  assert.deepEqual(await oldGraph.check(), { status: 'ready' });
  assert.equal((await oldModel.step({ messages: [{ role: 'user', content: 'Synthetic pre-rotation probe.' }], maxOutputTokens: 32 })).text, 'Probe succeeded.');
  assert.ok(previousRequests.some(request => String(request.body).includes('synthetic-old-graph-secret')));
  assert.ok(previousRequests.some(request => request.url === `${MODEL_URL}/chat/completions` && request.authorization === 'Bearer synthetic-old-model-key'));

  // Seed a stopped deployment's cursor, resumable queue item, and unresolved action fence.
  const stateRoot = join(root, cfg.state_root);
  const store = openStore(stateRoot, { identity: mailboxIdentity(cfg), clock: () => NOW });
  const checkpoint = JSON.stringify({ initialComplete: true, delta: 'synthetic-rotation-cursor' });
  store.setMeta('cursor', checkpoint);
  store.saveRun(pendingRun('queued-before-rotation', 1, 'queued'));
  store.saveRun(pendingRun('uncertain-before-rotation', 2, 'uncertain', { uncertainty: { kind: 'tool', key: 'write-fence' } }));
  store.saveAction({ key: 'write-fence', runId: 'uncertain-before-rotation', state: 'uncertain', effect: 'write', tool: 'records.append' });
  store.close();

  env[GRAPH_SECRET_ENV] = 'synthetic-new-graph-secret';
  env[MODEL_KEY_ENV] = 'synthetic-new-model-key';
  const replacementRequests = [];
  const replacementFetch = syntheticFetch(replacementRequests);
  let toolCalls = 0;
  const mcp = {
    listTools: async () => new Map(),
    call: async () => { toolCalls++; return { content: [] }; },
    close: async () => {}
  };
  const runtime = await createRuntime({
    config: cfg, root, env, hash: 'after-rotation', instructions: 'Synthetic retained instructions.',
    fetchImpl: replacementFetch, mcp, clock: () => NOW
  });
  t.after(() => runtime.stop());

  const identity = value => [value.id, value.mailbox.tenant_id, value.mailbox.client_id, value.mailbox.address];
  assert.deepEqual(identity(cfg), identity(original));
  assert.deepEqual(cfg.policy.senders, original.policy.senders);
  assert.deepEqual(cfg.policy.recipients, original.policy.recipients);
  assert.deepEqual(cfg.mailbox, original.mailbox);
  assert.deepEqual(cfg.model, original.model);

  const probe = await runtime.liveCheck();
  assert.equal(probe.ready, true);
  assert.equal(probe.externalMutations, false);
  const tokenRequest = replacementRequests.find(request => request.url.includes('/oauth2/v2.0/token'));
  assert.ok(tokenRequest);
  assert.ok(String(tokenRequest.body).includes('synthetic-new-graph-secret'));
  const graphRead = replacementRequests.find(request => request.url.startsWith('https://graph.microsoft.com/'));
  assert.equal(graphRead.method, 'GET');
  assert.equal(graphRead.authorization, 'Bearer synthetic-access-for-synthetic-new-graph-secret');
  const modelRequest = replacementRequests.find(request => request.url === `${MODEL_URL}/chat/completions`);
  assert.equal(modelRequest.authorization, 'Bearer synthetic-new-model-key');
  assert.equal(toolCalls, 0);
  assert.equal(replacementRequests.some(request => request.url.includes('/reply')), false);
  assert.equal(replacementRequests.filter(request => request.url.startsWith('https://graph.microsoft.com/')).every(request => request.method === 'GET'), true);

  const status = runtime.status();
  assert.equal(status.sync.baseline, 'complete');
  assert.equal(status.counts.queued, 1);
  assert.equal(status.counts.uncertain, 1);
  assert.equal(status.runs.find(run => run.id === 'queued-before-rotation').budget.modelCalls, 2);
  await runtime.stop();

  const restored = openStore(stateRoot, { identity: mailboxIdentity(cfg), clock: () => NOW });
  try {
    assert.equal(restored.getMeta('cursor'), checkpoint);
    assert.equal(restored.getRun('queued-before-rotation').status, 'queued');
    assert.equal(restored.getRun('uncertain-before-rotation').status, 'uncertain');
    assert.equal(restored.getAction('write-fence').state, 'uncertain');
  } finally { restored.close(); }
});
