import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runCli } from '../src/cli.mjs';
import { loadFixture } from '../src/fixture.mjs';

const config = fileURLToPath(new URL('../examples/text-inbox/agent.yaml', import.meta.url));
const sentinel = 'PRIVATE_X';

function capture() {
  let text = '';
  return { write(value) { text += value; }, text: () => text };
}

async function previewFailure(filename, expected) {
  const stdout = capture(), stderr = capture();
  let constructed = 0, processed = 0, stopped = 0;
  const createRuntime = async settings => {
    constructed++;
    assert.equal(settings.mode, 'preview');
    return {
      async processMessage() { processed++; throw new Error('Unexpected request processing.'); },
      async stop() { stopped++; },
    };
  };
  assert.equal(await runCli(['preview', filename, '--config', config], {
    createRuntime, stdout, stderr, env: {},
  }), 1);
  assert.equal(stderr.text(), `Mail Agent: ${expected}\n`);
  assert.equal(stdout.text(), '');
  assert.equal(stderr.text().includes(sentinel), false);
  assert.equal(stderr.text().includes(filename), false);
  assert.equal(processed, 0);
  // Preserve existing preview setup ordering; failures must close any constructed runtime.
  assert.equal(constructed, 1);
  assert.equal(stopped, 1);
}

test('CLI malformed fixture errors never disclose submitted JSON excerpts or the filename', async t => {
  const root = await mkdtemp(join(tmpdir(), 'mail-fixture-errors-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const filename = join(root, 'private-request.json');
  await writeFile(filename, sentinel, { mode: 0o600 });
  await previewFailure(filename, 'Fixture request must be valid JSON');
  await assert.rejects(loadFixture(filename), error =>
    error.message === 'Fixture request must be valid JSON' && error.cause === undefined);
});

test('CLI unavailable fixture errors never disclose a private-shaped filename', async t => {
  const root = await mkdtemp(join(tmpdir(), 'mail-fixture-errors-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const filename = join(root, `private-${sentinel}-missing.json`);
  await previewFailure(filename, 'Fixture request could not be read');
  await assert.rejects(loadFixture(filename), error =>
    error.message === 'Fixture request could not be read' && error.cause === undefined);
});

test('valid fixture normalization and existing validation messages remain unchanged', async t => {
  const root = await mkdtemp(join(tmpdir(), 'mail-fixture-errors-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const filename = join(root, 'request.json');
  const mail = { id: 'synthetic-id', conversationId: 'synthetic-thread', sender: 'alice@example.org',
    subject: 'Synthetic', body: 'Synthetic request', receivedAt: '2026-10-01T00:00:00Z',
    to: ['assistant@example.org'], cc: [], attachments: [] };
  await writeFile(filename, JSON.stringify(mail), { mode: 0o600 });
  assert.deepEqual(await loadFixture(filename), { ...mail, attachments: false, autoGenerated: false, authenticated: true });
  await writeFile(filename, '{}');
  await assert.rejects(loadFixture(filename), { message: 'Fixture request requires id' });
  await writeFile(filename, JSON.stringify({ ...mail, receivedAt: 'invalid' }));
  await assert.rejects(loadFixture(filename), { message: 'Fixture receivedAt must be an ISO date' });
});
