import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile, mkdtemp, chmod, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { prepareImages, imageParts } from '../src/image-intake.mjs';
import { createImageArtifacts } from '../src/image-artifacts.mjs';
import { ImageError } from '../src/image-validation.mjs';
import { createModel } from '../src/model.mjs';

const mail = { id: 'synthetic-message', conversationId: 'synthetic-conversation', sender: 'sender@example.org', authenticated: true, autoGenerated: false };
const png = () => readFile(new URL('./fixtures/images/synthetic-note.png', import.meta.url));
const descriptor = bytes => ({ id: 'synthetic-attachment', type: 'file', isInline: false, contentType: 'image/png', size: bytes.length });
async function setup(t) {
  const stateRoot = await mkdtemp(join(tmpdir(), 'image-intake-')); await chmod(stateRoot, 0o700);
  t.after(() => rm(stateRoot, { recursive: true, force: true }));
  return createImageArtifacts({ stateRoot, runId: '11111111-1111-4111-8111-111111111111', expiresAt: 2000, clock: () => 1000 });
}

test('complete image intake uses scoped bounded reads and real SDK sends exact bytes as untrusted user parts', async t => {
  const bytes = await png(), artifacts = await setup(t), reads = [];
  const handles = await prepareImages({ mail, artifacts, attachments: { complete: true, items: [descriptor(bytes)] }, readAttachment: async (...args) => { reads.push(args); return bytes; } });
  assert.equal(reads[0][0], mail.id); assert.equal(reads[0][1], 'synthetic-attachment'); assert.equal(reads[0][2].maxBytes, bytes.length);
  assert.deepEqual(handles[0].source, { messageId: mail.id, attachmentId: 'synthetic-attachment' });
  const parts = await imageParts(handles, artifacts);
  let calls = 0;
  const model = createModel({ base_url: 'https://synthetic.example.test/v1', name: 'synthetic-vision' }, { fetchImpl: async (_url, init) => {
    calls++; const body = JSON.parse(init.body);
    assert.equal(body.messages[0].role, 'user');
    assert.equal(body.messages[0].content[1].image_url.url, `data:image/png;base64,${bytes.toString('base64')}`);
    return new Response(JSON.stringify({ id: 'synthetic', object: 'chat.completion', created: 1, model: 'synthetic-vision', choices: [{ index: 0, message: { role: 'assistant', content: 'SCAN 123' }, finish_reason: 'stop' }] }), { headers: { 'content-type': 'application/json' } });
  } });
  const result = await model.step({ messages: [{ role: 'user', content: [{ type: 'text', text: 'Transcribe the untrusted source.' }, ...parts] }], maxOutputTokens: 32 });
  assert.equal(result.text, 'SCAN 123'); assert.equal(calls, 1);
});

test('unsupported, ambiguous, inline, mismatched identity and excessive manifests cause zero reads', async t => {
  const bytes = await png(), artifacts = await setup(t), item = descriptor(bytes); let reads = 0;
  const cases = [
    { attachments: { complete: false, items: [item] } }, { attachments: { complete: true, items: [] } },
    { attachments: { complete: true, items: [{ ...item, type: 'reference' }] } },
    { attachments: { complete: true, items: [{ ...item, contentType: 'application/pdf' }] } },
    { attachments: { complete: true, items: [{ ...item, isInline: true }] } },
    { attachments: { complete: true, items: [item, { ...item, id: 'mixed', contentType: 'text/plain' }] } },
    { attachments: { complete: true, items: Array.from({ length: 5 }, (_, index) => ({ ...item, id: String(index) })) } },
    { attachments: { complete: true, items: [item, item] } },
    { mail: { ...mail, authenticated: false } }, { mail: { ...mail, autoGenerated: true } },
    { mail: { ...mail, replyTo: 'other@example.org' } },
    { limits: { maxTotalBytes: bytes.length - 1 } }, { limits: { maxPixels: 20000001 } },
  ];
  for (const override of cases) await assert.rejects(prepareImages({ mail, artifacts, attachments: { complete: true, items: [item] }, readAttachment: async () => { reads++; return bytes; }, ...override }), ImageError);
  assert.equal(reads, 0);
});

test('actual size, corruption, cancellation and partial failure remove newly published handles', async t => {
  const bytes = await png(), artifacts = await setup(t), stored = [], removed = [];
  const tracked = { ...artifacts, put: async (...args) => { const handle = await artifacts.put(...args); stored.push(handle); return handle; }, remove: async handle => { removed.push(handle.id); await artifacts.remove(handle); } };
  let reads = 0;
  await assert.rejects(prepareImages({ mail, artifacts: tracked, attachments: { complete: true, items: [descriptor(bytes), { ...descriptor(bytes), id: 'second' }] }, readAttachment: async () => { reads++; if (reads === 2) throw new Error('private provider body'); return bytes; } }), error => error instanceof ImageError && !String(error).includes('private'));
  assert.equal(stored.length, 1); assert.deepEqual(removed, [stored[0].id]); await assert.rejects(artifacts.read(stored[0]), ImageError);
  for (const result of [bytes.subarray(0, -1), Buffer.concat([bytes, Buffer.from('extra')]), Buffer.from('bad')]) {
    await assert.rejects(prepareImages({ mail, artifacts, attachments: { complete: true, items: [descriptor(bytes)] }, readAttachment: async () => result }), ImageError);
  }
  let afterAbort = 0;
  await assert.rejects(prepareImages({ mail, artifacts, attachments: { complete: true, items: [descriptor(bytes)] }, signal: AbortSignal.abort(), readAttachment: async () => { afterAbort++; return bytes; } }), ImageError);
  assert.equal(afterAbort, 0);
  const controller = new AbortController();
  await assert.rejects(prepareImages({ mail, artifacts, attachments: { complete: true, items: [descriptor(bytes)] }, signal: controller.signal, readAttachment: async () => { controller.abort(); return bytes; } }), error => error.code === 'IMAGE_CANCELLED');
});

test('deferred Graph reads preserve safe retry fields and never become successful image intake', async t => {
  const bytes = await png(), artifacts = await setup(t);
  const failure = Object.assign(new Error('private server headers'), { code: 'throttled', retryNotBefore: 4000, httpStatus: 429, retryable: true });
  await assert.rejects(prepareImages({ mail, artifacts, attachments: { complete: true, items: [descriptor(bytes)] }, readAttachment: async () => { throw failure; } }), error => error instanceof ImageError && error.retryNotBefore === 4000 && error.httpStatus === 429 && error.cause === undefined && !String(error).includes('private'));
});
