import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { setImmediate as yieldControl } from 'node:timers/promises';
import { createRuntime } from '../src/runtime.mjs';
import { openStore } from '../src/store.mjs';
import { digest } from '../src/policy.mjs';

async function harness(t, overrides = {}) {
  const root = await mkdtemp(join(tmpdir(), 'mail-agent-operations-'));
  const config = {
    id: 'operations-test', state_root: './state',
    mailbox: { address: 'agent@example.org', tenant_id: 'tenant', client_id: 'client', poll_seconds: 30 },
    model: { capabilities: { tools: false } },
    policy: { senders: ['alice@example.org'], recipients: ['alice@example.org'], approvers: ['admin@example.org'], tools: {} },
    mcp: {}, limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000, output_tokens: 2000, queue_messages: 100 },
    retention: { content_hours: 24, audit_days: 30 }
  };
  if (overrides.mode === 'live') config.mailbox.sender_authentication = { transport_headers_verified: true };
  const loaded = {
    config, root, instructions: 'Answer helpfully.', hash: 'operations-config',
    model: { step: async () => ({ text: 'A useful reply.', toolCalls: [] }) },
    mail: { reply: async () => ({ status: 'accepted' }) },
    listenControl: async () => ({ close: async () => {} }),
    ...overrides
  };
  const runtime = await createRuntime(loaded);
  const runtimes = [runtime];
  t.after(async () => {
    for (const instance of [...runtimes].reverse()) await instance.stop();
    await rm(root, { recursive: true, force: true });
  });
  const restart = async () => {
    await runtimes.at(-1).stop();
    const instance = await createRuntime(loaded);
    runtimes.push(instance);
    return instance;
  };
  return { root, config, loaded, runtime, restart };
}

function message(id, overrides = {}) {
  return {
    id, conversationId: `conversation-${id}`, sender: 'alice@example.org',
    replyTo: 'alice@example.org', to: ['agent@example.org'], cc: [], subject: 'Question',
    body: 'Please explain.', receivedAt: '2026-01-01T00:00:00Z', authenticated: true,
    autoGenerated: false, attachments: false, ...overrides
  };
}

test('status preserves legacy fields and returns bounded, cursor-paginated run metadata', async t => {
  const h = await harness(t);
  for (const id of ['one', 'two', 'three']) assert.equal((await h.runtime.processMessage(message(id))).status, 'completed');

  const first = h.runtime.status({ limit: 1 });
  assert.equal(first.agent, h.config.id);
  assert.equal(first.mailbox, h.config.mailbox.address);
  assert.equal(first.dependencyError, null);
  assert.ok(Array.isArray(first.runs));
  assert.equal(first.runs.length, 1);
  assert.ok(first.nextCursor);
  assert.equal(first.counts.completed, 3);
  assert.equal(first.sync.baseline, 'not-started');

  const second = h.runtime.status({ limit: 1, after: first.nextCursor });
  assert.equal(second.runs.length, 1);
  assert.notEqual(second.runs[0].id, first.runs[0].id);
  assert.ok(second.nextCursor);
  const final = h.runtime.status({ limit: 1, after: second.nextCursor });
  assert.equal(final.runs.length, 1);
  assert.notEqual(final.runs[0].id, second.runs[0].id);
  assert.equal(h.runtime.status({ limit: 1, after: final.nextCursor }).runs.length, 0);
  assert.throws(() => h.runtime.status({ limit: 101 }), /Page limit/);
  assert.throws(() => h.runtime.status({ after: 'not-a-cursor' }), /Invalid metadata cursor/);
});

test('status filters runs without changing global counts', async t => {
  const h = await harness(t);
  await h.runtime.processMessage(message('complete'));
  await h.runtime.processMessage(message('ignored', { sender: 'outsider@example.org', replyTo: 'outsider@example.org' }));
  const status = h.runtime.status({ limit: 10, status: 'ignored' });
  assert.equal(status.runs.length, 1);
  assert.equal(status.runs[0].status, 'ignored');
  assert.equal(status.counts.completed, 1);
  assert.equal(status.counts.ignored, 1);
});

test('approval metadata keeps its legacy array form and supports validated bounded pages', async t => {
  const model = { step: async () => ({ text: '', toolCalls: [{
    id: 'proposal', name: 'records.add_note', args: { collection: 'intake', text: 'Synthetic note' }
  }] }) };
  const mcp = {
    listTools: async () => new Map([['records.add_note', {
      description: 'Append a synthetic note',
      inputSchema: { type: 'object', properties: { collection: { type: 'string' }, text: { type: 'string' } }, required: ['collection', 'text'], additionalProperties: false }
    }]]),
    call: async () => { throw new Error('Approval test must not execute the tool.'); },
    close: async () => {}
  };
  const h = await harness(t, { model, mcp });
  h.config.model.capabilities.tools = true;
  h.config.policy.tools['records.add_note'] = {
    effect: 'write', authorization: 'approval',
    constraints: { type: 'object', properties: { collection: { const: 'intake' }, text: { maxLength: 2000 } } }
  };
  assert.equal((await h.runtime.processMessage(message('approval-one'))).status, 'awaiting_approval');
  assert.equal((await h.runtime.processMessage(message('approval-two'))).status, 'awaiting_approval');

  const legacy = h.runtime.approvals();
  assert.ok(Array.isArray(legacy));
  assert.equal(legacy.length, 2);
  const first = h.runtime.approvals({ limit: 1 });
  assert.equal(first.items.length, 1);
  assert.ok(first.nextCursor);
  const second = h.runtime.approvals({ limit: 1, after: first.nextCursor });
  assert.equal(second.items.length, 1);
  assert.notEqual(second.items[0].runId, first.items[0].runId);
  assert.throws(() => h.runtime.approvals({ limit: 101 }), /Page limit/);
});

test('pending approvals count against the configured queue capacity', async t => {
  const model = { step: async () => ({ text: '', toolCalls: [{
    id: 'proposal', name: 'records.add_note', args: { collection: 'intake', text: 'Synthetic note' }
  }] }) };
  const mcp = {
    listTools: async () => new Map([['records.add_note', {
      inputSchema: { type: 'object', properties: { collection: { type: 'string' }, text: { type: 'string' } }, required: ['collection', 'text'], additionalProperties: false }
    }]]),
    call: async () => { throw new Error('Capacity test must not execute the tool.'); }, close: async () => {}
  };
  const h = await harness(t, { model, mcp });
  h.config.limits.queue_messages = 1;
  h.config.model.capabilities.tools = true;
  h.config.policy.tools['records.add_note'] = {
    effect: 'write', authorization: 'approval',
    constraints: { type: 'object', properties: { collection: { const: 'intake' }, text: { maxLength: 2000 } } }
  };
  assert.equal((await h.runtime.processMessage(message('capacity-one'))).status, 'awaiting_approval');
  await assert.rejects(h.runtime.processMessage(message('capacity-two')), /Queue capacity reached/);
  assert.equal(h.runtime.status().counts.awaiting_approval, 1);
});

test('health reports current process liveness and resolves outside a blocked intake operation', async t => {
  let enterPoll;
  let releasePoll;
  const polling = new Promise(resolve => { releasePoll = resolve; });
  const entered = new Promise(resolve => { enterPoll = resolve; });
  const mail = {
    poll: async () => {
      enterPoll();
      return polling;
    }
  };
  const listenControl = async () => ({ close: async () => {} });
  const h = await harness(t, { mode: 'live', mail, listenControl });
  assert.equal(h.runtime.health().live, false);
  const started = h.runtime.start();
  await entered;
  const health = h.runtime.health();
  assert.equal(health.live, true);
  assert.equal(health.ready, false);
  assert.equal(health.reason, 'baseline-pending');
  releasePoll({ messages: [], cursor: JSON.stringify({ initialComplete: true }) });
  await h.runtime.stop();
  await started;
});

test('health reports stale synchronization while the daemon remains live', async t => {
  let now = 1_000;
  let polls = 0;
  let enterSecondPoll;
  let releaseSecondPoll;
  const secondPollEntered = new Promise(resolve => { enterSecondPoll = resolve; });
  const secondPoll = new Promise(resolve => { releaseSecondPoll = resolve; });
  const mail = { poll: async () => {
    polls++;
    if (polls === 1) return { messages: [], cursor: JSON.stringify({ initialComplete: true }) };
    enterSecondPoll();
    return secondPoll;
  } };
  const h = await harness(t, { mode: 'live', mail, clock: () => now });
  h.config.mailbox.poll_seconds = 0;
  const started = h.runtime.start();
  await secondPollEntered;
  now += 120_000;
  const health = h.runtime.health();
  assert.equal(health.live, true);
  assert.equal(health.ready, false);
  assert.equal(health.reason, 'intake-stale');
  assert.equal(health.sync.baseline, 'complete');
  releaseSecondPoll({ messages: [], cursor: JSON.stringify({ initialComplete: true }) });
  await h.runtime.stop();
  await started;
});

test('health becomes ready after a successful baseline while the daemon stays live', async t => {
  let polls = 0;
  let enterSecondPoll;
  let releaseSecondPoll;
  const secondPollEntered = new Promise(resolve => { enterSecondPoll = resolve; });
  const secondPoll = new Promise(resolve => { releaseSecondPoll = resolve; });
  const mail = { poll: async () => {
    polls++;
    if (polls === 1) return { messages: [], cursor: JSON.stringify({ initialComplete: true }) };
    enterSecondPoll();
    return secondPoll;
  } };
  const h = await harness(t, { mode: 'live', mail, clock: () => 10_000 });
  h.config.mailbox.poll_seconds = 0;
  const started = h.runtime.start();
  await secondPollEntered;
  const health = h.runtime.health();
  assert.equal(health.live, true);
  assert.equal(health.ready, true);
  assert.equal(health.reason, 'ready');
  assert.equal(health.sync.baseline, 'complete');
  releaseSecondPoll({ messages: [], cursor: JSON.stringify({ initialComplete: true }) });
  await h.runtime.stop();
  await started;
});

test('invalid persisted cursor remains visible as an unhealthy baseline', async t => {
  const h = await harness(t, { mode: 'live' });
  await h.runtime.stop();
  const store = openStore(join(h.root, 'state'), {
    identity: digest([h.config.id, h.config.mailbox.tenant_id, h.config.mailbox.client_id, h.config.mailbox.address])
  });
  store.setMeta('cursor', '{malformed');
  store.close();

  const restarted = await h.restart();
  const started = restarted.start();
  await yieldControl();
  const health = restarted.health();
  assert.equal(health.live, true);
  assert.equal(health.ready, false);
  assert.equal(health.reason, 'invalid-cursor');
  assert.equal(health.sync.baseline, 'invalid');
  await restarted.stop();
  await started;
});

test('health exposes a future provider retry deadline during the backoff window', async t => {
  let now = 1_000;
  let enteredPoll;
  const polled = new Promise(resolve => { enteredPoll = resolve; });
  const mail = { poll: async () => {
    enteredPoll();
    throw Object.assign(new Error('synthetic throttle'), { diagnosticCode: 'throttled', retryNotBefore: now + 60_000 });
  } };
  const h = await harness(t, { mode: 'live', mail, clock: () => now });
  const started = h.runtime.start();
  await polled;
  await yieldControl();
  const health = h.runtime.health();
  assert.equal(health.live, true);
  assert.equal(health.ready, false);
  assert.equal(health.sync.retryNotBefore, 61_000);
  assert.equal(health.reason, 'provider-backoff');
  await h.runtime.stop();
  await started;
});

test('provider retry deadline survives restart and suppresses early polling', async t => {
  let now = 10_000;
  let polls = 0;
  const mail = {
    poll: async () => {
      polls++;
      if (polls === 1) throw Object.assign(new Error('safe throttling failure'), {
        diagnosticCode: 'throttled', retryNotBefore: now + 60_000
      });
      return { messages: [], cursor: JSON.stringify({ initialComplete: true }) };
    }
  };
  const h = await harness(t, { mail, clock: () => now });
  const failed = await h.runtime.start({ once: true });
  assert.equal(polls, 1);
  assert.equal(failed.sync.retryNotBefore, 70_000);
  assert.equal(failed.sync.lastFailure.code, 'throttled');

  const restarted = await h.restart();
  const deferred = await restarted.start({ once: true });
  assert.equal(polls, 1);
  assert.equal(deferred.sync.retryNotBefore, 70_000);

  now = 70_000;
  await restarted.start({ once: true });
  assert.equal(polls, 2);
  assert.equal(restarted.status().sync.retryNotBefore, null);
});

test('Retry-After observed during shutdown cancellation survives restart', async t => {
  let now = 20_000;
  let polls = 0;
  let enterPoll;
  const polling = new Promise(resolve => { enterPoll = resolve; });
  const mail = { poll: async ({ signal }) => {
    polls++;
    if (polls > 1) return { messages: [], cursor: JSON.stringify({ initialComplete: true }) };
    enterPoll();
    return new Promise((_, reject) => {
      signal.addEventListener('abort', () => reject(Object.assign(new Error('cancelled poll'), {
        name: 'AbortError', retryNotBefore: now + 60_000
      })), { once: true });
    });
  } };
  const h = await harness(t, { mail, clock: () => now });
  const started = h.runtime.start();
  await polling;
  await h.runtime.stop();
  await started;
  assert.equal(h.runtime.status().sync.retryNotBefore, 80_000);

  const restarted = await h.restart();
  const deferred = await restarted.start({ once: true });
  assert.equal(polls, 1);
  assert.equal(deferred.sync.retryNotBefore, 80_000);
  now = 80_000;
  await restarted.start({ once: true });
  assert.equal(polls, 2);
});

test('attachment metadata throttling queues the request and prevents Graph work until Retry-After', async t => {
  let now = 30_000;
  let metadataCalls = 0, messageCalls = 0, replies = 0, modelCalls = 0, polls = 0;
  const model = { step: async () => { modelCalls++; return { text: 'Should not infer.', toolCalls: [] }; } };
  const mail = {
    getAttachmentMetadata: async () => {
      metadataCalls++;
      if (metadataCalls === 1) throw Object.assign(new Error('synthetic metadata throttle'), {
        diagnosticCode: 'throttled', retryNotBefore: now + 60_000
      });
      return { kind: 'document', count: 1 };
    },
    getMessage: async id => { messageCalls++; return message(id, { attachmentStatus: 'unknown' }); },
    reply: async () => { replies++; return { status: 'accepted' }; },
    poll: async () => { polls++; return { messages: [], cursor: JSON.stringify({ initialComplete: true }) }; }
  };
  const h = await harness(t, { mail, model, clock: () => now });
  const result = await h.runtime.processMessage(message('attachment-throttled', { attachmentStatus: 'unknown' }));
  assert.equal(result.status, 'queued');
  assert.equal(replies, 0);
  assert.equal(modelCalls, 0);
  assert.equal(metadataCalls, 1);

  const restarted = await h.restart();
  const deferred = await restarted.start({ once: true });
  assert.equal(metadataCalls, 1);
  assert.equal(messageCalls, 0);
  assert.equal(replies, 0);
  assert.equal(deferred.counts.queued, 1);
  assert.equal(polls, 0);

  now = 90_000;
  const resumed = await restarted.start({ once: true });
  assert.equal(metadataCalls, 2);
  assert.equal(messageCalls, 1);
  assert.equal(replies, 1);
  assert.equal(modelCalls, 0);
  assert.equal(resumed.counts.completed, 1);
});

test('Graph cooldown during an MCP pending call stays queued instead of sending a denial reply', async t => {
  let now = 40_000;
  let getMessageCalls = 0, mcpCalls = 0, replies = 0, modelSteps = 0;
  const model = { step: async () => {
    modelSteps++;
    return modelSteps === 1
      ? { text: '', toolCalls: [{ id: 'read-1', name: 'records.read', args: { target: 'synthetic' } }] }
      : { text: 'Read complete.', toolCalls: [] };
  } };
  const mcp = {
    listTools: async () => new Map([['records.read', {
      inputSchema: { type: 'object', properties: { target: { const: 'synthetic' } }, required: ['target'], additionalProperties: false }
    }]]),
    call: async () => { mcpCalls++; return { content: [{ type: 'text', text: 'Synthetic data.' }] }; }, close: async () => {}
  };
  const mail = {
    getMessage: async id => {
      getMessageCalls++;
      if (getMessageCalls === 1) throw Object.assign(new Error('synthetic Graph throttle'), {
        diagnosticCode: 'throttled', retryNotBefore: now + 60_000
      });
      return message(id);
    },
    reply: async () => { replies++; return { status: 'accepted' }; }
  };
  const h = await harness(t, { mail, model, mcp, clock: () => now });
  h.config.model.capabilities.tools = true;
  h.config.policy.tools['records.read'] = {
    effect: 'read', authorization: 'automatic',
    constraints: { type: 'object', properties: { target: { const: 'synthetic' } } }
  };

  const pending = await h.runtime.processMessage(message('mcp-cooldown'));
  assert.equal(pending.status, 'queued');
  assert.equal(replies, 0);
  assert.equal(mcpCalls, 0);
  assert.equal(h.runtime.status().counts.queued, 1);

  const restarted = await h.restart();
  const deferred = await restarted.start({ once: true });
  assert.equal(deferred.counts.queued, 1);
  assert.equal(getMessageCalls, 1);
  assert.equal(mcpCalls, 0);
  assert.equal(replies, 0);

  now = 100_000;
  const resumed = await restarted.start({ once: true });
  assert.ok(getMessageCalls > 1);
  assert.equal(mcpCalls, 1);
  assert.equal(replies, 1);
  assert.equal(resumed.counts.completed, 1);
});

test('deferred intake still drains durable queued work before its provider retry deadline', async t => {
  let now = 10_000;
  let polls = 0;
  let holdModel = false;
  let enterModel;
  const enteredModel = new Promise(resolve => { enterModel = resolve; });
  let releaseModel;
  const held = new Promise(resolve => { releaseModel = resolve; });
  const sent = [];
  const model = {
    step: async () => {
      if (holdModel) {
        enterModel();
        await held;
      }
      return { text: 'Durably resumed.', toolCalls: [] };
    }
  };
  const mail = {
    poll: async () => {
      polls++;
      if (polls === 1) throw Object.assign(new Error('synthetic provider throttle'), {
        diagnosticCode: 'throttled', retryNotBefore: now + 60_000
      });
      return { messages: [], cursor: JSON.stringify({ initialComplete: true }) };
    },
    reply: async input => { sent.push(input.id); return { status: 'accepted' }; }
  };
  const h = await harness(t, { mail, model, clock: () => now });
  await h.runtime.start({ once: true });

  holdModel = true;
  const processing = h.runtime.processMessage(message('queued-during-backoff'));
  await enteredModel;
  await h.runtime.stop();
  assert.equal((await processing).status, 'queued');
  holdModel = false;
  releaseModel();

  const restarted = await h.restart();
  const status = await restarted.start({ once: true });
  assert.deepEqual(sent, []);
  assert.equal(polls, 1);
  assert.equal(status.sync.retryNotBefore, 70_000);
  assert.equal(status.counts.ready_to_send, 1);
  assert.equal(status.counts.completed, 0);

  now = 70_000;
  const resumed = await restarted.start({ once: true });
  assert.deepEqual(sent, ['queued-during-backoff']);
  assert.equal(resumed.counts.completed, 1);
  assert.equal(sent.length, 1);
});

test('categorized model failure remains in history after successful mailbox polling and later model recovery', async t => {
  let now = 5_000;
  let failedOnce = false;
  const model = { step: async () => {
    if (!failedOnce) {
      failedOnce = true;
      throw Object.assign(new Error('synthetic model outage'), { diagnosticCode: 'model-unsupported' });
    }
    return { text: 'Recovered.', toolCalls: [] };
  } };
  const mail = { poll: async ({ cursor }) => ({ messages: [], cursor: cursor ?? JSON.stringify({ initialComplete: true }) }) };
  const h = await harness(t, { model, mail, clock: () => now });
  await h.runtime.start({ once: true });
  assert.equal(h.runtime.status().sync.lastSuccessAt, now);

  now += 10;
  await h.runtime.processMessage(message('model-failure'));
  const failure = h.runtime.status().failures.model;
  assert.equal(failure.code, 'model-unsupported');
  assert.equal(failure.at, now);
  assert.equal(failure.resolvedAt, null);

  now += 10;
  await h.runtime.start({ once: true });
  const stillRecorded = h.runtime.status().failures.model;
  assert.equal(stillRecorded.at, failure.at);
  assert.equal(stillRecorded.resolvedAt, null);

  now += 10;
  await h.runtime.processMessage(message('model-recovered'));
  const recovered = h.runtime.status().failures.model;
  assert.equal(recovered.code, 'model-unsupported');
  assert.equal(recovered.at, failure.at);
  assert.equal(recovered.resolvedAt, now);
});

test('malformed model output is retained as an invalid-response diagnostic', async t => {
  const h = await harness(t, { model: { step: async () => ({ text: 42, toolCalls: [] }) } });
  assert.equal((await h.runtime.processMessage(message('invalid-model-output'))).status, 'completed');
  assert.equal(h.runtime.status().failures.model.code, 'invalid-response');
});

test('MCP read failures retain their category across mailbox polling and resolve on a successful MCP read', async t => {
  let failRead = true;
  let modelSteps = 0;
  const model = { step: async () => {
    modelSteps++;
    return modelSteps % 2 === 1
      ? { text: '', toolCalls: [{ id: `read-${modelSteps}`, name: 'records.read', args: { target: 'synthetic' } }] }
      : { text: 'Read complete.', toolCalls: [] };
  } };
  const mcp = {
    listTools: async () => new Map([['records.read', {
      inputSchema: { type: 'object', properties: { target: { const: 'synthetic' } }, required: ['target'], additionalProperties: false }
    }]]),
    call: async () => {
      if (failRead) throw Object.assign(new Error('synthetic MCP outage'), { diagnosticCode: 'tool-unavailable' });
      return { content: [{ type: 'text', text: 'Synthetic result.' }] };
    },
    close: async () => {}
  };
  const mail = { poll: async ({ cursor }) => ({ messages: [], cursor: cursor ?? JSON.stringify({ initialComplete: true }) }) };
  const h = await harness(t, { model, mcp, mail });
  h.config.model.capabilities.tools = true;
  h.config.policy.tools['records.read'] = {
    effect: 'read', authorization: 'automatic',
    constraints: { type: 'object', properties: { target: { const: 'synthetic' } } }
  };

  await h.runtime.processMessage(message('mcp-read-fails'));
  const failure = h.runtime.status().failures.mcp;
  assert.equal(failure.code, 'tool-unavailable');
  assert.equal(failure.resolvedAt, null);
  await h.runtime.start({ once: true });
  assert.equal(h.runtime.status().failures.mcp.at, failure.at);
  assert.equal(h.runtime.status().failures.mcp.resolvedAt, null);

  failRead = false;
  await h.runtime.processMessage(message('mcp-read-recovers'));
  assert.equal(h.runtime.status().failures.mcp.code, 'tool-unavailable');
  assert.notEqual(h.runtime.status().failures.mcp.resolvedAt, null);
});

test('uncertain send remains fenced across restart and records a safe send category', async t => {
  let attempts = 0;
  let modelCalls = 0;
  const model = { step: async () => { modelCalls++; return { text: 'A reply.', toolCalls: [] }; } };
  const mail = { reply: async () => {
    attempts++;
    throw Object.assign(new Error('private transport details'), { diagnosticCode: 'connection', uncertain: true });
  } };
  const h = await harness(t, { model, mail });
  assert.equal((await h.runtime.processMessage(message('uncertain-send'))).status, 'uncertain');
  assert.equal(h.runtime.status().failures.send.code, 'connection');
  const restarted = await h.restart();
  assert.equal((await restarted.processMessage(message('uncertain-send'))).status, 'uncertain');
  assert.equal(attempts, 1);
  assert.equal(modelCalls, 1);
});
