import assert from 'node:assert/strict';
import test from 'node:test';
import { chmod, mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { runCli } from '../src/cli.mjs';
import { loadConfig } from '../src/config.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';
import { digest } from '../src/policy.mjs';
import { openStore } from '../src/store.mjs';
import { createRuntime } from '../src/runtime.mjs';
import { backupState } from '../src/backup.mjs';
import { restoreState } from '../src/restore.mjs';
import { inspectRecovery } from '../src/recovery-inspect.mjs';
import { previewRecovery, applyRecovery } from '../src/recovery-apply.mjs';

const fixedNow = 1_800_000_000_000;
const clock = () => fixedNow;
const actualServices = {
  backupState: settings => backupState({ ...settings, clock }),
  restoreState: settings => restoreState({ ...settings, clock }),
  inspectRecovery: settings => inspectRecovery({ ...settings, clock }),
  previewRecovery: settings => previewRecovery({ ...settings, clock }),
  applyRecovery: settings => applyRecovery({ ...settings, clock }),
};

function output() {
  let value = '';
  return { write(text) { value += text; }, value() { return value; } };
}

async function invoke(args, services = actualServices) {
  const stdout = output(), stderr = output();
  const code = await runCli(args, { stdout, stderr, env: {}, ...services });
  return { code, stdout: stdout.value(), stderr: stderr.value() };
}

function parse(result) {
  assert.equal(result.code, 0, result.stderr);
  return JSON.parse(result.stdout);
}

function evidence(source, recordHash, observedAt) { return { source, recordHash, observedAt }; }

test('CLI backup, restore, inspection, preview and apply form a private held-state recovery journey', async t => {
  const parent = await mkdtemp(join(tmpdir(), 'ma-recovery-journey-'));
  t.after(() => rm(parent, { recursive: true, force: true }));
  const bundle = join(parent, 'bundle');
  const initialized = await invoke(['init', '--directory', bundle, '--recipe', 'text-inbox', '--id', 'synthetic-agent', '--state-root', './source-state',
    '--mailbox', 'agent@tenant.test', '--tenant', 'tenant-123', '--client', 'client-123', '--model-url', 'https://model.tenant.test/v1', '--model', 'model-v1',
    '--senders', 'alice@tenant.test', '--recipients', 'alice@tenant.test', '--auth-profile', 'dmarc', '--authserv-ids', 'mx.tenant.test']);
  assert.equal(initialized.code, 0, initialized.stderr);
  const filename = join(bundle, 'agent.yaml');
  let loaded = await loadConfig(filename, { env: {} });
  const identity = mailboxIdentity(loaded.config);
  const now = fixedNow;
  const sourceStore = openStore(loaded.config.state_root, { identity, clock: () => now });
  sourceStore.setMeta('cursor', 'cursor-before-restore');
  sourceStore.saveRun({ id: 'run-synthetic', messageKey: digest(['synthetic-agent', 'message-synthetic']), conversationKey: digest('conversation-synthetic'), sequence: 1,
    status: 'queued', createdAt: now, budget: { modelCalls: 1, toolCalls: 0, activeMs: 50 },
    mail: { id: 'source-message', sender: 'alice@tenant.test', to: ['agent@tenant.test'], body: 'SYNTHETIC_PRIVATE_BODY', authenticated: true, autoGenerated: false } });
  sourceStore.saveRun({ id: 'action-run-synthetic', messageKey: digest(['synthetic-agent', 'action-message-synthetic']), conversationKey: digest('action-conversation-synthetic'), sequence: 2,
    status: 'uncertain', createdAt: now, budget: { modelCalls: 0, toolCalls: 0, activeMs: 0 }, uncertainty: { kind: 'tool', key: 'action-synthetic' } });
  sourceStore.saveAction({ key: 'action-synthetic', runId: 'action-run-synthetic', state: 'uncertain', effect: 'write', tool: 'records.append', args: { private: 'SYNTHETIC_PRIVATE_ARGS' } });
  sourceStore.close();

  const snapshot = join(parent, 'snapshot');
  parse(await invoke(['backup', '--config', filename, '--directory', snapshot]));
  const configText = await readFile(filename, 'utf8');
  await writeFile(filename, configText.replace('state_root: ./source-state', 'state_root: ./restored-state'));
  await chmod(filename, 0o600);
  loaded = await loadConfig(filename, { env: {} });
  const restored = parse(await invoke(['restore', '--config', filename, '--snapshot', snapshot, '--actor', 'operator@tenant.test', '--reason', 'Synthetic recovery acceptance']));
  assert.deepEqual(restored, { snapshotId: restored.snapshotId, stateRoot: await realpath(loaded.config.state_root), stateSchema: 5, recoveryRequired: true });

  const runListing = parse(await invoke(['recovery-inspect', '--config', filename, '--kind', 'runs', '--limit', '100']));
  const actionListing = parse(await invoke(['recovery-inspect', '--config', filename, '--kind', 'actions', '--limit', '100']));
  const run = runListing.items.find(item => item.id === 'run-synthetic');
  const action = actionListing.items.find(item => item.key === 'action-synthetic');
  assert.ok(run?.fingerprint);
  assert.ok(action?.fingerprint);
  assert.equal(runListing.recovery.required, true);

  const observedAt = fixedNow;
  const plan = { format: 1, mailboxIdentity: identity, snapshotId: runListing.recovery.snapshotId, binding: runListing.binding, configHash: runListing.configHash,
    operations: [
      { kind: 'run', id: run.id, fingerprint: run.fingerprint, outcome: 'resume', evidence: evidence('graph', 'a'.repeat(64), observedAt) },
      { kind: 'action', key: action.key, fingerprint: action.fingerprint, outcome: 'no-effect', evidence: evidence('adapter', 'b'.repeat(64), observedAt) },
      { kind: 'message', messageId: 'post-snapshot-message', conversationId: 'post-snapshot-conversation', outcome: 'sent',
        evidence: evidence('graph', 'c'.repeat(64), observedAt) }
    ] };
  const planPath = join(parent, 'recovery-plan.json');
  await writeFile(planPath, `${JSON.stringify(plan)}\n`, { mode: 0o600 });
  await chmod(planPath, 0o600);

  const preview = parse(await invoke(['recovery-preview', '--config', filename, '--plan', planPath]));
  assert.equal(preview.applied, false);
  assert.equal(preview.operations.length, 3);
  assert.doesNotMatch(JSON.stringify(preview), /SYNTHETIC_PRIVATE/);
  const expectedDigest = digest(plan);
  assert.equal(preview.planDigest, expectedDigest);

  const db = new DatabaseSync(join(loaded.config.state_root, 'agent.sqlite'));
  const cursor = db.prepare("SELECT value FROM meta WHERE key='cursor'").get().value;
  db.prepare("UPDATE meta SET value=? WHERE key='cursor'").run('cursor-stale-synthetic');
  db.close();
  const applyArgs = ['recovery-apply', '--config', filename, '--plan', planPath, '--digest', expectedDigest, '--actor', 'operator@tenant.test', '--reason', 'Synthetic recovery acceptance'];
  const stale = await invoke(applyArgs);
  assert.equal(stale.code, 1);
  assert.match(stale.stderr, /Recovery command could not complete/);
  const restoreCursor = new DatabaseSync(join(loaded.config.state_root, 'agent.sqlite'));
  restoreCursor.prepare("UPDATE meta SET value=? WHERE key='cursor'").run(cursor);
  restoreCursor.close();
  const wrongDigest = expectedDigest === 'f'.repeat(64) ? 'e'.repeat(64) : 'f'.repeat(64);
  const mismatch = await invoke(['recovery-apply', '--config', filename, '--plan', planPath, '--digest', wrongDigest, '--actor', 'operator@tenant.test', '--reason', 'Synthetic recovery acceptance']);
  assert.equal(mismatch.code, 1);
  assert.match(mismatch.stderr, /Recovery command could not complete/);

  const beforeApply = new DatabaseSync(join(loaded.config.state_root, 'agent.sqlite'));
  assert.equal(beforeApply.prepare("SELECT count(*) AS count FROM audit WHERE event='recovery-decision'").get().count, 0);
  beforeApply.close();
  const applied = parse(await invoke(applyArgs));
  assert.equal(applied.applied, true);
  assert.equal(applied.idempotent, false);
  assert.equal(applied.operations.length, 3);
  const retried = parse(await invoke(applyArgs));
  assert.equal(retried.applied, true);
  assert.equal(retried.idempotent, true);

  const afterApply = new DatabaseSync(join(loaded.config.state_root, 'agent.sqlite'), { readOnly: true });
  try {
    assert.equal(afterApply.prepare("SELECT count(*) AS count FROM audit WHERE event='recovery-decision'").get().count, 3);
    assert.equal(afterApply.prepare("SELECT count(*) AS count FROM audit WHERE event='recovery-decision' AND actor=?").get(digest('operator@tenant.test')).count, 3);
    assert.equal(afterApply.prepare('SELECT status FROM runs WHERE id=?').get('run-synthetic').status, 'queued');
    assert.equal(afterApply.prepare('SELECT status FROM runs WHERE message_key=?').get(digest(['synthetic-agent', 'post-snapshot-message'])).status, 'completed');
    assert.equal(afterApply.prepare("SELECT value FROM meta WHERE key='restore_hold'").get().value.length > 0, true);
  } finally { afterApply.close(); }

  const effects = { mailbox: 0, model: 0, mcp: 0 };
  const runtime = await createRuntime({ root: bundle, mode: 'operator', config: loaded.config, clock,
    mail: { check: async () => { effects.mailbox++; }, poll: async () => { effects.mailbox++; }, send: async () => { effects.mailbox++; } },
    model: { step: async () => { effects.model++; } }, mcp: { listTools: async () => { effects.mcp++; }, call: async () => { effects.mcp++; } } });
  try {
    await assert.rejects(runtime.processMessage({ id: 'later-synthetic', conversationId: 'conversation-later', sender: 'alice@tenant.test', to: [], body: 'synthetic', subject: '' }),
      /Restored state requires provider reconciliation/);
    await assert.rejects(runtime.start({ once: true }), /Restored state requires provider reconciliation/);
    assert.deepEqual(effects, { mailbox: 0, model: 0, mcp: 0 });
  } finally { await runtime.stop(); }
});
