import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRuntime } from '../src/runtime.mjs';
import { openStore } from '../src/store.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';

const SNAPSHOT_ID = '00000000-0000-4000-8000-000000000006';
const SNAPSHOT_CREATED_AT = 1_700_000_000_000;
const RESTORED_AT = 1_700_000_100_000;

function config() {
  return {
    id: 'restore-hold-test', state_root: './state',
    mailbox: { address: 'agent@example.org', tenant_id: 'synthetic-tenant', client_id: 'synthetic-client', poll_seconds: 30 },
    model: { capabilities: { tools: true } },
    policy: { senders: ['alice@example.org'], recipients: ['alice@example.org'], approvers: ['admin@example.org'],
      tools: { 'records.append': { effect: 'write', authorization: 'approval' } } },
    mcp: {}, limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000, output_tokens: 2000, queue_messages: 100 },
    retention: { content_hours: 24, audit_days: 30 }
  };
}

function record(id, sequence, status, extra = {}) {
  return {
    id, messageKey: `message-${id}`, conversationKey: `conversation-${id}`, sequence, status,
    createdAt: 1_700_000_000_000 + sequence, budget: { modelCalls: 2, toolCalls: 1, activeMs: 37 },
    mail: { sender: 'alice@example.org', replyTo: 'alice@example.org', to: ['agent@example.org'], body: 'synthetic' },
    ...extra
  };
}

function adapters(calls) {
  return {
    model: { step: async () => { calls.model++; return { text: 'synthetic', toolCalls: [] }; } },
    mail: {
      poll: async () => { calls.poll++; return { messages: [], cursor: JSON.stringify({ initialComplete: true }) }; },
      check: async () => { calls.check++; return { status: 'ready' }; },
      getMessage: async () => { calls.getMessage++; return {}; },
      getAttachmentMetadata: async () => { calls.metadata++; return { kind: 'none', count: 0 }; },
      reply: async () => { calls.reply++; return { status: 'accepted' }; }
    },
    mcp: {
      listTools: async () => { calls.listTools++; return new Map(); },
      call: async () => { calls.mcpCall++; return { content: [] }; },
      close: async () => {}
    },
    listenControl: async () => ({ close: async () => {} })
  };
}

async function heldRuntime(t, holdValue,seed=()=>{}) {
  const root = await mkdtemp(join(tmpdir(), 'ma-restore-hold-'));
  const cfg = config();
  const stateRoot = join(root, cfg.state_root);
  const store = openStore(stateRoot, { identity: mailboxIdentity(cfg), clock: () => RESTORED_AT });
  store.setMeta('cursor', JSON.stringify({ initialComplete: true, delta: 'synthetic-cursor' }));
  store.saveRun(record('queued-run', 1, 'queued', { mail: {
    id: 'queued-message', conversationId: 'queued-conversation', sender: 'alice@example.org', replyTo: 'alice@example.org',
    to: ['agent@example.org'], cc: [], subject: 'synthetic', body: 'synthetic', receivedAt: '2026-01-01T00:00:00Z',
    authenticated: true, autoGenerated: false, attachments: false
  } }));
  store.saveRun(record('approval-run', 2, 'awaiting_approval', {
    approval: { id: 'approval-held', tool: 'records.append', args: { value: 'synthetic' }, policyHash: 'synthetic-policy', expiresAt: RESTORED_AT + 100_000 }
  }));
  store.saveRun(record('uncertain-run', 3, 'uncertain', { uncertainty: { kind: 'tool', key: 'action-held' } }));
  store.saveAction({ key: 'action-held', runId: 'uncertain-run', state: 'uncertain', effect: 'write', tool: 'records.append' });
  store.setMeta('restore_hold', holdValue);
  seed(store);
  store.close();

  const calls = { poll: 0, check: 0, getMessage: 0, metadata: 0, reply: 0, model: 0, listTools: 0, mcpCall: 0 };
  const runtime = await createRuntime({
    config: cfg, root, instructions: 'Synthetic restore hold test.', hash: 'synthetic',
    clock: () => RESTORED_AT, ...adapters(calls)
  });
  t.after(async () => { await runtime.stop(); await rm(root, { recursive: true, force: true }); });
  return { root, stateRoot, config: cfg, runtime, calls, storeMeta: () => {
    const database = new DatabaseSync(join(stateRoot, 'agent.sqlite'), { readOnly: true });
    try { return database.prepare("SELECT value FROM meta WHERE key='restore_hold'").get()?.value; }
    finally { database.close(); }
  } };
}

const validHold = () => JSON.stringify({ snapshotId: SNAPSHOT_ID, snapshotCreatedAt: SNAPSHOT_CREATED_AT, restoredAt: RESTORED_AT });

function assertNoAdapterEffects(calls) {
  assert.deepEqual(calls, { poll: 0, check: 0, getMessage: 0, metadata: 0, reply: 0, model: 0, listTools: 0, mcpCall: 0 });
}

async function tryGuardedOperations(runtime) {
  const operator = { actor: 'admin@example.org', reason: 'Synthetic reconciliation review.' };
  const checks = [
    () => runtime.start({ once: true }),
    () => runtime.liveCheck(),
    () => runtime.processMessage({
      id: 'must-not-admit', conversationId: 'must-not-admit', sender: 'alice@example.org',
      replyTo: 'alice@example.org', to: ['agent@example.org'], cc: [], subject: 'synthetic', body: 'synthetic'
    }),
    () => runtime.approve({ id: 'approval-held', ...operator }),
    () => runtime.resolve({ runId: 'uncertain-run', outcome: 'sent', ...operator })
  ];
  const outcomes = [];
  for (const check of checks) {
    try { outcomes.push({ ok: true, value: await check() }); }
    catch (error) { outcomes.push({ ok: false, message: error.message }); }
  }
  return outcomes;
}

test('valid restore hold permits inspection but blocks every execution or operator mutation path', async t => {
  const h = await heldRuntime(t, validHold());
  const outcomes = await tryGuardedOperations(h.runtime);
  assert.equal(outcomes.length, 5);
  assert.ok(outcomes.every(outcome => !outcome.ok && /restore|recovery/i.test(outcome.message)));

  const initial = h.runtime.status();
  const initialApproval = h.runtime.approvals();
  assert.deepEqual(initial.recovery, {
    required: true, snapshotId: SNAPSHOT_ID, snapshotCreatedAt: SNAPSHOT_CREATED_AT,
    restoredAt: RESTORED_AT, reason: 'restore-reconciliation'
  });
  assert.equal(initial.sync.baseline, 'complete');
  assert.equal(initial.counts.queued, 1);
  assert.equal(initial.counts.awaiting_approval, 1);
  assert.equal(initial.counts.uncertain, 1);
  assert.equal(initial.runs.find(run => run.id === 'queued-run').budget.modelCalls, 2);
  assert.equal(initialApproval.length, 1);
  assert.equal(initialApproval[0].id, 'approval-held');
  assert.equal(h.runtime.health().ready, false);
  assert.equal(h.runtime.health().reason, 'recovery-required');

  assertNoAdapterEffects(h.calls);
  const after = h.runtime.status();
  assert.equal(after.counts.queued, 1);
  assert.equal(after.counts.awaiting_approval, 1);
  assert.equal(after.counts.uncertain, 1);
  assert.equal(after.runs.length, initial.runs.length);
  assert.equal(h.storeMeta(), validHold());
});

test('malformed nonempty restore hold fails closed and remains inspectable', async t => {
  const h = await heldRuntime(t, '{malformed-hold');
  const outcomes = await tryGuardedOperations(h.runtime);
  assert.equal(outcomes.length, 5);
  assert.ok(outcomes.every(outcome => !outcome.ok && /restore|recovery/i.test(outcome.message)));
  const status = h.runtime.status();
  assert.equal(status.recovery.required, true);
  assert.equal(status.recovery.reason, 'invalid-record');
  assert.equal(h.runtime.health().ready, false);
  assert.equal(h.runtime.health().reason, 'recovery-required');
  assertNoAdapterEffects(h.calls);
  assert.equal(h.storeMeta(), '{malformed-hold');
});

test('present empty restore hold fails closed rather than authorizing execution', async t => {
  const h=await heldRuntime(t,'');
  assert.equal(h.runtime.status().recovery?.reason,'invalid-record');
  assert.equal(h.runtime.health().reason,'recovery-required');
  assert.ok((await tryGuardedOperations(h.runtime)).every(outcome=>!outcome.ok));
  assertNoAdapterEffects(h.calls);
  assert.equal(h.storeMeta(),'');
});

test('held inspection preserves unexpired in-flight reservations rather than performing normal restart recovery',async t=>{
  const run=record('in-flight',4,'running',{activeOperation:{kind:'tool',reservedMs:50}});
  const action={key:'in-flight-action',runId:run.id,state:'executing',effect:'write',tool:'records.append'};
  const h=await heldRuntime(t,validHold(),store=>{store.saveRun(run);store.saveAction(action);});
  assert.equal(h.runtime.status().counts.running,1);
  await h.runtime.stop();
  const store=openStore(h.stateRoot,{identity:mailboxIdentity(h.config),clock:()=>RESTORED_AT});
  try {
    assert.deepEqual(store.getRun(run.id),run);
    assert.deepEqual(store.getAction(action.key),action);
  } finally {store.close();}
  assertNoAdapterEffects(h.calls);
});

test('held inspection still expires private content without deleting replay identities or action fences',async t=>{
  const run=record('expired-held',4,'awaiting_approval',{createdAt:RESTORED_AT-24*3_600_000,
    mail:{body:'EXPIRED_PRIVATE_CONTENT'},approval:{id:'expired-approval',args:{value:'EXPIRED_PRIVATE_CONTENT'}}});
  const action={key:'expired-fence',runId:run.id,state:'uncertain',effect:'write',tool:'records.append'};
  const h=await heldRuntime(t,validHold(),store=>{store.saveRun(run);store.saveAction(action);});
  await h.runtime.stop();
  const store=openStore(h.stateRoot,{identity:mailboxIdentity(h.config),clock:()=>RESTORED_AT});
  try {
    const retained=store.getRun(run.id);
    assert.equal(retained.status,'failed');
    assert.equal(retained.contentExpired,true);
    assert.equal(retained.messageKey,run.messageKey);
    assert.doesNotMatch(JSON.stringify(retained),/EXPIRED_PRIVATE_CONTENT|expired-approval/);
    assert.deepEqual(store.getAction(action.key),action);
    assert.equal(store.getMeta('restore_hold'),validHold());
  } finally {store.close();}
  assertNoAdapterEffects(h.calls);
});

test('restore hold rejects unrecognized fields and never exposes their values', async t => {
  const secretSentinel = 'SYNTHETIC_PRIVATE_HOLD_FIELD';
  const h = await heldRuntime(t, JSON.stringify({
    snapshotId: SNAPSHOT_ID, snapshotCreatedAt: SNAPSHOT_CREATED_AT, restoredAt: RESTORED_AT, privateField: secretSentinel
  }));
  const status = h.runtime.status();
  assert.equal(status.recovery.required, true);
  assert.equal(status.recovery.reason, 'invalid-record');
  assert.equal(JSON.stringify(status).includes(secretSentinel), false);
  assert.equal(JSON.stringify(h.runtime.health()).includes(secretSentinel), false);
  assert.equal((await tryGuardedOperations(h.runtime)).every(outcome => !outcome.ok && /restore|recovery/i.test(outcome.message)), true);
  assertNoAdapterEffects(h.calls);
});

test('schema three upgrade preserves durable records and nonversion metadata', async t => {
  const root = await mkdtemp(join(tmpdir(), 'ma-v3-upgrade-'));
  t.after(async () => { await rm(root, { recursive: true, force: true }); });
  const cfg = config();
  const stateRoot = join(root, cfg.state_root);
  let store = openStore(stateRoot, { identity: mailboxIdentity(cfg), clock: () => RESTORED_AT });
  store.setMeta('cursor', JSON.stringify({ initialComplete: true, delta: 'preserved' }));
  store.setMeta('restore_hold', validHold());
  store.saveRun(record('queued-before-upgrade', 1, 'queued'));
  store.saveRun(record('uncertain-before-upgrade', 2, 'uncertain', { uncertainty: { kind: 'tool', key: 'fence-v3' } }));
  store.saveAction({ key: 'fence-v3', runId: 'uncertain-before-upgrade', state: 'uncertain', effect: 'write', tool: 'records.append' });
  store.close();

  const databasePath = join(stateRoot, 'agent.sqlite');
  let db = new DatabaseSync(databasePath);
  db.exec("UPDATE meta SET value='3' WHERE key='schema_version';");
  const before = {
    meta: db.prepare("SELECT key,value FROM meta WHERE key<>'schema_version' ORDER BY key").all(),
    runs: db.prepare('SELECT id,message_key,conversation_key,status,updated_at,data FROM runs ORDER BY id').all(),
    actions: db.prepare('SELECT key,run_id,state,data FROM actions ORDER BY key').all()
  };
  db.close();

  store = openStore(stateRoot, { identity: mailboxIdentity(cfg), clock: () => RESTORED_AT });
  assert.equal(store.getMeta('schema_version'), '5');
  store.close();
  db = new DatabaseSync(databasePath);
  const after = {
    meta: db.prepare("SELECT key,value FROM meta WHERE key<>'schema_version' ORDER BY key").all(),
    runs: db.prepare('SELECT id,message_key,conversation_key,status,updated_at,data FROM runs ORDER BY id').all(),
    actions: db.prepare('SELECT key,run_id,state,data FROM actions ORDER BY key').all()
  };
  db.close();
  assert.deepEqual(after, before);

  const calls = { poll: 0 };
  const runtime = await createRuntime({
    config: cfg, root, instructions: 'Synthetic restore hold test.', hash: 'synthetic', clock: () => RESTORED_AT,
    model: { step: async () => ({ text: 'synthetic', toolCalls: [] }) },
    mail: { poll: async () => { calls.poll++; return { messages: [], cursor: '{}' }; } },
    listenControl: async () => ({ close: async () => {} })
  });
  assert.equal(runtime.status().recovery.required, true);
  assert.equal(runtime.status().recovery.reason, 'restore-reconciliation');
  await assert.rejects(runtime.start({ once: true }), /restore|recovery/i);
  assert.equal(calls.poll, 0);
  await runtime.stop();
});
