import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { openStore } from '../src/store.mjs';
import { loadConfig } from '../src/config.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';
import { digest } from '../src/policy.mjs';
import { previewRecovery, applyRecovery } from '../src/recovery-apply.mjs';
import { previewRecoveryRelease, applyRecoveryRelease } from '../src/recovery-release.mjs';
import { createGraph } from '../src/graph.mjs';

const now=1_800_000_000_000, clock=()=>now;
const snapshotId='00000000-0000-4000-8000-000000000001';
const hold=JSON.stringify({snapshotId,snapshotCreatedAt:now-1000,restoredAt:now-500});
const cursor=JSON.stringify({url:'https://graph.microsoft.com/v1.0/users/assistant%40example.org/mailFolders/inbox/messages/delta?$deltatoken=SYNTHETIC_PRIVATE',initialComplete:true});
const actor='operator@example.org',reason='Synthetic whole-window reconciliation';

async function fixture(t,{active=false}={}) {
  const stateRoot=await mkdtemp(join(tmpdir(),'ma-release-'));
  t.after(()=>rm(stateRoot,{recursive:true,force:true}));
  const loaded=await loadConfig(new URL('../examples/text-inbox/agent.yaml',import.meta.url).pathname,{env:{}});
  const config={...loaded.config,state_root:stateRoot}, identity=mailboxIdentity(config), configHash='b'.repeat(64);
  const binding=digest([identity,hold,cursor]);
  const store=openStore(stateRoot,{identity,clock});
  store.setMeta('restore_hold',hold);store.setMeta('cursor',cursor);
  if(active) store.saveRun({id:'active-run',messageKey:digest([config.id,'synthetic-message']),conversationKey:digest('synthetic-conversation'),
    sequence:1,status:'queued',createdAt:now-800,budget:{modelCalls:1,toolCalls:0,activeMs:10},
    mail:{id:'synthetic-message',conversationId:'synthetic-conversation',sender:'alice@example.org',replyTo:'alice@example.org',
      to:['assistant@example.org'],cc:[],subject:'Synthetic',body:'SYNTHETIC_PRIVATE_BODY',receivedAt:new Date(now-800).toISOString(),
      attachments:false,authenticated:true,autoGenerated:false},
    grants:{},pending:[],configHash,instructionSnapshot:loaded.instructions});
  store.close();
  const plan={format:1,mode:'continuity',mailboxIdentity:identity,snapshotId,binding,configHash,
    coverage:{from:now-1000,through:now,oldOwnerStoppedAt:now-600,evidenceHash:'c'.repeat(64),allSources:true},acceptHistoryGap:false};
  const request={stateRoot,identity,configHash,config,plan,actor,reason,clock};
  const inspect=callback=>{const store=openStore(stateRoot,{identity,clock});try{return callback(store);}finally{store.close();}};
  const reconcile=async()=>{
    const fingerprint=inspect(store=>store.runFingerprint('active-run'));
    const batch={format:1,mailboxIdentity:identity,snapshotId,binding,configHash,operations:[{kind:'run',id:'active-run',fingerprint,outcome:'resume',
      evidence:{source:'adapter',recordHash:'d'.repeat(64),observedAt:now}}]};
    const options={stateRoot,identity,agentId:config.id,configHash,limits:config.limits,contentHours:config.retention.content_hours,plan:batch,clock};
    const preview=await previewRecovery(options);
    return applyRecovery({...options,expectedPlanDigest:preview.planDigest,actor,reason});
  };
  return {request,inspect,reconcile};
}

test('continuity release requires per-run reconciliation, preserves checkpoint and supports exact safe acknowledgment',async t=>{
  const f=await fixture(t,{active:true});
  const noNetwork={graphFactory(){throw new Error('Unexpected provider construction');}};
  await assert.rejects(previewRecoveryRelease(f.request,noNetwork));
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),hold);
  await f.reconcile();
  const preview=await previewRecoveryRelease(f.request,noNetwork);
  assert.equal(preview.mode,'continuity');assert.equal(preview.released,false);assert.equal(preview.executableRuns,1);
  assert.doesNotMatch(JSON.stringify(preview),/SYNTHETIC_PRIVATE|deltatoken|alice@example/);
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),hold);
  const request={...f.request,expectedReviewDigest:preview.reviewDigest};
  const result=await applyRecoveryRelease(request);
  assert.equal(result.released,true);assert.equal(result.idempotent,false);
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),undefined);
  assert.equal(f.inspect(store=>store.getMeta('cursor')),cursor);
  const repeat=await applyRecoveryRelease(request);assert.equal(repeat.idempotent,true);
  await assert.rejects(applyRecoveryRelease({...request,reason:'Changed attribution'}));
  f.inspect(store=>store.setMeta('cursor',cursor.replace('PRIVATE','ADVANCED')));
  await assert.rejects(applyRecoveryRelease(request));
});

test('stale review, configuration, changed executable record and a newer hold cannot release execution',async t=>{
  const f=await fixture(t,{active:true});await f.reconcile();
  const preview=await previewRecoveryRelease(f.request);
  await assert.rejects(applyRecoveryRelease({...f.request,expectedReviewDigest:'e'.repeat(64)}));
  await assert.rejects(applyRecoveryRelease({...f.request,configHash:'e'.repeat(64),expectedReviewDigest:preview.reviewDigest}));
  f.inspect(store=>{const run=store.getRun('active-run');run.budget.activeMs++;store.saveRun(run);});
  await assert.rejects(applyRecoveryRelease({...f.request,expectedReviewDigest:preview.reviewDigest}));
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),hold);
  f.inspect(store=>store.setMeta('restore_hold',JSON.stringify({snapshotId,snapshotCreatedAt:now-1000,restoredAt:now-100})));
  await assert.rejects(applyRecoveryRelease({...f.request,expectedReviewDigest:preview.reviewDigest}));
});

test('history-gap preview stages read-only baseline; application performs no network and preserves effect fences',async t=>{
  const f=await fixture(t);
  const request={...f.request,plan:{...f.request.plan,mode:'history-gap',acceptHistoryGap:true}};
  const fresh=cursor.replace('PRIVATE','FRESH');let polls=0;
  const graphFactory=()=>({poll:async({cursor:previous})=>{polls++;assert.equal(previous,undefined);return {messages:[],cursor:fresh};}});
  f.inspect(store=>store.saveAction({key:'uncertain-write',runId:'terminal',state:'uncertain',effect:'write',tool:'records.append'}));
  const preview=await previewRecoveryRelease(request,{graphFactory});
  assert.equal(polls,1);assert.equal(preview.mode,'history-gap');assert.equal(preview.baseline.pages,1);
  assert.equal(f.inspect(store=>store.getMeta('cursor')),cursor);
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),hold);
  const result=await applyRecoveryRelease({...request,expectedReviewDigest:preview.reviewDigest},{graphFactory(){throw new Error('No reads during apply');}});
  assert.equal(result.released,true);assert.equal(polls,1);
  assert.equal(f.inspect(store=>store.getMeta('cursor')),fresh);
  assert.equal(f.inspect(store=>store.getAction('uncertain-write').state),'uncertain');
  const db=new DatabaseSync(join(request.stateRoot,'agent.sqlite'),{readOnly:true});
  try {
    const details=JSON.parse(db.prepare("SELECT details FROM audit WHERE event='recovery-release'").get().details);
    assert.deepEqual(details.skippedHistory,{from:now-1000,through:now});
    assert.equal(details.baseline.observedAt,now);
  } finally {db.close();}
});

test('baseline failure, provider backoff, cancellation and invalid completed checkpoint preserve hold and cursor',async t=>{
  const f=await fixture(t);
  const gap={...f.request,plan:{...f.request.plan,mode:'history-gap',acceptHistoryGap:true}};
  await assert.rejects(previewRecoveryRelease(gap,{graphFactory:()=>({poll:async()=>{throw new Error('PRIVATE_PROVIDER_ERROR');}})}),
    error=>error.code==='RECOVERY_RELEASE_INVALID'&&!error.message.includes('PRIVATE'));
  const controller=new AbortController();controller.abort();
  await assert.rejects(previewRecoveryRelease({...gap,signal:controller.signal}));
  await assert.rejects(previewRecoveryRelease(gap,{graphFactory:()=>({poll:async()=>({messages:[],
    cursor:cursor.replace('graph.microsoft.com','untrusted.example.test')})})}));
  f.inspect(store=>store.setMeta('sync.retry',String(now+1000)));
  await assert.rejects(previewRecoveryRelease(gap,{graphFactory(){throw new Error('Backoff must precede construction');}}));
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),hold);
  assert.equal(f.inspect(store=>store.getMeta('cursor')),cursor);
});

test('continuity requires a completed original checkpoint; unfinished intake cannot silently become recovered history',async t=>{
  const f=await fixture(t);
  const incomplete=cursor.replace('true','false');
  f.inspect(store=>store.setMeta('cursor',incomplete));
  const binding=digest([f.request.identity,hold,incomplete]);
  await assert.rejects(previewRecoveryRelease({...f.request,plan:{...f.request.plan,binding}}));
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),hold);
  assert.equal(f.inspect(store=>store.getMeta('cursor')),incomplete);
});

test('a baseline provider deadline persists across failed preview and prevents a premature retry',async t=>{
  const f=await fixture(t);
  const gap={...f.request,plan:{...f.request.plan,mode:'history-gap',acceptHistoryGap:true}};
  let fetches=0;
  const graphFactory=value=>createGraph(value.config.mailbox,{env:{INBOX_GRAPH_CLIENT_SECRET:'synthetic'},clock,
    onRetryNotBefore:value.onRetryNotBefore,fetchImpl:async url=>{
      fetches++;
      if(String(url).includes('/oauth2/')) return new Response(JSON.stringify({access_token:'synthetic',expires_in:3600}));
      return new Response('SYNTHETIC_PRIVATE_RESPONSE',{status:429,headers:{'retry-after':'3600'}});
    }});
  await assert.rejects(previewRecoveryRelease(gap,{graphFactory}));
  assert.equal(f.inspect(store=>store.getMeta('sync.retry')),String(now+3_600_000));
  await assert.rejects(previewRecoveryRelease(gap,{graphFactory}));
  assert.equal(fetches,2);
  assert.equal(f.inspect(store=>store.getMeta('restore_hold')),hold);
  assert.equal(f.inspect(store=>store.getMeta('cursor')),cursor);
});
