import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openStore } from '../src/store.mjs';
import { digest, policyDigest } from '../src/policy.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';
import { previewRecovery, applyRecovery } from '../src/recovery-apply.mjs';
import { verifyRecoveryLedger } from '../src/recovery-ledger.mjs';

const config = { id: 'ledger-gate', state_root: 'state', mailbox: { tenant_id: 'synthetic', client_id: 'synthetic', address: 'agent@example.test' },
  model: { capabilities: { tools: true } },
  policy: { senders: ['sender@example.test'], recipients: ['sender@example.test'], approvers: ['admin@example.test'],
    tools: { 'records.append': { effect: 'write', authorization: 'approval' } } },
  limits: { model_calls: 6, tool_calls: 10, run_seconds: 120 }, retention: { content_hours: 24, audit_days: 30 } };
const identity = mailboxIdentity(config), configHash = digest(config);
const snapshotId = '11111111-1111-4111-8111-111111111111';
const rawHold = JSON.stringify({ snapshotId, snapshotCreatedAt: 10, restoredAt: 20 }), rawCursor = 'synthetic-private-cursor';
const binding = digest([identity, rawHold, rawCursor]);
const context = { config, identity, configHash, binding, snapshotId, snapshotCreatedAt: 10, now: 30 };
const mail = id => ({ id, conversationId: id, sender: 'sender@example.test', replyTo: 'sender@example.test', to: ['agent@example.test'], cc: [],
  subject: 'Synthetic', body: 'SYNTHETIC_PRIVATE_BODY', receivedAt: '2026-01-01T00:00:00Z', authenticated: true, autoGenerated: false, attachments: false });

function waitingApproval(run) {
  const call = { name: 'records.append', args: { value: 'synthetic' } };
  run.status = 'awaiting_approval';
  run.pending = [call];
  run.approval = { id: digest([run.id, call.name, call.args]), tool: call.name, args: structuredClone(call.args),
    policyHash: policyDigest(config), expiresAt: 1000 };
}

async function fixture(t, count = 1) {
  const root = await mkdtemp(join(tmpdir(), 'ma-ledger-gate-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const store = openStore(root, { identity, clock: () => 30 });
  store.setMeta('restore_hold', rawHold); store.setMeta('cursor', rawCursor);
  for (let index = 0; index < count; index++) store.saveRun({ id: `run-${index}`, messageKey: digest(index), conversationKey: digest(index), status: 'queued',
    createdAt: 15, sequence: index + 1, mail: mail(`provider-${index}`), budget: { modelCalls: 1, toolCalls: 1, activeMs: 5 }, grants: { synthetic: { expiresAt: 1000 } } });
  store.close();
  const inspect = callback => { const store = openStore(root, { identity, clock: () => 30 }); try { return callback(store); } finally { store.close(); } };
  const reconcile = async () => {
    for (let offset = 0; offset < count; offset += 100) {
      const operations = inspect(store => Array.from({ length: Math.min(100, count - offset) }, (_, index) => ({ kind: 'run', id: `run-${offset + index}`,
        fingerprint: store.runFingerprint(`run-${offset + index}`), outcome: 'resume', evidence: { source: 'adapter', recordHash: 'a'.repeat(64), observedAt: 30 } })));
      const plan = { format: 1, mailboxIdentity: identity, snapshotId, binding, configHash, operations };
      const options = { stateRoot: root, identity, agentId: config.id, configHash, contentHours: 24, limits: config.limits, clock: () => 30, plan };
      const preview = await previewRecovery(options);
      await applyRecovery({ ...options, actor: 'operator@example.test', reason: 'Synthetic reconciliation', expectedPlanDigest: preview.planDigest });
    }
  };
  return { inspect, reconcile };
}

test('the ledger gate requires committed exact resume proofs and leaves approvals/grants unchanged', async t => {
  const f = await fixture(t);
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, context)));
  f.inspect(store => { const run = store.getRun('run-0'); waitingApproval(run); store.saveRun(run); });
  await f.reconcile();
  const before = f.inspect(store => store.getRun('run-0'));
  const first = f.inspect(store => verifyRecoveryLedger(store, context));
  assert.equal(first.count, 1);
  assert.match(first.ledgerDigest, /^[a-f0-9]{64}$/);
  assert.deepEqual(f.inspect(store => verifyRecoveryLedger(store, context)), first);
  assert.deepEqual(f.inspect(store => store.getRun('run-0')), before);
  assert.equal(JSON.stringify(first).includes('SYNTHETIC_PRIVATE'), false);
  f.inspect(store => { const run = store.getRun('run-0'); run.mail.body += ' changed'; store.saveRun(run); });
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, context)));
});

test('old, missing and mismatched run receipts cannot release executable work', async t => {
  for (const change of [value => { delete value.runs; }, value => { value.runs = []; }, value => { value.configHash = 'f'.repeat(64); },
    value => { value.runs[0].appliedFingerprint = 'f'.repeat(64); }, value => { value.runs[0].outcome = 'skip'; },
    value => { value.runs[0].evidenceHash = 'f'.repeat(64); }, value => { value.runs[0].id = 'other-run'; }]) {
    const f = await fixture(t); await f.reconcile();
    f.inspect(store => { const run = store.getRun('run-0'), key = `recovery_batch:${run.recovery.planDigest}`;
      const receipt = JSON.parse(store.getMeta(key)); change(receipt); store.setMeta(key, JSON.stringify(receipt)); });
    assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, context)));
  }
});

test('current recipient authority, envelope validity, unresolved actions and real exhaustion block release', async t => {
  const f = await fixture(t); await f.reconcile();
  for (const policy of [{ ...config.policy, senders: [] }, { ...config.policy, recipients: [] }]) {
    assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, { ...context, config: { ...config, policy } })));
  }
  f.inspect(store => store.saveAction({ key: 'unknown', runId: 'run-0', state: 'uncertain', effect: 'write' }));
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, context)));
  for (const mutation of [value => { value.budget = null; }, value => { value.budget.activeMs = 120000; }, value => { value.budget.toolCalls = 11; },
    value => { value.mail.authenticated = false; }, value => { value.mail.replyTo = 'other@example.test'; }, value => { value.mail.to = []; },
    value => { value.mail.subject = null; }, value => { value.contentExpired = true; }, value => { value.activeOperation = { reservedMs: 1 }; },
    value => { value.status = 'running'; }, value => { value.status = 'sending'; }]) {
    const candidate = await fixture(t); await candidate.reconcile();
    candidate.inspect(store => { const value = store.getRun('run-0'); mutation(value); store.saveRun(value);
      const key = `recovery_batch:${value.recovery.planDigest}`, receipt = JSON.parse(store.getMeta(key));
      receipt.runs[0].appliedFingerprint = store.runFingerprint(value.id); store.setMeta(key, JSON.stringify(receipt)); });
    assert.throws(() => candidate.inspect(store => verifyRecoveryLedger(store, context)));
  }
});

test('recorded outbox delivery may retain exact model/tool caps without renewing any budget', async t => {
  const f = await fixture(t);
  f.inspect(store => { const value = store.getRun('run-0'); value.status = 'ready_to_send'; value.reply = 'Synthetic saved reply';
    value.budget = { modelCalls: 6, toolCalls: 10, activeMs: 119999 }; store.saveRun(value); });
  await f.reconcile();
  assert.equal(f.inspect(store => verifyRecoveryLedger(store, context)).count, 1);
});

test('indexed metadata pages are bounded, ordered and cancellable without scanning terminal history', async t => {
  const f = await fixture(t, 101); await f.reconcile();
  let pages = 0, reads = 0, checks = 0;
  const result = f.inspect(store => {
    store.listRuns = () => { throw new Error('Forbidden history scan'); };
    store.actions = () => { throw new Error('Forbidden action scan'); };
    store.activeBatch = () => { throw new Error('Forbidden full-row page'); };
    store.getMeta = () => { throw new Error('Forbidden unbounded metadata read'); };
    const page = store.activeRecoveryPage, getRun = store.getRun;
    store.activeRecoveryPage = options => { pages++; assert.equal(options.limit, 100); return page(options); };
    store.getRun = id => { reads++; return getRun(id); };
    return verifyRecoveryLedger(store, { ...context, checkCancelled: () => { checks++; } });
  });
  assert.equal(result.count, 101); assert.equal(pages, 2); assert.equal(reads, 101); assert.ok(checks >= 103);
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, { ...context, maxRuns: 100 })));
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, { ...context, checkCancelled: () => { throw new Error('PRIVATE_CANCEL'); } })),
    error => error.code === 'RECOVERY_LEDGER_INVALID' && !error.message.includes('PRIVATE'));
});

test('empty active ledger has a deterministic digest and terminal history is never requested', async t => {
  const f = await fixture(t, 0);
  const first = f.inspect(store => verifyRecoveryLedger(store, context));
  assert.equal(first.count, 0);
  assert.deepEqual(f.inspect(store => verifyRecoveryLedger(store, context)), first);
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, { ...context, maxRuns: 10001 })));
});

test('bounded metadata rejects oversized receipts/checkpoints and retention expiry even when fingerprints match', async t => {
  const f = await fixture(t); await f.reconcile();
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, { ...context, now: 86_400_015 })));
  const key = f.inspect(store => `recovery_batch:${store.getRun('run-0').recovery.planDigest}`);
  const raw = f.inspect(store => store.getMeta(key));
  f.inspect(store => store.setMeta(key, 'x'.repeat(262_145)));
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, context)));
  f.inspect(store => { store.setMeta(key, raw); store.setMeta('cursor', 'x'.repeat(65_537)); });
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, context)));
});

test('waiting approvals must be current and identify the exact original pending tool call', async t => {
  const mutations = [
    run => { delete run.approval; }, run => { run.approval = null; }, run => { run.approval.expiresAt = 30; },
    run => { run.approval.expiresAt = '1000'; }, run => { run.approval.policyHash = 'f'.repeat(64); },
    run => { run.approval.tool = 'unknown.tool'; }, run => { run.approval.id = 'f'.repeat(64); },
    run => { run.approval.args = { value: 'different' }; }, run => { run.pending = []; },
    run => { run.pending[0].name = 'unknown.tool'; }, run => { run.pending[0].args = { value: 'different' }; }
  ];
  for (const mutation of mutations) {
    const f = await fixture(t);
    f.inspect(store => { const run = store.getRun('run-0'); waitingApproval(run); mutation(run); store.saveRun(run); });
    await f.reconcile();
    const before = f.inspect(store => store.runFingerprint('run-0'));
    assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, context)));
    assert.equal(f.inspect(store => store.runFingerprint('run-0')), before);
  }
  const f = await fixture(t);
  f.inspect(store => { const run = store.getRun('run-0'); waitingApproval(run); store.saveRun(run); });
  await f.reconcile();
  const disabled = { ...config, model: { capabilities: { tools: false } } };
  assert.throws(() => f.inspect(store => verifyRecoveryLedger(store, { ...context, config: disabled })));
});

test('queued stale grants remain unchanged and cannot become implicit approval through release inspection', async t => {
  const f = await fixture(t);
  const grants = { synthetic: { expiresAt: 1, policyHash: 'f'.repeat(64), actor: 'former@example.test' } };
  f.inspect(store => { const run = store.getRun('run-0'); run.grants = grants; store.saveRun(run); });
  await f.reconcile();
  assert.equal(f.inspect(store => verifyRecoveryLedger(store, context)).count, 1);
  assert.deepEqual(f.inspect(store => store.getRun('run-0').grants), grants);
});
