import assert from 'node:assert/strict';
import test from 'node:test';
import { chmod, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { runCli } from '../src/cli.mjs';
import { loadConfig } from '../src/config.mjs';
import { openStore } from '../src/store.mjs';
import { createRuntime } from '../src/runtime.mjs';
import { backupState } from '../src/backup.mjs';
import { restoreState } from '../src/restore.mjs';
import { inspectRecovery } from '../src/recovery-inspect.mjs';
import { previewRecovery, applyRecovery } from '../src/recovery-apply.mjs';
import { previewRecoveryRelease, applyRecoveryRelease } from '../src/recovery-release.mjs';
import { digest } from '../src/policy.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';
import { createGraph } from '../src/graph.mjs';

const actor = 'operator@tenant.test';
const reason = 'Reconcile the stopped synthetic mailbox window';
const secret = 'synthetic-private-graph-secret';

function sink() { let text = ''; return { write(value) { text += value; }, value() { return text; } }; }

function services(clock, additions = {}) {
  return {
    env: { INBOX_GRAPH_CLIENT_SECRET: secret }, stdout: sink(), stderr: sink(),
    backupState: value => backupState({ ...value, clock }),
    restoreState: value => restoreState({ ...value, clock }),
    inspectRecovery: value => inspectRecovery({ ...value, clock }),
    previewRecovery: value => previewRecovery({ ...value, clock }),
    applyRecovery: value => applyRecovery({ ...value, clock }),
    previewRecoveryRelease: value => previewRecoveryRelease({ ...value, clock }),
    applyRecoveryRelease: value => applyRecoveryRelease({ ...value, clock }),
    ...additions,
  };
}

async function invoke(args, dependencies) {
  const stdout = sink(), stderr = sink();
  const code = await runCli(args, { ...dependencies, stdout, stderr });
  return { code, stdout: stdout.value(), stderr: stderr.value() };
}

function parse(result) {
  assert.equal(result.code, 0, result.stderr);
  return JSON.parse(result.stdout);
}

function envelope(id, body, sender = 'alice@tenant.test') {
  return { id, conversationId: `conversation-${id}`, sender, replyTo: sender, to: ['agent@tenant.test'], cc: [],
    subject: `Synthetic ${id}`, body, receivedAt: '2026-09-30T12:00:00.000Z', attachments: false,
    authenticated: true, autoGenerated: false };
}

function createRun(config, instructions, hash, message, sequence, modelCalls = 0) {
  return { id: `run-${message.id}`, messageKey: digest([config.id, message.id]), conversationKey: digest(message.conversationId),
    sequence, status: 'queued', createdAt: 1_800_000_000_000, budget: { modelCalls, toolCalls: 0, activeMs: 250 },
    mail: message, instructionSnapshot: instructions, configHash: hash, pending: [], grants: {}, messages: null };
}

async function initialize(root) {
  const bundle = join(root, 'bundle');
  const setup = await invoke(['init', '--directory', bundle, '--recipe', 'text-inbox', '--id', 'release-journey', '--state-root', './source-state',
    '--mailbox', 'agent@tenant.test', '--tenant', 'tenant-id', '--client', 'client-id', '--model-url', 'https://model.tenant.test/v1',
    '--model', 'synthetic-model', '--senders', 'alice@tenant.test', '--recipients', 'alice@tenant.test',
    '--auth-profile', 'dmarc', '--authserv-ids', 'mx.tenant.test'], services(() => 1_800_000_000_000));
  assert.equal(setup.code, 0, setup.stderr);
  return { bundle, filename: join(bundle, 'agent.yaml') };
}

function database(stateRoot, callback) {
  const db = new DatabaseSync(join(stateRoot, 'agent.sqlite'));
  try { return callback(db); } finally { db.close(); }
}

test('CLI snapshot reconciliation fences post-snapshot effects and releases the original cursor once', async t => {
  const root = await mkdtemp(join(tmpdir(), 'ma-recovery-release-journey-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  let now = 1_800_000_000_000;
  const clock = () => now;
  const cli = services(clock);
  const { filename } = await initialize(root);
  const loaded = await loadConfig(filename, { env: cli.env });
  const config = loaded.config;
  const stateRoot = config.state_root;
  const initialCursor = JSON.stringify({
    url: 'https://graph.microsoft.com/v1.0/users/agent%40tenant.test/mailFolders/inbox/messages/delta?$deltatoken=synthetic-original',
    initialComplete: true,
  });
  const x = envelope('x-message', 'Snapshot queued; source completes this after backup.');
  const r = envelope('r-message', 'Snapshot queued; resume only after its receipt is recorded.');
  const seed = openStore(stateRoot, { identity: mailboxIdentity(config), clock });
  seed.setMeta('cursor', initialCursor);
  seed.saveRun(createRun(config, loaded.instructions, loaded.hash, x, 1));
  seed.saveRun(createRun(config, loaded.instructions, loaded.hash, r, 2, 1));
  seed.setMeta('queue_sequence', '2');
  seed.close();

  const snapshot = join(root, 'snapshot');
  parse(await invoke(['backup', '--config', filename, '--directory', snapshot], cli));

  const sourceEffects = { replies: [], model: 0, mcpList: 0, mcpCalls: 0 };
  const sourceRuntime = await createRuntime({ ...loaded, mode: 'operator', clock,
    mail: { async reply(message) { sourceEffects.replies.push(message.id); return { status: 'accepted' }; } },
    model: { async step() { sourceEffects.model++; return { text: 'Synthetic reply.', toolCalls: [] }; } },
    mcp: { async listTools() { sourceEffects.mcpList++; return new Map(); }, async call() { sourceEffects.mcpCalls++; }, async close() {} },
  });
  assert.equal((await sourceRuntime.processMessage(x)).status, 'completed');
  now += 1_000;
  const y = envelope('y-message', 'This message arrived after the snapshot.');
  assert.equal((await sourceRuntime.processMessage(y)).status, 'completed');
  assert.deepEqual(sourceEffects.replies, ['x-message', 'y-message']);
  assert.equal(sourceEffects.model, 2);
  now += 1_000;
  const stoppedAt = now;
  await sourceRuntime.stop();

  const beforeConfig = await readFile(filename, 'utf8');
  await writeFile(filename, beforeConfig.replace('state_root: ./source-state', 'state_root: ./restored-state'));
  await chmod(filename, 0o600);
  now += 1_000;
  const restored = parse(await invoke(['restore', '--config', filename, '--snapshot', snapshot, '--actor', actor, '--reason', reason], cli));
  assert.equal(restored.recoveryRequired, true);
  assert.equal(restored.stateSchema, 5);

  const inspected = parse(await invoke(['recovery-inspect', '--config', filename, '--kind', 'runs', '--limit', '100'], cli));
  const xRun = inspected.items.find(item => item.id === 'run-x-message');
  const rRun = inspected.items.find(item => item.id === 'run-r-message');
  assert.ok(xRun?.fingerprint && rRun?.fingerprint);
  const evidence = (source, value) => ({ source, recordHash: digest(value), observedAt: now });
  const reconcilePlan = { format: 1, mailboxIdentity: inspected.mailboxIdentity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash: inspected.configHash,
    operations: [
      { kind: 'run', id: xRun.id, fingerprint: xRun.fingerprint, outcome: 'fenced', evidence: evidence('adapter', 'x completed after snapshot') },
      { kind: 'message', messageId: y.id, conversationId: y.conversationId, outcome: 'sent', evidence: evidence('graph', 'y exists in provider sent history') },
      { kind: 'run', id: rRun.id, fingerprint: rRun.fingerprint, outcome: 'resume', evidence: evidence('adapter', 'r has no post-snapshot effect') },
    ] };
  const planPath = join(root, 'recovery-plan.json');
  await writeFile(planPath, `${JSON.stringify(reconcilePlan)}\n`, { mode: 0o600 });
  await chmod(planPath, 0o600);
  const recoveryPreview = parse(await invoke(['recovery-preview', '--config', filename, '--plan', planPath], cli));
  const recoveryDigest = recoveryPreview.planDigest;
  const recoveryArgs = ['recovery-apply', '--config', filename, '--plan', planPath, '--digest', recoveryDigest, '--actor', actor, '--reason', reason];
  assert.equal(parse(await invoke(recoveryArgs, cli)).applied, true);
  assert.equal(parse(await invoke(recoveryArgs, cli)).idempotent, true);
  database(restored.stateRoot, db => {
    assert.equal(db.prepare('SELECT status FROM runs WHERE id=?').get(xRun.id).status, 'uncertain');
    assert.equal(db.prepare('SELECT status FROM runs WHERE id=?').get(rRun.id).status, 'queued');
    assert.equal(JSON.parse(db.prepare('SELECT data FROM runs WHERE id=?').get(rRun.id).data).budget.modelCalls, 1);
    assert.equal(db.prepare("SELECT count(*) AS n FROM audit WHERE event='recovery-decision'").get().n, 3);
  });

  now += 1_000;
  const releasePlan = { format: 1, mode: 'continuity', mailboxIdentity: inspected.mailboxIdentity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash: inspected.configHash,
    coverage: { from: inspected.recovery.snapshotCreatedAt, through: now, oldOwnerStoppedAt: stoppedAt,
      evidenceHash: digest('all synthetic sources reconciled'), allSources: true }, acceptHistoryGap: false };
  const releasePath = join(root, 'release-plan.json');
  await writeFile(releasePath, `${JSON.stringify(releasePlan)}\n`, { mode: 0o600 });
  await chmod(releasePath, 0o600);
  const releaseArgs = ['--config', filename, '--plan', releasePath, '--actor', actor, '--reason', reason];
  const releasePreview = parse(await invoke(['recovery-release-preview', ...releaseArgs], cli));
  assert.equal(releasePreview.mode, 'continuity');
  assert.equal(releasePreview.released, false);
  assert.equal(releasePreview.executableRuns, 1);
  assert.doesNotMatch(JSON.stringify(releasePreview), /synthetic-original|tenant\.test|private/i);
  const releaseApplyArgs = ['recovery-release-apply', ...releaseArgs, '--digest', releasePreview.reviewDigest];
  assert.equal(parse(await invoke(releaseApplyArgs, cli)).released, true);
  assert.equal(parse(await invoke(releaseApplyArgs, cli)).idempotent, true);
  database(restored.stateRoot, db => {
    assert.equal(db.prepare("SELECT value FROM meta WHERE key='cursor'").get().value, initialCursor);
    assert.equal(db.prepare("SELECT value FROM meta WHERE key='restore_hold'").get(), undefined);
    assert.equal(db.prepare("SELECT count(*) AS n FROM audit WHERE event='recovery-release'").get().n, 1);
    assert.equal(db.prepare("SELECT count(*) AS n FROM meta WHERE key LIKE 'recovery_release_receipt:%'").get().n, 1);
  });

  const restoredConfig = await loadConfig(filename, { env: cli.env });
  const effects = { replies: [], model: 0, mcpList: 0, mcpCalls: 0 };
  const runtime = await createRuntime({ ...restoredConfig, mode: 'operator', clock,
    mail: { async reply(message) { effects.replies.push(message.id); return { status: 'accepted' }; } },
    model: { async step() { effects.model++; return { text: 'Synthetic reply.', toolCalls: [] }; } },
    mcp: { async listTools() { effects.mcpList++; return new Map(); }, async call() { effects.mcpCalls++; }, async close() {} },
  });
  try {
    assert.equal((await runtime.processMessage(x)).status, 'uncertain');
    assert.equal((await runtime.processMessage(y)).status, 'completed');
    assert.equal((await runtime.processMessage(r)).status, 'completed');
    const fresh = envelope('new-message', 'A new request after reconciliation.');
    assert.equal((await runtime.processMessage(fresh)).status, 'completed');
    assert.deepEqual(effects.replies, ['r-message', 'new-message']);
    assert.equal(effects.model, 2);
    assert.equal(effects.mcpCalls, 0);
    assert.ok(effects.mcpList >= 2);
  } finally { await runtime.stop(); }

  database(restored.stateRoot, db => {
    const row = id => JSON.parse(db.prepare('SELECT data FROM runs WHERE id=?').get(id).data);
    assert.equal(row('run-r-message').status, 'completed');
    assert.equal(row('run-r-message').budget.modelCalls, 2);
    assert.equal(row('run-r-message').budget.activeMs, 250);
    assert.equal(row('run-x-message').status, 'uncertain');
    assert.equal(row('run-x-message').budget.modelCalls, 0);
    assert.equal(db.prepare("SELECT status FROM runs WHERE message_key=?").get(digest([config.id, y.id])).status, 'completed');
    assert.equal(db.prepare("SELECT status FROM runs WHERE message_key=?").get(digest([config.id, 'new-message'])).status, 'completed');
  });
  assert.deepEqual(sourceEffects.replies, ['x-message', 'y-message']);
});

test('history-gap release stages a multipage baseline through the actual Graph adapter', async t => {
  const root = await mkdtemp(join(tmpdir(), 'ma-recovery-history-gap-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const now = 1_800_000_100_000, clock = () => now;
  const bundle = join(root, 'bundle');
  const init = await invoke(['init', '--directory', bundle, '--recipe', 'text-inbox', '--id', 'history-gap-agent', '--state-root', './state',
    '--mailbox', 'agent@tenant.test', '--tenant', 'tenant-id', '--client', 'client-id', '--model-url', 'https://model.tenant.test/v1',
    '--model', 'synthetic-model', '--senders', 'alice@tenant.test', '--recipients', 'alice@tenant.test',
    '--auth-profile', 'dmarc', '--authserv-ids', 'mx.tenant.test'], services(clock));
  assert.equal(init.code, 0, init.stderr);
  const filename = join(bundle, 'agent.yaml');
  const env = { INBOX_GRAPH_CLIENT_SECRET: secret };
  const loaded = await loadConfig(filename, { env });
  const identity = mailboxIdentity(loaded.config);
  const originalCursor = JSON.stringify({ url: 'https://graph.microsoft.com/v1.0/users/agent%40tenant.test/mailFolders/inbox/messages/delta?$deltatoken=original', initialComplete: true });
  const hold = JSON.stringify({ snapshotId: '00000000-0000-4000-8000-000000000123', snapshotCreatedAt: now - 2_000, restoredAt: now - 1_000 });
  const store = openStore(loaded.config.state_root, { identity, clock });
  store.setMeta('cursor', originalCursor);
  store.setMeta('restore_hold', hold);
  const queued = envelope('history-queued', 'Reconciled queued work must survive a history-gap release.');
  store.saveRun(createRun(loaded.config, loaded.instructions, loaded.hash, queued, 1, 1));
  store.setMeta('queue_sequence', '1');
  store.close();

  const inspected = parse(await invoke(['recovery-inspect', '--config', filename, '--kind', 'runs', '--limit', '100'], services(clock)));
  const queuedRow = inspected.items.find(item => item.id === 'run-history-queued');
  assert.ok(queuedRow?.fingerprint);
  const recoveryPlan = { format: 1, mailboxIdentity: identity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash: inspected.configHash,
    operations: [{ kind: 'run', id: queuedRow.id, fingerprint: queuedRow.fingerprint, outcome: 'resume',
      evidence: { source: 'adapter', recordHash: digest('queued work is effect-free'), observedAt: now } }] };
  const recoveryPath = join(root, 'history-gap-reconcile.json');
  await writeFile(recoveryPath, `${JSON.stringify(recoveryPlan)}\n`, { mode: 0o600 });
  await chmod(recoveryPath, 0o600);
  const recoveryPreview = parse(await invoke(['recovery-preview', '--config', filename, '--plan', recoveryPath], services(clock)));
  const recoveryApplyArgs = ['recovery-apply', '--config', filename, '--plan', recoveryPath, '--digest', recoveryPreview.planDigest,
    '--actor', actor, '--reason', 'Confirm the synthetic queued run had no effect'];
  assert.equal(parse(await invoke(recoveryApplyArgs, services(clock))).applied, true);

  const releasePlan = { format: 1, mode: 'history-gap', mailboxIdentity: identity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash: loaded.hash,
    coverage: { from: inspected.recovery.snapshotCreatedAt, through: now, oldOwnerStoppedAt: now - 500,
      evidenceHash: digest('complete synthetic source window'), allSources: true }, acceptHistoryGap: true };
  const planPath = join(root, 'history-gap-plan.json');
  await writeFile(planPath, `${JSON.stringify(releasePlan)}\n`, { mode: 0o600 });
  await chmod(planPath, 0o600);

  const deltaRoot = 'https://graph.microsoft.com/v1.0/users/agent%40tenant.test/mailFolders/inbox/messages/delta';
  const links = [`${deltaRoot}?$skiptoken=synthetic-page-two`, `${deltaRoot}?$skiptoken=synthetic-page-three`, `${deltaRoot}?$deltatoken=synthetic-final`];
  const pages = [
    { value: [], '@odata.nextLink': links[0] },
    { value: [], '@odata.nextLink': links[1] },
    { value: [], '@odata.deltaLink': links[2] },
  ];
  const requests = [];
  const fetchImpl = async (url, init) => {
    const target = String(url);
    requests.push({ target, method: init.method });
    if (target.includes('/oauth2/v2.0/token')) return new Response(JSON.stringify({ access_token: 'synthetic-token', expires_in: 3600 }));
    return new Response(JSON.stringify(pages.shift()));
  };
  const dependencies = services(clock, {
    env,
    previewRecoveryRelease: value => previewRecoveryRelease({ ...value, clock }, {
      graphFactory: settings => createGraph(settings.config.mailbox, { env: settings.env, clock, fetchImpl }),
    }),
  });
  const commandArgs = ['--config', filename, '--plan', planPath, '--actor', actor, '--reason', 'Accept the synthetic history gap'];
  const preview = parse(await invoke(['recovery-release-preview', ...commandArgs], dependencies));
  assert.equal(preview.mode, 'history-gap');
  assert.deepEqual(preview.baseline, { pages: 3, messages: 0, observedAt: now });
  assert.deepEqual(preview.skippedHistory, { from: inspected.recovery.snapshotCreatedAt, through: now });
  assert.equal(preview.released, false);
  assert.equal(preview.executableRuns, 1);
  assert.equal(requests.filter(request => request.method === 'GET').length, 3);
  assert.ok(requests[0].target.includes('/oauth2/v2.0/token'));
  assert.doesNotMatch(JSON.stringify(preview), /synthetic-final|tenant\.test|synthetic-token/i);
  const beforeApply = openStore(loaded.config.state_root, { identity, clock });
  try { assert.equal(beforeApply.getMeta('cursor'), originalCursor); }
  finally { beforeApply.close(); }

  const applyArgs = ['recovery-release-apply', ...commandArgs, '--digest', preview.reviewDigest];
  const applied = parse(await invoke(applyArgs, dependencies));
  assert.equal(applied.released, true);
  assert.equal(applied.idempotent, false);
  const retried = parse(await invoke(applyArgs, dependencies));
  assert.equal(retried.released, true);
  assert.equal(retried.idempotent, true);
  const finalStore = openStore(loaded.config.state_root, { identity, clock });
  try {
    assert.equal(finalStore.getMeta('cursor'), JSON.stringify({ url: links[2], initialComplete: true }));
    assert.equal(finalStore.getMeta('restore_hold'), undefined);
    assert.equal(finalStore.getRun('run-history-queued').status, 'queued');
    assert.equal(finalStore.getRun('run-history-queued').budget.modelCalls, 1);
    assert.equal(finalStore.summary().total, 1);
  } finally { finalStore.close(); }
  database(loaded.config.state_root, db => {
    const releaseAudit = db.prepare("SELECT details FROM audit WHERE event='recovery-release'").get();
    assert.deepEqual(JSON.parse(releaseAudit.details).skippedHistory, { from: inspected.recovery.snapshotCreatedAt, through: now });
  });
});
