import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openStore } from '../src/store.mjs';
import { DatabaseSync } from 'node:sqlite';
import { digest } from '../src/policy.mjs';
import { previewRecovery, applyRecovery } from '../src/recovery-apply.mjs';

const identity = 'a'.repeat(64), configHash = 'b'.repeat(64), agentId = 'synthetic-agent';
const snapshotId = '11111111-1111-4111-8111-111111111111';
const limits = { model_calls: 6, tool_calls: 10, run_seconds: 120 };
const evidence = (source = 'adapter') => ({ source, recordHash: 'c'.repeat(64), observedAt: 30 });
const actor = 'operator@example.test', reason = 'Synthetic provider reconciliation.';
const hold = JSON.stringify({ snapshotId, snapshotCreatedAt: 10, restoredAt: 20 });
const cursor = JSON.stringify({ initialComplete: true, url: 'SYNTHETIC_PRIVATE_CURSOR' });
const binding = digest([identity, hold, cursor]);
const mail = () => ({ id: 'SYNTHETIC_PRIVATE_PROVIDER_ID', conversationId: 'SYNTHETIC_PRIVATE_CONVERSATION', sender: 'sender@example.test',
  to: ['agent@example.test'], cc: [], subject: 'SYNTHETIC_PRIVATE_SUBJECT', body: 'SYNTHETIC_PRIVATE_BODY', authenticated: true, autoGenerated: false });
const run = (id = 'run-one', extra = {}) => ({ id, messageKey: digest([agentId, id]), conversationKey: digest(id), sequence: 1,
  status: 'queued', createdAt: 15, budget: { modelCalls: 2, toolCalls: 1, activeMs: 5 }, mail: mail(),
  grants: { 'synthetic-grant': { actor: 'admin@example.test', expiresAt: 900, policyHash: 'synthetic-policy' } }, ...extra });

async function fixture(t, records = [run()]) {
  const root = await mkdtemp(join(tmpdir(), 'ma-recovery-apply-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const store = openStore(root, { identity, clock: () => 30 });
  store.setMeta('restore_hold', hold);
  store.setMeta('cursor', cursor);
  store.setMeta('queue_sequence', '9');
  for (const value of records) store.saveRun(value);
  store.close();
  const options = { stateRoot: root, identity, agentId, configHash, limits, contentHours: 24, clock: () => 30 };
  return { options, inspect: callback => {
    const current = openStore(root, { identity, clock: () => 30 });
    try { return callback(current); } finally { current.close(); }
  } };
}

function makePlan(operations) { return { format: 1, mailboxIdentity: identity, snapshotId, binding, configHash, operations }; }
function runOp(f, id = 'run-one', outcome = 'resume', source = 'adapter') {
  return { kind: 'run', id, fingerprint: f.inspect(store => store.runFingerprint(id)), outcome, evidence: evidence(source) };
}
function actionOp(f, key, outcome = 'no-effect') {
  return { kind: 'action', key, fingerprint: f.inspect(store => store.actionFingerprint(key)), outcome, evidence: evidence('adapter') };
}
async function reviewed(f, plan, dependencies) {
  const preview = await previewRecovery({ ...f.options, plan }, dependencies);
  return { ...f.options, actor, reason, plan, expectedPlanDigest: preview.planDigest };
}

test('preview is metadata-only and apply preserves budgets/grants with one-time reservation accounting while held', async t => {
  const f = await fixture(t, [run('run-one', { status: 'running', activeOperation: { reservedMs: 40 } })]);
  const before = f.inspect(store => ({ run: store.getRun('run-one'), hold: store.getMeta('restore_hold'), cursor: store.getMeta('cursor') }));
  const plan = makePlan([runOp(f)]);
  const preview = await previewRecovery({ ...f.options, plan });
  assert.equal(preview.planDigest, digest(plan));
  assert.equal(JSON.stringify(preview).includes('SYNTHETIC_PRIVATE'), false);
  assert.deepEqual(f.inspect(store => store.getRun('run-one')), before.run);
  const result = await applyRecovery({ ...f.options, actor, reason, plan, expectedPlanDigest: preview.planDigest });
  assert.equal(result.applied, true);
  const after = f.inspect(store => ({ run: store.getRun('run-one'), hold: store.getMeta('restore_hold'), cursor: store.getMeta('cursor') }));
  assert.equal(after.run.status, 'queued');
  assert.deepEqual(after.run.budget, { modelCalls: 2, toolCalls: 1, activeMs: 45 });
  assert.equal(after.run.activeOperation, undefined);
  assert.deepEqual(after.run.grants, before.run.grants);
  assert.deepEqual(after.run.recovery, { binding, planDigest: preview.planDigest, outcome: 'resume', evidenceHash: evidence().recordHash });
  assert.equal(after.hold, before.hold);
  assert.equal(after.cursor, before.cursor);
  const receipt = JSON.parse(f.inspect(store => store.getMeta(`recovery_batch:${preview.planDigest}`)));
  assert.deepEqual(receipt.runs, [{ id: 'run-one', originalFingerprint: plan.operations[0].fingerprint,
    appliedFingerprint: f.inspect(store => store.runFingerprint('run-one')), outcome: 'resume', evidenceHash: evidence().recordHash }]);
  const fingerprint = f.inspect(store => store.runFingerprint('run-one'));
  const repeat = await applyRecovery({ ...f.options, actor, reason, plan, expectedPlanDigest: preview.planDigest });
  assert.equal(repeat.idempotent, true);
  assert.equal(f.inspect(store => store.runFingerprint('run-one')), fingerprint);
  await assert.rejects(applyRecovery({ ...f.options, actor, reason: 'Different attribution', plan, expectedPlanDigest: preview.planDigest }));
});

test('action absence resolves to pending before run resumption without creating tool results or replacing approval', async t => {
  const call = { id: 'call-one', name: 'synthetic.write', args: { value: 'SYNTHETIC_PRIVATE_ARGS' } };
  const key = digest(['run-one', call.name, call.args]);
  const approval = { id: 'approval-one', args: call.args };
  const f = await fixture(t, [run('run-one', { status: 'uncertain', pending: [call], uncertainty: { kind: 'tool', key }, approval })]);
  f.inspect(store => store.saveAction({ key, runId: 'run-one', state: 'uncertain', effect: 'write', tool: call.name }));
  const plan = makePlan([runOp(f), actionOp(f, key)]);
  await applyRecovery(await reviewed(f, plan));
  f.inspect(store => {
    assert.equal(store.getAction(key).state, 'pending');
    assert.equal(Object.hasOwn(store.getAction(key), 'result'), false);
    assert.equal(store.getRun('run-one').status, 'queued');
    assert.deepEqual(store.getRun('run-one').approval, approval);
    assert.equal(store.getRun('run-one').uncertainty, undefined);
  });
});

test('pending approvals stay pending and known send absence retries only the original retained outbox', async t => {
  const approval = { id: 'approval-one', expiresAt: 1000 };
  const f = await fixture(t, [run('run-one', { status: 'awaiting_approval', approval }),
    run('send-run', { status: 'uncertain', uncertainty: { kind: 'send' }, reply: 'SYNTHETIC_PRIVATE_REPLY', sequence: 2 })]);
  const plan = makePlan([runOp(f), runOp(f, 'send-run', 'resume', 'graph')]);
  await applyRecovery(await reviewed(f, plan));
  f.inspect(store => {
    assert.equal(store.getRun('run-one').status, 'awaiting_approval');
    assert.deepEqual(store.getRun('run-one').approval, approval);
    assert.equal(store.getRun('send-run').status, 'ready_to_send');
    assert.equal(store.getRun('send-run').reply, 'SYNTHETIC_PRIVATE_REPLY');
  });
});

test('sent conclusions allow expired send uncertainty, while fences and abandoned work preserve unknown actions', async t => {
  const f = await fixture(t, [run('run-one', { status: 'uncertain', contentExpired: true, mail: undefined, uncertainty: { kind: 'send' } }),
    run('fenced-run', { status: 'running', uncertainty: { kind: 'tool', key: 'unknown' }, sequence: 2 }), run('skipped-run', { sequence: 3 })]);
  f.inspect(store => store.saveAction({ key: 'unknown', runId: 'fenced-run', state: 'executing', effect: 'write' }));
  const plan = makePlan([runOp(f, 'run-one', 'sent', 'graph'), runOp(f, 'fenced-run', 'fenced'), runOp(f, 'skipped-run', 'skip'), actionOp(f, 'unknown', 'fenced')]);
  await applyRecovery(await reviewed(f, plan));
  f.inspect(store => {
    assert.equal(store.getRun('run-one').status, 'completed');
    assert.equal(store.getRun('fenced-run').status, 'uncertain');
    assert.deepEqual(store.getRun('fenced-run').uncertainty, { kind: 'tool', key: 'unknown' });
    assert.equal(store.getRun('skipped-run').status, 'failed');
    assert.equal(store.getAction('unknown').state, 'uncertain');
    assert.equal(Object.hasOwn(store.getAction('unknown'), 'result'), false);
  });
});

test('missing messages create content-free replay fences and reject existing ledger collisions', async t => {
  const f = await fixture(t);
  const operations = ['sent', 'fenced'].map((outcome, index) => ({ kind: 'message', messageId: `SYNTHETIC_PRIVATE_MESSAGE_${index}`,
    conversationId: 'SYNTHETIC_PRIVATE_CONVERSATION', outcome, evidence: evidence(outcome === 'sent' ? 'graph' : 'operator') }));
  const plan = makePlan(operations);
  const input = await reviewed(f, plan);
  assert.equal(JSON.stringify(await previewRecovery({ ...f.options, plan })).includes('SYNTHETIC_PRIVATE'), false);
  await applyRecovery(input);
  f.inspect(store => {
    for (const [index, operation] of operations.entries()) {
      const fence = store.byMessage(digest([agentId, operation.messageId]));
      assert.equal(fence.status, operation.outcome === 'sent' ? 'completed' : 'uncertain');
      assert.equal(fence.conversationKey, digest(operation.conversationId));
      assert.equal(fence.sequence, 10 + index);
      assert.deepEqual(fence.budget, { modelCalls: 0, toolCalls: 0, activeMs: 0 });
      for (const field of ['mail', 'messages', 'reply', 'pending', 'approval', 'grants', 'instructionSnapshot']) assert.equal(fence[field], undefined);
      assert.equal(JSON.stringify(fence).includes(operation.messageId), false);
    }
    assert.equal(store.getMeta('queue_sequence'), '11');
  });
  const collision = makePlan([{ ...operations[0], evidence: { ...evidence('graph'), recordHash: 'd'.repeat(64) } }]);
  await assert.rejects(previewRecovery({ ...f.options, plan: collision }));
});

test('stale targets, held binding drift, wrong review digest and malformed plans reject without mutations', async t => {
  const f = await fixture(t);
  const plan = makePlan([runOp(f)]), input = await reviewed(f, plan);
  const before = f.inspect(store => store.runFingerprint('run-one'));
  for (const change of [{ expectedPlanDigest: undefined }, { expectedPlanDigest: 'd'.repeat(64) }, { actor: 'invalid' }, { reason: '' },
    { plan: { ...plan, body: 'SYNTHETIC_PRIVATE_INJECTION' } }]) await assert.rejects(applyRecovery({ ...input, ...change }));
  assert.equal(f.inspect(store => store.runFingerprint('run-one')), before);
  f.inspect(store => { const value = store.getRun('run-one'); value.status = 'running'; store.saveRun(value); });
  await assert.rejects(applyRecovery(input));
  f.inspect(store => store.setMeta('cursor', 'different-synthetic-cursor'));
  await assert.rejects(applyRecovery(input));
});

test('resumption rejects expired/malformed/exhausted work, operator claims of possible effects and unresolved actions', async t => {
  const invalid = [
    { contentExpired: true }, { createdAt: 0 }, { mail: undefined }, { status: 'completed' }, { budget: { modelCalls: -1, toolCalls: 1, activeMs: 0 } },
    { budget: { modelCalls: 7, toolCalls: 1, activeMs: 0 } }, { budget: { modelCalls: 1, toolCalls: 11, activeMs: 0 } },
    { budget: { modelCalls: 1, toolCalls: 1, activeMs: 120_000 } }, { activeOperation: { reservedMs: -1 } },
    { activeOperation: { reservedMs: Number.MAX_SAFE_INTEGER } }, { status: 'sending' }, { status: 'uncertain', uncertainty: { kind: 'tool', key: 'missing' } }
  ];
  for (const change of invalid) {
    const f = await fixture(t, [run('run-one', change)]);
    await assert.rejects(previewRecovery({ ...f.options, contentHours: change.createdAt === 0 ? 1 : 24,
      clock: () => change.createdAt === 0 ? 3_600_001 : 30, plan: makePlan([runOp(f)]) }));
  }
  const f = await fixture(t, [run('run-one', { status: 'running' })]);
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f, 'run-one', 'resume', 'operator')]) }));
  f.inspect(store => store.saveAction({ key: 'unknown', runId: 'run-one', state: 'uncertain', effect: 'write' }));
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) }));
  f.inspect(store => store.saveAction({ key: 'completed', runId: 'run-one', state: 'completed', effect: 'write', result: { private: true } }));
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([actionOp(f, 'completed')]) }));
});

test('all targets validate before writes and an interrupted transaction rolls back actions, runs, imports, audits and receipts', async t => {
  const f = await fixture(t);
  f.inspect(store => store.saveAction({ key: 'unknown', runId: 'run-one', state: 'uncertain', effect: 'write' }));
  const plan = makePlan([runOp(f), actionOp(f, 'unknown'), { kind: 'message', messageId: 'missing-message', conversationId: 'conversation',
    outcome: 'fenced', evidence: evidence('operator') }]);
  const input = await reviewed(f, plan);
  const controller = new AbortController();
  const withStore = async (_options, callback) => f.inspect(store => {
    const original = store.saveAction;
    store.saveAction = value => { original(value); controller.abort(); };
    return callback(store, { rawHold: hold, rawCursor: cursor, binding, recovery: { snapshotId, snapshotCreatedAt: 10 }, stateSchema: 5 });
  });
  await assert.rejects(applyRecovery({ ...input, signal: controller.signal }, { withStore }));
  f.inspect(store => {
    assert.equal(store.getAction('unknown').state, 'uncertain');
    assert.equal(store.getRun('run-one').recovery, undefined);
    assert.equal(store.byMessage(digest([agentId, 'missing-message'])), undefined);
    assert.equal(store.getMeta(`recovery_batch:${input.expectedPlanDigest}`), undefined);
    assert.equal(store.getMeta('queue_sequence'), '9');
    assert.equal(store.getMeta('restore_hold'), hold);
  });
  const stale = makePlan([actionOp(f, 'unknown'), { ...runOp(f), fingerprint: 'f'.repeat(64) }]);
  await assert.rejects(applyRecovery({ ...f.options, actor, reason, plan: stale, expectedPlanDigest: digest(stale) }));
  assert.equal(f.inspect(store => store.getAction('unknown').state), 'uncertain');
});

test('uncertain tool resumption accepts only absence decisions for this binding and the original pending call', async t => {
  const call = { name: 'synthetic.write', args: { value: 'synthetic' } }, key = digest(['run-one', call.name, call.args]);
  const f = await fixture(t, [run('run-one', { status: 'uncertain', uncertainty: { kind: 'tool', key }, pending: [call] })]);
  f.inspect(store => store.saveAction({ key, runId: 'run-one', state: 'uncertain', effect: 'write' }));
  const actionPlan = makePlan([actionOp(f, key)]);
  await applyRecovery(await reviewed(f, actionPlan));
  await previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) });
  f.inspect(store => { const value = store.getAction(key); value.recovery.binding = 'd'.repeat(64); store.saveAction(value); });
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) }));
  f.inspect(store => { const value = store.getAction(key); value.recovery.binding = binding; store.saveAction(value);
    const current = store.getRun('run-one'); current.pending = [{ ...call, args: { value: 'different' } }]; store.saveRun(current); });
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) }));
});

test('transaction failure after earlier audits and replay-fence insertion leaves the entire batch unapplied', async t => {
  const f = await fixture(t);
  f.inspect(store => store.saveAction({ key: 'unknown', runId: 'run-one', state: 'uncertain', effect: 'write' }));
  const plan = makePlan([actionOp(f, 'unknown'), runOp(f), { kind: 'message', messageId: 'missing-message', conversationId: 'conversation',
    outcome: 'sent', evidence: evidence('graph') }]);
  const input = await reviewed(f, plan);
  const withStore = async (_options, callback) => f.inspect(store => {
    const save = store.saveRun;
    let writes = 0;
    store.saveRun = value => { save(value); if (++writes === 2) throw new Error('SYNTHETIC_PRIVATE_DATABASE_FAILURE'); };
    return callback(store, { rawHold: hold, rawCursor: cursor, binding, recovery: { snapshotId, snapshotCreatedAt: 10 }, stateSchema: 5 });
  });
  await assert.rejects(applyRecovery(input, { withStore }), error => {
    assert.equal(error.code, 'RECOVERY_APPLY_INVALID');
    assert.equal(error.message, 'Recovery decisions are invalid or do not match the held state.');
    assert.equal(error.cause, undefined);
    return true;
  });
  f.inspect(store => {
    assert.equal(store.getAction('unknown').state, 'uncertain');
    assert.equal(store.getRun('run-one').recovery, undefined);
    assert.equal(store.byMessage(digest([agentId, 'missing-message'])), undefined);
    assert.equal(store.getMeta('queue_sequence'), '9');
    assert.equal(store.getMeta(`recovery_batch:${input.expectedPlanDigest}`), undefined);
  });
  const db = new DatabaseSync(join(f.options.stateRoot, 'agent.sqlite'), { readOnly: true });
  assert.equal(db.prepare("SELECT count(*) AS count FROM audit WHERE event='recovery-decision'").get().count, 0);
  db.close();
});

test('review digest format and cancellation fail before opening state, while an absent hold rejects all decisions', async t => {
  const f = await fixture(t);
  const plan = makePlan([runOp(f)]), input = await reviewed(f, plan);
  let opened = 0;
  const withStore = async () => { opened++; throw new Error('SYNTHETIC_PRIVATE_FAILURE'); };
  await assert.rejects(applyRecovery({ ...input, expectedPlanDigest: 'invalid' }, { withStore }));
  const controller = new AbortController(); controller.abort();
  await assert.rejects(previewRecovery({ ...f.options, plan, signal: controller.signal }, { withStore }));
  await assert.rejects(applyRecovery({ ...input, signal: controller.signal }, { withStore }));
  assert.equal(opened, 0);
  f.inspect(store => store.setMeta('restore_hold', ''));
  await assert.rejects(previewRecovery({ ...f.options, plan }));
  await assert.rejects(applyRecovery(input));
});

test('audits contain only attribution/evidence hashes and idempotent repeats append no new records', async t => {
  const f = await fixture(t);
  const plan = makePlan([runOp(f)]), input = await reviewed(f, plan);
  await applyRecovery(input);
  await applyRecovery(input);
  const db = new DatabaseSync(join(f.options.stateRoot, 'agent.sqlite'), { readOnly: true });
  const records = db.prepare("SELECT actor,target,details FROM audit WHERE event='recovery-decision'").all();
  assert.equal(records.length, 1);
  assert.equal(records[0].actor, digest(actor));
  assert.equal(records[0].target, 'run-one');
  assert.equal(JSON.parse(records[0].details).reasonHash, digest(reason));
  assert.equal(JSON.stringify(records).includes('SYNTHETIC_PRIVATE'), false);
  assert.equal(JSON.stringify(records).includes(reason), false);
  db.close();
});

test('queued snapshot work with zero recorded budget still requires provider or adapter absence evidence', async t => {
  const f = await fixture(t, [run('run-one', { budget: { modelCalls: 0, toolCalls: 0, activeMs: 0 } })]);
  const plan = makePlan([runOp(f, 'run-one', 'resume', 'operator')]);
  await assert.rejects(previewRecovery({ ...f.options, plan }));
  await assert.rejects(applyRecovery({ ...f.options, actor, reason, plan, expectedPlanDigest: digest(plan) }));
  assert.equal(f.inspect(store => store.getRun('run-one').recovery), undefined);
});

test('unknown legacy budgets remain unknown under conservative decisions and expired accepted-send conclusions', async t => {
  const f = await fixture(t, [run('run-one', { budget: undefined }), run('fenced-run', { budget: null, activeOperation: { reservedMs: 'unknown' }, sequence: 2 }),
    run('sent-run', { budget: undefined, status: 'uncertain', contentExpired: true, mail: undefined, uncertainty: { kind: 'send' }, sequence: 3 })]);
  const plan = makePlan([runOp(f, 'run-one', 'skip'), runOp(f, 'fenced-run', 'fenced'), runOp(f, 'sent-run', 'sent', 'graph')]);
  await applyRecovery(await reviewed(f, plan));
  f.inspect(store => {
    assert.equal(store.getRun('run-one').status, 'failed');
    assert.equal(store.getRun('run-one').budget, undefined);
    assert.equal(store.getRun('fenced-run').status, 'uncertain');
    assert.equal(store.getRun('fenced-run').budget, null);
    assert.deepEqual(store.getRun('fenced-run').activeOperation, { reservedMs: 'unknown' });
    assert.equal(store.getRun('sent-run').status, 'completed');
    assert.equal(store.getRun('sent-run').budget, undefined);
  });
});

test('completed and ignored history cannot be rewritten by any recovery decision', async t => {
  for (const status of ['completed', 'ignored']) {
    const f = await fixture(t, [run('run-one', { status })]);
    const before = f.inspect(store => store.runFingerprint('run-one'));
    for (const outcome of ['resume', 'skip', 'fenced', 'sent']) {
      const plan = makePlan([runOp(f, 'run-one', outcome, outcome === 'sent' ? 'graph' : 'adapter')]);
      await assert.rejects(previewRecovery({ ...f.options, plan }));
      await assert.rejects(applyRecovery({ ...f.options, actor, reason, plan, expectedPlanDigest: digest(plan) }));
    }
    assert.equal(f.inspect(store => store.runFingerprint('run-one')), before);
  }
});

test('abandonment cannot hide sending, uncertain, unresolved or merely operator-attested effects', async t => {
  for (const status of ['sending', 'uncertain']) {
    const f = await fixture(t, [run('run-one', { status, reply: 'synthetic reply', uncertainty: { kind: 'send' } })]);
    const before = f.inspect(store => store.runFingerprint('run-one'));
    const plan = makePlan([runOp(f, 'run-one', 'skip', 'graph')]);
    await assert.rejects(previewRecovery({ ...f.options, plan }));
    await assert.rejects(applyRecovery({ ...f.options, actor, reason, plan, expectedPlanDigest: digest(plan) }));
    assert.equal(f.inspect(store => store.runFingerprint('run-one')), before);
  }
  const f = await fixture(t);
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f, 'run-one', 'skip', 'operator')]) }));
  f.inspect(store => store.saveAction({ key: 'unknown', runId: 'run-one', state: 'uncertain', effect: 'write' }));
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f, 'run-one', 'skip')]) }));
  await applyRecovery(await reviewed(f, makePlan([runOp(f, 'run-one', 'skip'), actionOp(f, 'unknown')])));
  assert.equal(f.inspect(store => store.getRun('run-one').status), 'failed');
  const outbox = await fixture(t, [run('run-one', { status: 'ready_to_send', reply: 'synthetic reply' })]);
  await assert.rejects(previewRecovery({ ...outbox.options, plan: makePlan([runOp(outbox, 'run-one', 'skip', 'adapter')]) }));
  await applyRecovery(await reviewed(outbox, makePlan([runOp(outbox, 'run-one', 'skip', 'graph')])));
  assert.equal(outbox.inspect(store => store.getRun('run-one').status), 'failed');
});

test('prior action absence requires its exact committed batch decision and current action fingerprint', async t => {
  const call = { name: 'synthetic.write', args: { value: 'synthetic' } }, key = digest(['run-one', call.name, call.args]);
  const f = await fixture(t, [run('run-one', { status: 'uncertain', uncertainty: { kind: 'tool', key }, pending: [call] })]);
  f.inspect(store => store.saveAction({ key, runId: 'run-one', state: 'pending', effect: 'write', recovery: {
    binding, planDigest: 'd'.repeat(64), outcome: 'no-effect', evidenceHash: evidence().recordHash
  } }));
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) }));
  f.inspect(store => { const value = store.getAction(key); value.state = 'uncertain'; delete value.recovery; store.saveAction(value); });
  const decision = actionOp(f, key), actionPlan = makePlan([decision]);
  const input = await reviewed(f, actionPlan);
  await applyRecovery(input);
  const receiptKey = `recovery_batch:${input.expectedPlanDigest}`;
  const raw = f.inspect(store => store.getMeta(receiptKey)), receipt = JSON.parse(raw);
  assert.ok(Buffer.byteLength(raw) <= 262_144);
  assert.deepEqual(receipt.actions, [{ key, originalFingerprint: decision.fingerprint,
    appliedFingerprint: f.inspect(store => store.actionFingerprint(key)), outcome: 'no-effect', evidenceHash: evidence().recordHash }]);
  await previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) });
  for (const change of [
    value => { value.mailboxIdentity = 'f'.repeat(64); }, value => { value.configHash = 'f'.repeat(64); },
    value => { value.snapshotId = '22222222-2222-4222-8222-222222222222'; }, value => { value.binding = 'f'.repeat(64); },
    value => { value.actions[0].evidenceHash = 'f'.repeat(64); }, value => { value.actions[0].outcome = 'fenced'; },
    value => { value.actions[0].key = 'other-action'; }, value => { delete value.actions; }
  ]) {
    const mutated = structuredClone(receipt); change(mutated);
    f.inspect(store => store.setMeta(receiptKey, JSON.stringify(mutated)));
    await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) }));
  }
  f.inspect(store => store.setMeta(receiptKey, raw));
  f.inspect(store => { const value = store.getAction(key); value.tool = 'different-tool'; store.saveAction(value); });
  await assert.rejects(previewRecovery({ ...f.options, plan: makePlan([runOp(f)]) }));
});

test('one hundred legal Unicode action decisions fit a byte-bounded private receipt and remain idempotent', async t => {
  const f = await fixture(t);
  const decisions = f.inspect(store => Array.from({ length: 100 }, (_, index) => {
    const key = `${index}${'漢'.repeat(250)}`;
    store.saveAction({ key, runId: 'run-one', state: 'uncertain', effect: 'write' });
    return { kind: 'action', key, fingerprint: store.actionFingerprint(key), outcome: 'no-effect', evidence: evidence('adapter') };
  }));
  const plan = makePlan(decisions), input = await reviewed(f, plan);
  await applyRecovery(input);
  const raw = f.inspect(store => store.getMeta(`recovery_batch:${input.expectedPlanDigest}`));
  assert.ok(Buffer.byteLength(raw) > 65_536);
  assert.ok(Buffer.byteLength(raw) <= 262_144);
  assert.equal(JSON.parse(raw).actions.length, 100);
  assert.equal((await applyRecovery(input)).idempotent, true);
});
