import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { once } from 'node:events';
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import test from 'node:test';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { DEFAULT_INHERITED_ENV_VARS, StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { createRuntime } from '../src/runtime.mjs';
import { createMcp } from '../src/mcp.mjs';
import { digest } from '../src/policy.mjs';

const now = 1_800_000_000_000;
const execute = promisify(execFile);
const serverPath = fileURLToPath(new URL('../mcp/records/server.mjs', import.meta.url));
const preloadPath = fileURLToPath(new URL('./fixtures/records/crash-preload.mjs', import.meta.url));
const actor = 'operator@example.test';
const mail = { id: 'synthetic-message', conversationId: 'synthetic-conversation', sender: 'alice@example.test',
  replyTo: 'alice@example.test', to: ['agent@example.test'], cc: [], subject: 'Synthetic approved update',
  body: 'Update the synthetic record.', receivedAt: '2026-10-01T00:00:00Z', authenticated: true,
  autoGenerated: false, attachments: false };
const seed = { format: 1, id: 'record-a', revision: 1, type: 'note', title: 'Original synthetic title',
  content: 'Synthetic content', tags: [], source: { kind: 'operator', referenceHash: 'a'.repeat(64) },
  createdAt: now - 1000, updatedAt: now - 1000, updatedByHash: 'b'.repeat(64), deleted: false };
const operator = { actor, reason: 'Inspected the stopped synthetic authoritative operation.' };

function configuration(fx) {
  return { id: 'records-crash', state_root: './state', mailbox: { address: 'agent@example.test',
    tenant_id: 'synthetic', client_id: 'synthetic', sender_authentication: { mode: 'exchange-authenticated' } },
    model: { capabilities: { tools: true } }, mcp: { records: { transport: 'stdio', command: 'node',
      args: ['--import', preloadPath, serverPath, '--root', fx.recordsRoot, '--policy', fx.policyFile],
      actor_context: 'mail-agent-v1', timeout_ms: 10_000, env: ['RECORDS_CRASH_ROOT', 'RECORDS_CRASH_MODE'] } },
    policy: { senders: [mail.sender], recipients: [mail.sender], approvers: [actor], tools: {
      'records.propose_update': { effect: 'read', authorization: 'automatic' },
      'records.apply_approved_update': { effect: 'write', authorization: 'approval' },
    } }, limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000,
      output_tokens: 2000, queue_messages: 100 }, retention: { content_hours: 24, audit_days: 30 } };
}

async function fixture(t, mode) {
  const root = await mkdtemp(join(tmpdir(), 'records-crash-'));
  await chmod(root, 0o700);
  const recordsRoot = join(root, 'business'), directory = join(recordsRoot, 'records', seed.id);
  await mkdir(directory, { recursive: true, mode: 0o700 });
  await writeFile(join(directory, 'record.json'), JSON.stringify(seed), { mode: 0o600 });
  const policyFile = join(root, 'policy.json');
  await writeFile(policyFile, JSON.stringify({ version: 1, agentId: 'records-crash', mailbox: 'agent@example.test',
    connection: 'records', members: { [mail.sender]: { read: [seed.id], edit: [seed.id], delete: [] } }, approvers: [actor] }), { mode: 0o600 });
  const fx = { root, recordsRoot, directory, policyFile, mode, children: [], runtimes: [],
    counters: { modelCalls: 0, toolCalls: 0, writeDispatches: 0, replies: 0 }, barrier: barrier() };
  fx.config = configuration(fx);
  t.after(async () => {
    for (const child of fx.children) await terminate(child);
    for (const runtime of fx.runtimes.reverse()) await runtime.stop();
    await rm(root, { recursive: true, force: true });
  });
  fx.runtime = await runtime(fx, mode);
  return fx;
}

function barrier() {
  let reach;
  const promise = new Promise(resolve => { reach = resolve; });
  return { promise, reach };
}

function observeBarrier(fx, stream) {
  let bytes = '';
  stream.on('data', chunk => {
    bytes += chunk.toString();
    assert.ok(bytes.length <= 4096, 'Fixture stderr exceeded its synthetic bound.');
    if (bytes.includes(`RECORDS_CRASH_BOUNDARY:${fx.mode}\n`)) fx.barrier.reach();
  });
}

async function factory(fx, options, { signal }) {
  const client = new Client({ name: 'synthetic-records-crash', version: '1' }, { capabilities: {} });
  const transport = new StdioClientTransport({ command: options.command, args: options.args, cwd: options.cwd,
    env: { ...Object.fromEntries(DEFAULT_INHERITED_ENV_VARS.map(name => [name, undefined])), ...options.env }, stderr: 'pipe' });
  observeBarrier(fx, transport.stderr);
  try {
    await client.connect(transport, { signal, timeout: options.timeout });
    // The dependency is pinned. Capture the exact owned handle, never search or kill by process name.
    const child = transport._process;
    assert.equal(child.pid, transport.pid);
    fx.children.push(child);
    return client;
  } catch (error) { await transport.close(); throw error; }
}

function proposal(messages) {
  for (const message of messages) for (const part of message.content ?? []) {
    if (part.type !== 'tool-result' || part.toolName !== 'records.propose_update') continue;
    return JSON.parse(part.output.value.content[0].text);
  }
  throw new Error('Synthetic model did not receive the real proposal.');
}

function model(fx) {
  return { async step({ messages }) {
    fx.counters.modelCalls++;
    if (fx.counters.modelCalls === 1) return { text: '', toolCalls: [{ id: 'proposal', name: 'records.propose_update',
      args: { recordId: seed.id, expectedRevision: 1, patch: { title: 'Approved synthetic title' } } }] };
    if (fx.counters.modelCalls === 2) {
      const value = proposal(messages);
      return { text: '', toolCalls: [{ id: 'apply', name: 'records.apply_approved_update', args: {
        recordId: value.recordId, expectedRevision: value.expectedRevision, expectedRecordHash: value.expectedRecordHash,
        patch: value.patch, proposalDigest: value.proposalDigest,
      } }] };
    }
    return { text: 'Synthetic update confirmed.', toolCalls: [] };
  } };
}

async function runtime(fx, mode = 'none') {
  const real = createMcp(fx.config.mcp, { root: fx.root,
    env: { RECORDS_CRASH_ROOT: fx.recordsRoot, RECORDS_CRASH_MODE: mode }, clock: () => now,
    clientFactory: (options, settings) => factory(fx, options, settings) });
  const mcp = { listTools: options => real.listTools(options), close: () => real.close(),
    call: (name, args, options) => {
      fx.counters.toolCalls++;
      if (name === 'records.apply_approved_update') fx.counters.writeDispatches++;
      return real.call(name, args, options);
    } };
  const value = await createRuntime({ config: fx.config, root: fx.root, instructions: 'Synthetic governed records update.',
    hash: 'synthetic', clock: () => now, env: {}, mcp, model: model(fx),
    mail: { reply: async () => { fx.counters.replies++; return { status: 'accepted' }; } } });
  fx.runtimes.push(value);
  return value;
}

async function terminate(child) {
  if (child.exitCode !== null || child.signalCode !== null) return;
  const exit = once(child, 'exit');
  assert.equal(child.kill('SIGKILL'), true);
  await exit;
}

async function crash(fx) {
  assert.equal((await fx.runtime.processMessage(mail)).status, 'awaiting_approval');
  const [approval] = await fx.runtime.approvals();
  await fx.runtime.approve({ id: approval.id, actor, reason: 'Approve the exact synthetic revision.' });
  const pending = fx.runtime.processMessage(mail);
  await Promise.race([fx.barrier.promise, pending.then(() => assert.fail('Owned adapter never reached the required crash boundary.'))]);
  const child = fx.children.at(-1), exit = once(child, 'exit');
  assert.equal(child.kill('SIGKILL'), true);
  assert.deepEqual(await exit, [null, 'SIGKILL']);
  assert.equal((await pending).status, 'uncertain');
  const intent = await fx.runtime.recordsIntent({ actionKey: approval.id, ...operator });
  await fx.runtime.stop();
  return { actionKey: approval.id, intent };
}

async function inspect(fx, intent) {
  const path = join(fx.root, 'intent.json');
  await writeFile(path, JSON.stringify(intent), { mode: 0o600 });
  const { stdout, stderr } = await execute(process.execPath, ['--import', preloadPath, serverPath, 'inspect',
    '--root', fx.recordsRoot, '--policy', fx.policyFile, '--intent', path, '--actor', actor, '--reason', operator.reason],
  { env: {}, timeout: 5000, maxBuffer: 8192 });
  assert.equal(stderr, '');
  return JSON.parse(stdout);
}

async function record(fx) { return JSON.parse(await readFile(join(fx.directory, 'record.json'), 'utf8')); }
async function committedReceipts(fx) {
  return (await readdir(join(fx.recordsRoot, 'operations'))).filter(name => name.endsWith('.receipt.json'));
}

for (const mode of ['before-publication', 'after-publication']) {
  test(`actual records child SIGKILL ${mode} preserves inspection and exact reconciliation fences`,
    { skip: process.platform === 'win32', timeout: 30_000 }, async t => {
      const fx = await fixture(t, mode);
      const { actionKey, intent } = await crash(fx);
      const published = mode === 'after-publication';
      assert.equal((await record(fx)).revision, published ? 2 : 1);
      assert.equal((await committedReceipts(fx)).length, 0, 'Crash occurs before adapter receipt and acknowledgement.');
      const observed = await inspect(fx, intent);
      assert.equal(observed.status, published ? 'committed' : 'not-applied');
      assert.equal(observed.operationId, actionKey);
      assert.equal(observed.argsHash, intent.argsHash);
      assert.equal(observed.recordHash, digest(await record(fx)));
      const before = { ...fx.counters };
      const recovered = await runtime(fx);
      assert.equal((await recovered.processMessage(mail)).status, 'uncertain');
      assert.deepEqual(fx.counters, before, 'Restart never automatically retries the unknown write.');
      assert.equal((await recovered.reconcileRecords({ actionKey, receipt: observed, ...operator })).status, 'queued');
      if (!published) {
        assert.equal((await recovered.processMessage(mail)).status, 'awaiting_approval');
        assert.deepEqual(fx.counters, before, 'Absence evidence never grants another write.');
        const [approval] = await recovered.approvals();
        assert.equal(approval.id, actionKey);
        await recovered.approve({ id: actionKey, actor, reason: 'Fresh exact approval after stopped absence inspection.' });
      }
      assert.equal((await recovered.processMessage(mail)).status, 'completed');
      assert.equal((await record(fx)).revision, 2);
      assert.equal((await record(fx)).title, 'Approved synthetic title');
      assert.equal((await record(fx)).lastOperationId, actionKey);
      assert.equal((await record(fx)).lastArgsHash, intent.argsHash);
      assert.equal(fx.counters.writeDispatches, published ? 1 : 2);
      const after = { ...fx.counters };
      await recovered.stop();
      const replayed = await runtime(fx);
      assert.equal((await replayed.processMessage(mail)).status, 'completed');
      assert.deepEqual(fx.counters, after);
      assert.equal((await record(fx)).revision, 2);
      assert.equal(fx.counters.replies, 1);
    });
}

test('SIGKILL before publication with a subsequently changed authoritative record remains unresolved and fenced',
  { skip: process.platform === 'win32', timeout: 30_000 }, async t => {
    const fx = await fixture(t, 'before-publication');
    const { actionKey, intent } = await crash(fx);
    const changed = { ...seed, revision: 2, title: 'Independent synthetic operator revision',
      updatedAt: now, updatedByHash: 'c'.repeat(64) };
    await writeFile(join(fx.directory, 'record.json'), JSON.stringify(changed), { mode: 0o600 });
    const observed = await inspect(fx, intent);
    assert.equal(observed.status, 'unresolved');
    const before = { ...fx.counters };
    const recovered = await runtime(fx);
    await assert.rejects(recovered.reconcileRecords({ actionKey, receipt: observed, ...operator }), /Records reconciliation denied/);
    assert.equal((await recovered.processMessage(mail)).status, 'uncertain');
    assert.deepEqual(fx.counters, before);
    assert.deepEqual(await record(fx), changed);
    assert.equal((await committedReceipts(fx)).length, 0);
    assert.equal(fx.counters.replies, 0);
  });
