import assert from 'node:assert/strict';
import test from 'node:test';
import { chmod, cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { backupState } from '../src/backup.mjs';
import { createMcp } from '../src/mcp.mjs';
import { digest } from '../src/policy.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';
import { createRuntime } from '../src/runtime.mjs';
import { createRecordsAdapter } from '../mcp/records/records.mjs';
import { inspectRecovery } from '../src/recovery-inspect.mjs';
import { previewRecovery, applyRecovery } from '../src/recovery-apply.mjs';
import { previewRecoveryRelease, applyRecoveryRelease } from '../src/recovery-release.mjs';
import { restoreState } from '../src/restore.mjs';

const now = 1_800_000_000_000;
const actor = 'operator@example.test';
const serverPath = fileURLToPath(new URL('../mcp/records/server.mjs', import.meta.url));
const seed = { format: 1, id: 'record-a', revision: 1, type: 'note', title: 'Current title',
  content: 'Synthetic current content', tags: ['alpha'], source: { kind: 'operator', referenceHash: 'a'.repeat(64) },
  createdAt: now - 1000, updatedAt: now - 1000, updatedByHash: 'b'.repeat(64), deleted: false };

function configFor(recordsRoot, policyFile, clockFile) {
  return {
    id: 'records-recovery-agent', state_root: './state',
    mailbox: { address: 'agent@example.test', tenant_id: 'synthetic-tenant', client_id: 'synthetic-client',
      sender_authentication: { mode: 'exchange-authenticated', transport_headers_verified: true }, poll_seconds: 30 },
    model: { name: 'synthetic-model', capabilities: { tools: true } }, instructions: {},
    mcp: { records: { transport: 'stdio', command: process.execPath, pinned_version: 'synthetic-1',
      authorization_scope: 'sender-group', actor_context: 'mail-agent-v1', env: [], timeout_ms: 5000,
      args: ['--import', clockFile, serverPath, '--root', recordsRoot, '--policy', policyFile] } },
    policy: { senders: ['alice@example.test'], recipients: ['alice@example.test'], approvers: [actor], reply: 'sender',
      tools: {
        'records.get': { effect: 'read', authorization: 'automatic' },
        'records.propose_update': { effect: 'read', authorization: 'automatic' },
        'records.apply_approved_update': { effect: 'write', authorization: 'approval' },
      } },
    limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000, output_tokens: 2000, queue_messages: 100 },
    retention: { content_hours: 24, audit_days: 30 },
  };
}

function actorPolicy() {
  return { version: 1, agentId: 'records-recovery-agent', mailbox: 'agent@example.test', connection: 'records',
    members: { 'alice@example.test': { read: ['record-a'], edit: ['record-a'], delete: [] } }, approvers: [actor] };
}

function email() {
  return { id: 'message-recovery', conversationId: 'conversation-recovery', sender: 'alice@example.test', replyTo: 'alice@example.test',
    to: ['agent@example.test'], cc: [], subject: 'Update synthetic record', body: 'Change the synthetic record title.',
    receivedAt: new Date(now).toISOString(), authenticated: true, autoGenerated: false, attachments: false };
}

function proposalFrom(messages) {
  for (const message of [...messages].reverse()) for (const part of [...(message.content ?? [])].reverse()) {
    if (part.type !== 'tool-result' || part.toolName !== 'records.propose_update') continue;
    return JSON.parse(part.output.value.content.find(item => item.type === 'text').text);
  }
  throw new Error('Expected a synthetic proposal.');
}

function releaseSettings(value, plan, hash, clock) {
  return { stateRoot: value.stateRoot, identity: value.identity, configHash: hash, config: value.config,
    plan, actor, reason: 'Review the stopped synthetic backup and records evidence.', clock };
}

test('stopped agent backup preserves records uncertainty while its separate quiescent root preserves the committed receipt', async t => {
  const root = await mkdtemp(join(tmpdir(), 'ma-records-recovery-'));
  const runtimes = [];
  t.after(async () => {
    for (const instance of [...runtimes].reverse()) await instance.stop().catch(() => {});
    await rm(root, { recursive: true, force: true });
  });
  await chmod(root, 0o700);
  const stateRoot = join(root, 'state');
  const recordsRoot = join(root, 'records-live');
  const recordDir = join(recordsRoot, 'records', seed.id);
  await mkdir(recordDir, { recursive: true, mode: 0o700 });
  for (const directory of [recordsRoot, join(recordsRoot, 'records'), recordDir]) await chmod(directory, 0o700);
  await writeFile(join(recordDir, 'record.json'), `${JSON.stringify(seed, null, 2)}\n`, { mode: 0o600 });
  const policyFile = join(root, 'records-policy.json');
  await writeFile(policyFile, `${JSON.stringify(actorPolicy())}\n`, { mode: 0o600 });
  const clockFile = join(root, 'fixed-clock.mjs');
  await writeFile(clockFile, `Date.now = () => ${now};\n`, { mode: 0o600 });
  const config = configFor(recordsRoot, policyFile, clockFile);
  const identity = mailboxIdentity(config);
  const configHash = digest('records-recovery-config');
  const cursor = JSON.stringify({ url: 'https://graph.microsoft.com/v1.0/users/agent%40example.test/mailFolders/inbox/messages/delta?$deltatoken=synthetic', initialComplete: true });
  const { openStore } = await import('../src/store.mjs');
  const sourceStore = openStore(stateRoot, { identity, clock: () => now });
  sourceStore.setMeta('cursor', cursor);
  sourceStore.close();

  let modelCalls = 0;
  const model = { async step({ messages }) {
    modelCalls++;
    if (modelCalls === 1) return { text: '', toolCalls: [{ id: 'proposal', name: 'records.propose_update', args: {
      recordId: seed.id, expectedRevision: 1, patch: { title: 'Committed synthetic title' } } }] };
    if (modelCalls === 2) {
      const proposal = proposalFrom(messages);
      return { text: '', toolCalls: [{ id: 'approved-write', name: 'records.apply_approved_update', args: {
        recordId: proposal.recordId, expectedRevision: proposal.expectedRevision, expectedRecordHash: proposal.expectedRecordHash,
        patch: proposal.patch, proposalDigest: proposal.proposalDigest,
      } }] };
    }
    return { text: 'Synthetic update reconciled.', toolCalls: [] };
  } };
  let loseWriteResponse = true;
  const makeMcp = () => {
    const real = createMcp(config.mcp, { root, env: {}, clock: () => now });
    return {
      listTools: options => real.listTools(options),
      async call(name, args, options) {
        const result = await real.call(name, args, options);
        if (loseWriteResponse && name === 'records.apply_approved_update') {
          loseWriteResponse = false;
          throw new Error('Synthetic response lost after the authoritative record commit.');
        }
        return result;
      },
      close: () => real.close(),
    };
  };
  const createRuntimeAt = async target => {
    const instance = await createRuntime({ config, root: target, instructions: 'Use the synthetic records adapter.',
      hash: configHash, clock: () => now + (config.state_root === './restored-state' ? 2000 : 0), env: {}, model,
      mail: { async reply() { return { status: 'accepted' }; } }, mcp: makeMcp() });
    runtimes.push(instance);
    return instance;
  };

  let runtime = await createRuntimeAt(root);
  assert.equal((await runtime.processMessage(email())).status, 'awaiting_approval');
  const [approval] = await runtime.approvals();
  await runtime.approve({ id: approval.id, actor, reason: 'Approve this exact synthetic update.' });
  assert.equal((await runtime.processMessage(email())).status, 'uncertain');
  const runId = runtime.status().runs[0].id;
  assert.equal(JSON.parse(await readFile(join(recordDir, 'record.json'), 'utf8')).revision, 2);
  await runtime.stop();
  const originalReceipt = await readFile(join(recordsRoot, 'operations', `${approval.id}.receipt.json`));

  const snapshot = join(root, 'agent-backup');
  const snapshotResult = await backupState({ stateRoot, directory: snapshot, identity, clock: () => now });
  assert.equal(snapshotResult.stateSchema, 5);
  assert.deepEqual((await readdir(snapshot)).sort(), ['artifacts', 'manifest.json', 'snapshot.sqlite']);
  assert.deepEqual(JSON.parse(await readFile(join(snapshot, 'manifest.json'), 'utf8')).artifacts, []);
  const recordsBackup = join(root, 'records-backup');
  await cp(recordsRoot, recordsBackup, { recursive: true });
  await chmod(recordsBackup, 0o700);
  assert.deepEqual(await readFile(join(recordsBackup, 'operations', `${approval.id}.receipt.json`)), originalReceipt);
  const restoredRecordsRoot = join(root, 'records-restored');
  await cp(recordsBackup, restoredRecordsRoot, { recursive: true });
  await chmod(restoredRecordsRoot, 0o700);
  const restoredPolicy = join(root, 'records-policy-restored.json');
  await cp(policyFile, restoredPolicy);
  await chmod(restoredPolicy, 0o600);
  const restoredClock = join(root, 'fixed-clock-restored.mjs');
  await cp(clockFile, restoredClock);
  await chmod(restoredClock, 0o600);
  config.mcp.records.args = ['--import', restoredClock, serverPath, '--root', restoredRecordsRoot, '--policy', restoredPolicy];

  const restoredStateRoot = join(root, 'restored-state');
  const restoreResult = await restoreState({ snapshot, stateRoot: restoredStateRoot, identity, actor,
    reason: 'Restore synthetic agent state before reconciling records.', clock: () => now + 1000 });
  assert.equal(restoreResult.recoveryRequired, true);
  config.state_root = './restored-state';
  runtime = await createRuntimeAt(root);
  assert.equal(runtime.status().recovery.required, true);
  assert.equal(runtime.status().runs[0].status, 'uncertain');
  await assert.rejects(runtime.processMessage(email()), /recovery|restore/i);
  await assert.rejects(runtime.reconcileRecords({ actionKey: approval.id,
    receipt: JSON.parse(await readFile(join(restoredRecordsRoot, 'operations', `${approval.id}.receipt.json`), 'utf8')),
    actor, reason: 'Inspect the committed synthetic receipt.' }), /recovery|restore/i);
  await runtime.stop();

  const inspected = await inspectRecovery({ stateRoot: restoredStateRoot, identity, configHash, clock: () => now + 1000 });
  const run = inspected.items.find(item => item.id === runId);
  const actionPage = await inspectRecovery({ stateRoot: restoredStateRoot, identity, configHash, kind: 'actions', clock: () => now + 1000 });
  const action = actionPage.items.find(item => item.key === approval.id);
  assert.ok(run?.fingerprint);
  assert.ok(action?.fingerprint);
  const evidence = source => ({ source, recordHash: digest(`verified synthetic ${source}`), observedAt: now + 1000 });
  const recoveryPlan = { format: 1, mailboxIdentity: identity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash, operations: [
      { kind: 'run', id: run.id, fingerprint: run.fingerprint, outcome: 'fenced', evidence: evidence('adapter') },
      { kind: 'action', key: action.key, fingerprint: action.fingerprint, outcome: 'fenced', evidence: evidence('adapter') },
    ] };
  const recoveryOptions = { stateRoot: restoredStateRoot, identity, configHash, agentId: config.id,
    contentHours: 24, limits: config.limits, plan: recoveryPlan, clock: () => now + 1000 };
  const recoveryPreview = await previewRecovery(recoveryOptions);
  await applyRecovery({ ...recoveryOptions, expectedPlanDigest: recoveryPreview.planDigest, actor,
    reason: 'Keep the committed adapter action fenced until its receipt is checked.' });
  const releasePlan = { format: 1, mode: 'continuity', mailboxIdentity: identity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash,
    coverage: { from: inspected.recovery.snapshotCreatedAt, through: now + 2000, oldOwnerStoppedAt: now,
      evidenceHash: digest('complete synthetic Graph and records adapter history'), allSources: true }, acceptHistoryGap: false };
  const releaseOptions = releaseSettings({ stateRoot: restoredStateRoot, identity, config }, releasePlan, configHash, () => now + 2000);
  const releasePreview = await previewRecoveryRelease(releaseOptions);
  assert.equal(releasePreview.released, false);
  const released = await applyRecoveryRelease({ ...releaseOptions, expectedReviewDigest: releasePreview.reviewDigest });
  assert.equal(released.released, true);

  runtime = await createRuntimeAt(root);
  try {
    assert.equal(runtime.status().recovery, null);
    const receipt = JSON.parse(await readFile(join(restoredRecordsRoot, 'operations', `${approval.id}.receipt.json`), 'utf8'));
    assert.equal((await runtime.reconcileRecords({ actionKey: approval.id, receipt, actor,
      reason: 'Match the restored uncertain action to its authoritative commit receipt.' })).status, 'queued');
    assert.equal((await runtime.processMessage(email())).status, 'completed');
    assert.equal(JSON.parse(await readFile(join(restoredRecordsRoot, 'records', seed.id, 'record.json'), 'utf8')).revision, 2);
    assert.equal((await readdir(join(restoredRecordsRoot, 'operations'))).filter(name => name.endsWith('.receipt.json')).length, 1);
  } finally { await runtime?.stop(); }
});

test('stopped backup preserves an unresolved records intent and its fence without retrying after held restore', async t => {
  const root = await mkdtemp(join(tmpdir(), 'ma-records-unresolved-recovery-'));
  const runtimes = [];
  let adapter;
  t.after(async () => {
    for (const instance of [...runtimes].reverse()) await instance.stop().catch(() => {});
    await adapter?.close().catch(() => {});
    await rm(root, { recursive: true, force: true });
  });
  await chmod(root, 0o700);
  const recordsRoot = join(root, 'records-live');
  const recordDir = join(recordsRoot, 'records', seed.id);
  await mkdir(recordDir, { recursive: true, mode: 0o700 });
  for (const directory of [recordsRoot, join(recordsRoot, 'records'), recordDir]) await chmod(directory, 0o700);
  await writeFile(join(recordDir, 'record.json'), `${JSON.stringify(seed, null, 2)}\n`, { mode: 0o600 });
  const policyFile = join(root, 'records-policy.json');
  await writeFile(policyFile, `${JSON.stringify(actorPolicy())}\n`, { mode: 0o600 });
  const clockFile = join(root, 'fixed-clock.mjs');
  await writeFile(clockFile, `Date.now = () => ${now};\n`, { mode: 0o600 });
  const config = configFor(recordsRoot, policyFile, clockFile);
  const identity = mailboxIdentity(config), configHash = digest('records-unresolved-recovery-config');
  const stateRoot = join(root, 'state');
  const { openStore } = await import('../src/store.mjs');
  const initial = openStore(stateRoot, { identity, clock: () => now });
  initial.setMeta('cursor', JSON.stringify({ url: 'https://graph.microsoft.com/v1.0/users/agent%40example.test/mailFolders/inbox/messages/delta?$deltatoken=synthetic', initialComplete: true }));
  initial.close();

  let modelCalls = 0, adapterCalls = 0, sent = 0;
  const model = { async step({ messages }) {
    modelCalls++;
    if (modelCalls === 1) return { text: '', toolCalls: [{ id: 'proposal', name: 'records.propose_update', args: {
      recordId: seed.id, expectedRevision: 1, patch: { title: 'Initially committed title' } } }] };
    if (modelCalls === 2) {
      const proposal = proposalFrom(messages);
      return { text: '', toolCalls: [{ id: 'approved-write', name: 'records.apply_approved_update', args: {
        recordId: proposal.recordId, expectedRevision: proposal.expectedRevision, expectedRecordHash: proposal.expectedRecordHash,
        patch: proposal.patch, proposalDigest: proposal.proposalDigest,
      } }] };
    }
    return { text: 'Must not be generated after the unresolved fence.', toolCalls: [] };
  } };
  adapter = createRecordsAdapter({ root: recordsRoot, policy: actorPolicy(), clock: () => now,
    afterPublish: async () => { throw new Error('Synthetic interruption after record publication.'); } });
  const mcp = {
    listTools: async () => new Map(adapter.listTools().map(definition => [`records.${definition.name}`, definition])),
    async call(name, args, options) {
      adapterCalls++;
      const result = await adapter.call(name.slice('records.'.length), args, options.context);
      return { content: [{ type: 'text', text: JSON.stringify(result) }] };
    },
    close: () => adapter.close(),
  };
  const createRuntimeAt = async (target, offset = 0) => {
    const instance = await createRuntime({ config, root: target, instructions: 'Use only the synthetic records adapter.',
      hash: configHash, clock: () => now + offset, env: {}, model, mcp,
      mail: { async reply() { sent++; return { status: 'accepted' }; } } });
    runtimes.push(instance);
    return instance;
  };

  let runtime = await createRuntimeAt(root);
  assert.equal((await runtime.processMessage(email())).status, 'awaiting_approval');
  const [approval] = await runtime.approvals();
  await runtime.approve({ id: approval.id, actor, reason: 'Approve the exact synthetic operation.' });
  assert.equal((await runtime.processMessage(email())).status, 'uncertain');
  assert.equal(adapterCalls, 2);
  assert.equal(sent, 0);
  await adapter.close();
  await runtime.stop();

  const intentPath = join(recordsRoot, 'operations', `${approval.id}.intent.json`);
  const pendingPath = join(recordDir, 'pending.json');
  const savedIntent = await readFile(intentPath);
  const savedPending = await readFile(pendingPath);
  assert.equal(await readFile(join(recordsRoot, 'operations', `${approval.id}.receipt.json`)).then(() => true, () => false), false);
  const externallyChanged = JSON.parse(await readFile(join(recordDir, 'record.json'), 'utf8'));
  externallyChanged.revision = 3;
  externallyChanged.title = 'Synthetic concurrent operator change';
  externallyChanged.updatedAt = now + 1;
  externallyChanged.updatedByHash = 'c'.repeat(64);
  await writeFile(join(recordDir, 'record.json'), `${JSON.stringify(externallyChanged, null, 2)}\n`, { mode: 0o600 });

  const snapshot = join(root, 'agent-backup');
  await backupState({ stateRoot, directory: snapshot, identity, clock: () => now + 2 });
  const recordsBackup = join(root, 'records-backup');
  await cp(recordsRoot, recordsBackup, { recursive: true });
  await chmod(recordsBackup, 0o700);
  const restoredRecordsRoot = join(root, 'records-restored');
  await cp(recordsBackup, restoredRecordsRoot, { recursive: true });
  await chmod(restoredRecordsRoot, 0o700);
  const restoredPolicy = join(root, 'records-policy-restored.json');
  await cp(policyFile, restoredPolicy);
  await chmod(restoredPolicy, 0o600);
  const restoredClock = join(root, 'fixed-clock-restored.mjs');
  await cp(clockFile, restoredClock);
  await chmod(restoredClock, 0o600);
  config.mcp.records.args = ['--import', restoredClock, serverPath, '--root', restoredRecordsRoot, '--policy', restoredPolicy];
  assert.deepEqual(await readFile(join(restoredRecordsRoot, 'operations', `${approval.id}.intent.json`)), savedIntent);
  assert.deepEqual(await readFile(join(restoredRecordsRoot, 'records', seed.id, 'pending.json')), savedPending);

  const restoredStateRoot = join(root, 'restored-state');
  await restoreState({ snapshot, stateRoot: restoredStateRoot, identity, actor,
    reason: 'Restore the stopped synthetic agent backup.', clock: () => now + 3 });
  config.state_root = './restored-state';
  runtime = await createRuntimeAt(root, 5);
  assert.equal(runtime.status().recovery.required, true);
  assert.equal(runtime.status().runs[0].status, 'uncertain');
  await assert.rejects(runtime.processMessage(email()), /recovery|restore/i);
  await runtime.stop();

  const inspected = await inspectRecovery({ stateRoot: restoredStateRoot, identity, configHash, clock: () => now + 5 });
  const actionPage = await inspectRecovery({ stateRoot: restoredStateRoot, identity, configHash, kind: 'actions', clock: () => now + 5 });
  const run = inspected.items.find(item => item.status === 'uncertain');
  const action = actionPage.items.find(item => item.key === approval.id);
  const evidence = { source: 'adapter', recordHash: digest('synthetic unresolved adapter state'), observedAt: now + 5 };
  const recoveryPlan = { format: 1, mailboxIdentity: identity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash, operations: [
      { kind: 'run', id: run.id, fingerprint: run.fingerprint, outcome: 'fenced', evidence },
      { kind: 'action', key: action.key, fingerprint: action.fingerprint, outcome: 'fenced', evidence },
    ] };
  const recoveryOptions = { stateRoot: restoredStateRoot, identity, configHash, agentId: config.id,
    contentHours: 24, limits: config.limits, plan: recoveryPlan, clock: () => now + 5 };
  const recoveryPreview = await previewRecovery(recoveryOptions);
  await applyRecovery({ ...recoveryOptions, expectedPlanDigest: recoveryPreview.planDigest, actor,
    reason: 'Preserve the unresolved records effect fence.' });
  const releasePlan = { format: 1, mode: 'continuity', mailboxIdentity: identity, snapshotId: inspected.recovery.snapshotId,
    binding: inspected.binding, configHash,
    coverage: { from: inspected.recovery.snapshotCreatedAt, through: now + 10, oldOwnerStoppedAt: now + 1,
      evidenceHash: digest('complete synthetic provider and records history'), allSources: true }, acceptHistoryGap: false };
  const releaseOptions = releaseSettings({ stateRoot: restoredStateRoot, identity, config }, releasePlan, configHash, () => now + 10);
  const releasePreview = await previewRecoveryRelease(releaseOptions);
  await applyRecoveryRelease({ ...releaseOptions, expectedReviewDigest: releasePreview.reviewDigest });

  runtime = await createRuntimeAt(root, 10);
  try {
    assert.equal(runtime.status().recovery, null);
    assert.equal((await runtime.processMessage(email())).status, 'uncertain');
    const intent = JSON.parse(savedIntent.toString('utf8'));
    const inspector = createRecordsAdapter({ root: restoredRecordsRoot, policy: actorPolicy(), clock: () => now + 10 });
    const unresolved = await inspector.inspectOperation({ intent, actor, reason: 'Inspect the copied pending record state.' });
    await inspector.close();
    assert.equal(unresolved.status, 'unresolved');
    await assert.rejects(runtime.reconcileRecords({ actionKey: approval.id, receipt: unresolved, actor,
      reason: 'Attempt to reconcile unresolved synthetic evidence.' }), /Records reconciliation denied/);
    assert.equal(runtime.status().runs[0].status, 'uncertain');
    assert.equal(modelCalls, 2);
    assert.equal(adapterCalls, 2);
    assert.equal(sent, 0);
    assert.equal(JSON.parse(await readFile(join(restoredRecordsRoot, 'records', seed.id, 'record.json'), 'utf8')).revision, 3);
    assert.equal(await readFile(join(restoredRecordsRoot, 'operations', `${approval.id}.receipt.json`)).then(() => true, () => false), false);
  } finally { await runtime.stop(); }
});

