import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { cp, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRuntime } from '../src/runtime.mjs';
import { openStore } from '../src/store.mjs';

function config() {
  return {
    id: 'recovery-drill', state_root: './state',
    mailbox: { address: 'agent@example.org', tenant_id: 'tenant-synthetic', client_id: 'client-synthetic', poll_seconds: 30 },
    model: { capabilities: { tools: false } },
    policy: { senders: ['alice@example.org'], recipients: ['alice@example.org'], approvers: ['admin@example.org'], tools: {} },
    mcp: {}, limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000, output_tokens: 2000, queue_messages: 100 },
    retention: { content_hours: 24, audit_days: 30 }
  };
}

function message(id, overrides = {}) {
  return {
    id, conversationId: `conversation-${id}`, sender: 'alice@example.org', replyTo: 'alice@example.org',
    to: ['agent@example.org'], cc: [], subject: 'Synthetic recovery drill', body: 'Synthetic question.',
    receivedAt: '2026-01-01T00:00:00Z', authenticated: true, autoGenerated: false, attachments: false,
    ...overrides
  };
}

async function makeRuntime(t, root, configValue, options = {}) {
  const runtime = await createRuntime({
    config: configValue, root, instructions: 'Use only synthetic test data.', hash: 'recovery-config',
    model: { step: async () => ({ text: 'Synthetic reply.', toolCalls: [] }) },
    mail: { reply: async () => ({ status: 'accepted' }) },
    listenControl: async () => ({ close: async () => {} }),
    ...options
  });
  t.after(() => runtime.stop());
  return runtime;
}

async function fixture(t, options = {}) {
  const root = await mkdtemp(join(tmpdir(), 'ma-recovery-drill-'));
  const cfg = config();
  const runtimes = [];
  const create = async (overrides = {}) => {
    const runtime = await makeRuntime(t, root, cfg, { ...options, ...overrides });
    runtimes.push(runtime);
    return runtime;
  };
  t.after(async () => {
    for (const runtime of [...runtimes].reverse()) await runtime.stop();
    await rm(root, { recursive: true, force: true });
  });
  const runtime = await create();
  return { root, config: cfg, runtime, create, runtimes };
}

test('accepted intake checkpoint and interrupted model work survive restart without re-admitting the page', async t => {
  let hold = true;
  let enterModel;
  const modelEntered = new Promise(resolve => { enterModel = resolve; });
  let releaseModel;
  const blockedModel = new Promise(resolve => { releaseModel = resolve; });
  const attempts = [];
  const replies = [];
  const checkpoint = JSON.stringify({ initialComplete: true, delta: 'synthetic-accepted-page' });
  const mail = {
    poll: async ({ cursor }) => {
      attempts.push(cursor);
      if (attempts.length === 1) return { messages: [], cursor: JSON.stringify({ initialComplete: true, delta: 'baseline' }) };
      if (attempts.length === 2) return { messages: [message('checkpointed-message')], cursor: checkpoint };
      assert.equal(cursor, checkpoint);
      return { messages: [], cursor: checkpoint };
    },
    reply: async input => { replies.push(input.id); return { status: 'accepted' }; }
  };
  const model = { step: async () => {
    if (hold) { enterModel(); await blockedModel; }
    return { text: 'Recovered after interruption.', toolCalls: [] };
  } };
  const h = await fixture(t, { mail, model });
  await h.runtime.start({ once: true });
  const intake = h.runtime.start({ once: true });
  await modelEntered;
  await h.runtime.stop();
  await intake;
  assert.equal(h.runtime.status().sync.baseline, 'complete');
  assert.equal(h.runtime.status().counts.queued, 1);

  hold = false;
  releaseModel();
  const resumed = await h.create();
  await resumed.start({ once: true });
  assert.equal(attempts.length, 3);
  assert.deepEqual(replies, ['checkpointed-message']);
  assert.equal(resumed.status().counts.completed, 1);
});

test('replacement Graph and model credentials pass read-only probes without changing mailbox identity or scope', async t => {
  const env = { SYNTHETIC_GRAPH_SECRET: 'old-graph-secret', SYNTHETIC_MODEL_KEY: 'old-model-key' };
  const cfg = config();
  cfg.mailbox.client_secret_env = 'SYNTHETIC_GRAPH_SECRET';
  cfg.model.api_key_env = 'SYNTHETIC_MODEL_KEY';
  let entered;
  const blocked = new Promise(resolve => { entered = resolve; });
  let release;
  const hold = new Promise(resolve => { release = resolve; });
  let blockModel = true;
  const replies = [];
  const mail = {
    check: async () => {
      assert.equal(env.SYNTHETIC_GRAPH_SECRET, 'new-graph-secret');
      return { status: 'ready' };
    },
    reply: async input => { replies.push(input.id); return { status: 'accepted' }; }
  };
  const model = { step: async () => {
    if (blockModel) {
      assert.equal(env.SYNTHETIC_MODEL_KEY, 'old-model-key');
      entered();
      await hold;
    } else assert.equal(env.SYNTHETIC_MODEL_KEY, 'new-model-key');
    return { text: 'Synthetic probe or recovered reply.', toolCalls: [] };
  } };
  const before = structuredClone(cfg);
  const root = await mkdtemp(join(tmpdir(), 'ma-credential-rotation-'));
  const options = { env, mail, model, mcp: { listTools: async () => new Map(), close: async () => {} } };
  const first = await makeRuntime(t, root, cfg, options);
  t.after(async () => { await first.stop(); await rm(root, { recursive: true, force: true }); });
  const pending = first.processMessage(message('rotation-pending'));
  await blocked;
  await first.stop();
  assert.equal((await pending).status, 'queued');

  env.SYNTHETIC_GRAPH_SECRET = 'new-graph-secret';
  env.SYNTHETIC_MODEL_KEY = 'new-model-key';
  blockModel = false;
  release();
  const replacement = await makeRuntime(t, root, cfg, options);
  const identity = value => [value.id, value.mailbox.tenant_id, value.mailbox.client_id, value.mailbox.address];
  assert.deepEqual(identity(cfg), identity(before));
  assert.deepEqual(cfg.policy.senders, before.policy.senders);
  assert.deepEqual(cfg.policy.recipients, before.policy.recipients);
  const probe = await replacement.liveCheck();
  assert.equal(probe.ready, true);
  assert.equal(probe.externalMutations, false);
  assert.equal(replacement.status().counts.queued, 1);
  assert.deepEqual(replies, []);
  assert.equal((await replacement.processMessage(message('rotation-pending'))).status, 'completed');
  assert.deepEqual(replies, ['rotation-pending']);
  await replacement.stop();
});

function runRecord(id, sequence, status, extra = {}) {
  return {
    id, messageKey: `message-${id}`, conversationKey: `conversation-${id}`, sequence, status,
    createdAt: 1_000 + sequence, configHash: 'synthetic',
    budget: { modelCalls: 2, toolCalls: 1, activeMs: 37 },
    mail: { sender: 'alice@example.org', body: 'synthetic private content' },
    ...extra
  };
}

function downgradeToVersionTwo(db) {
  const triggers = db.prepare("SELECT name FROM sqlite_master WHERE type='trigger' AND (name LIKE 'runs_projection_%' OR name LIKE 'actions_result_%')").all();
  for (const { name } of triggers) db.exec(`DROP TRIGGER ${name}`);
  for (const name of ['projection_result_expiry', 'actions_results']) db.exec(`DROP INDEX IF EXISTS ${name}`);
  db.exec("ALTER TABLE run_projection DROP COLUMN result_actions; UPDATE meta SET value='2' WHERE key='schema_version';");
}

function downgradeToVersionOne(db) {
  downgradeToVersionTwo(db);
  const triggers = db.prepare("SELECT name FROM sqlite_master WHERE type='trigger' AND (name LIKE 'runs_projection_%' OR name LIKE 'actions_uncertainty_%')").all();
  for (const { name } of triggers) db.exec(`DROP TRIGGER ${name}`);
  for (const name of ['projection_active_operation', 'projection_uncertain_recovery', 'projection_status_page', 'projection_sequence', 'projection_active_sequence', 'actions_state_key']) db.exec(`DROP INDEX IF EXISTS ${name}`);
  for (const name of ['budget_present', 'model_calls', 'tool_calls', 'active_ms', 'active_operation', 'uncertain_actions']) db.exec(`ALTER TABLE run_projection DROP COLUMN ${name}`);
  db.exec("UPDATE meta SET value='1' WHERE key='schema_version';");
}

function downgradeToVersionZero(db) {
  downgradeToVersionOne(db);
  for (const { name } of db.prepare("SELECT name FROM sqlite_master WHERE type='trigger'").all()) db.exec(`DROP TRIGGER ${name}`);
  db.exec("DROP TABLE run_projection; DROP TABLE status_counts; DELETE FROM meta WHERE key='schema_version';");
}

test('legacy schema zero through three snapshots preserve queued work, approvals, grants and uncertain fences', async t => {
  const roots = [];
  t.after(async () => { for (const root of roots) await rm(root, { recursive: true, force: true }); });
  for (const version of [0, 1, 2, 3]) {
    const root = await mkdtemp(join(tmpdir(), `ma-migration-v${version}-`));
    roots.push(root);
    let store = openStore(root, { identity: 'synthetic-identity' });
    store.saveRun(runRecord('queued', 1, 'queued'));
    store.saveRun(runRecord('awaiting-approval', 2, 'awaiting_approval', {
      approval: { id: 'approval-synthetic', tool: 'records.append', args: { value: 'synthetic' }, policyHash: 'synthetic-policy' }
    }));
    const grant = { id: 'grant-synthetic', tool: 'records.append', args: { value: 'approved synthetic intent' },
      policyHash: 'approved-policy', expiresAt: 9_999_999_999_999, actor: 'admin@example.org' };
    const pending = { name: 'records.append', args: { value: 'approved synthetic intent' } };
    store.saveRun(runRecord('approved-queued', 3, 'queued', { grants: { 'grant-synthetic': grant }, pending: [pending] }));
    store.saveRun(runRecord('uncertain', 4, 'uncertain', { uncertainty: { kind: 'tool', key: 'fence-synthetic' } }));
    store.saveAction({ key: 'fence-synthetic', runId: 'uncertain', state: 'uncertain', effect: 'write', tool: 'records.append' });
    store.close();

    const db = new DatabaseSync(join(root, 'agent.sqlite'));
    if (version === 0) downgradeToVersionZero(db);
    else if (version === 1) downgradeToVersionOne(db);
    else if (version === 2) downgradeToVersionTwo(db);
    else db.exec("UPDATE meta SET value='3' WHERE key='schema_version';");
    db.close();

    store = openStore(root, { identity: 'synthetic-identity' });
    try {
      assert.equal(store.getMeta('schema_version'), '5');
      assert.deepEqual(store.summary().counts, {
        queued: 2, running: 0, awaiting_approval: 1, ready_to_send: 0, sending: 0,
        completed: 0, failed: 0, ignored: 0, uncertain: 1
      });
      for (const id of ['queued', 'awaiting-approval', 'approved-queued', 'uncertain']) {
        assert.deepEqual(store.getRun(id).budget, { modelCalls: 2, toolCalls: 1, activeMs: 37 });
      }
      assert.equal(store.approvalPage().items[0].id, 'approval-synthetic');
      assert.deepEqual(store.getRun('approved-queued').grants, { 'grant-synthetic': grant });
      assert.deepEqual(store.getRun('approved-queued').pending, [pending]);
      assert.equal(store.getAction('fence-synthetic').state, 'uncertain');
      assert.equal(store.getRun('uncertain').uncertainty.kind, 'tool');
    } finally { store.close(); }
  }
});

test('stopped filesystem snapshot can roll back a post-snapshot accepted send and requires reconciliation before resume', async t => {
  const root = await mkdtemp(join(tmpdir(), 'ma-backup-drill-'));
  const backup = await mkdtemp(join(tmpdir(), 'ma-backup-copy-'));
  t.after(async () => { await rm(root, { recursive: true, force: true }); await rm(backup, { recursive: true, force: true }); });
  const cfg = config();
  let uncertain = false;
  let sends = 0;
  const mail = { reply: async () => {
    sends++;
    if (uncertain) throw Object.assign(new Error('synthetic definite pre-acceptance failure'), { uncertain: false });
    return { status: 'accepted' };
  } };
  let runtime = await createRuntime({
    config: cfg, root, instructions: 'Synthetic recovery drill.', hash: 'synthetic',
    model: { step: async () => ({ text: 'Synthetic reply.', toolCalls: [] }) }, mail,
    listenControl: async () => ({ close: async () => {} })
  });
  uncertain = true;
  assert.equal((await runtime.processMessage(message('snapshot-send'))).status, 'ready_to_send');
  await runtime.stop();
  await cp(join(root, 'state'), join(backup, 'state'), { recursive: true });

  uncertain = false;
  runtime = await createRuntime({
    config: cfg, root, instructions: 'Synthetic recovery drill.', hash: 'synthetic',
    model: { step: async () => ({ text: 'Synthetic reply.', toolCalls: [] }) }, mail,
    listenControl: async () => ({ close: async () => {} })
  });
  assert.equal((await runtime.processMessage(message('snapshot-send'))).status, 'completed');
  assert.equal(sends, 2);
  await runtime.stop();

  await rm(join(root, 'state'), { recursive: true, force: true });
  await cp(join(backup, 'state'), join(root, 'state'), { recursive: true });
  runtime = await createRuntime({
    config: cfg, root, instructions: 'Synthetic recovery drill.', hash: 'synthetic', model: { step: async () => ({ text: 'Should not infer.', toolCalls: [] }) }, mail,
    listenControl: async () => ({ close: async () => {} })
  });
  assert.equal(runtime.status().runs[0].status, 'ready_to_send');
  // This records why a restored checkpoint must be quarantined for provider reconciliation.
  assert.equal((await runtime.processMessage(message('snapshot-send'))).status, 'completed');
  assert.equal(sends, 3);
  await runtime.stop();
});
