import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRuntime } from '../src/runtime.mjs';
import { createRecordsIntent } from '../src/records-reconciliation.mjs';
import { openStore } from '../src/store.mjs';
import { mailboxIdentity } from '../src/state-identity.mjs';
import { reconcileRecords } from '../src/runtime-records.mjs';

const start = 1_800_000_000_000;
const actor = 'admin@example.test';
const mail = { id: 'synthetic-message', conversationId: 'synthetic-conversation', sender: 'alice@example.test',
  to: ['agent@example.test'], replyTo: 'alice@example.test', cc: [], body: 'Review this synthetic update.',
  subject: 'Synthetic records', authenticated: true, autoGenerated: false, attachments: false };
const call = { id: 'call-a', name: 'records.apply_approved_update', args: { recordId: 'record-a', expectedRevision: 1,
  expectedRecordHash: 'c'.repeat(64), proposalDigest: 'd'.repeat(64), patch: { title: 'Synthetic change' } } };

async function fixture(t) {
  const root = await mkdtemp(join(tmpdir(), 'runtime-records-'));
  let now = start, calls = 0, steps = 0, captured;
  const config = { id: 'records-agent', state_root: './state',
    mailbox: { address: 'agent@example.test', tenant_id: 'synthetic-tenant', client_id: 'synthetic-client', sender_authentication: { mode: 'exchange-authenticated' } },
    model: { capabilities: { tools: true } }, mcp: { records: { transport: 'stdio', command: 'node', actor_context: 'mail-agent-v1' } },
    policy: { senders: [mail.sender], recipients: [mail.sender], approvers: [actor], tools: { [call.name]: { effect: 'write', authorization: 'approval' } } },
    limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000, output_tokens: 2000, queue_messages: 100 },
    retention: { content_hours: 1, audit_days: 30 } };
  const sent = [];
  const options = { config, root, instructions: 'Synthetic records workflow.', hash: 'synthetic-config', clock: () => now,
    mail: { reply: async (_, text) => { sent.push(text); return { status: 'accepted' }; } },
    model: { step: async () => ++steps === 1 ? { text: '', toolCalls: [call] } : { text: 'Confirmed.', toolCalls: [] } },
    mcp: { listTools: async () => new Map([[call.name, { inputSchema: { type: 'object' } }]]),
      call: async (_, __, input) => { calls++; captured = input.context; throw new Error('Synthetic lost outcome'); }, close: async () => {} } };
  let runtime = await createRuntime(options);
  t.after(async () => { await runtime.stop(); await rm(root, { recursive: true, force: true }); });
  await runtime.processMessage(mail);
  const [proposal] = await runtime.approvals();
  await runtime.approve({ id: proposal.id, actor, reason: 'Approve exact synthetic update.' });
  const result = await runtime.processMessage(mail);
  assert.equal(result.status, 'uncertain');
  const intent = createRecordsIntent(captured, call);
  now += 10;
  const receipt = outcome => {
    const { agentId, mailbox, connection, operationId, tool, argsHash, recordId, expectedRevision, expectedRecordHash, proposalDigest } = intent;
    return { format: 1, source: 'mail-agent-records', agentId, mailbox, connection, operationId, tool, argsHash,
      recordId, expectedRevision, expectedRecordHash, proposalDigest, status: outcome,
      revision: outcome === 'not-applied' ? 1 : 2, recordHash: outcome === 'not-applied' ? expectedRecordHash : 'f'.repeat(64), inspectedAt: now };
  };
  const reconcile = observed => runtime.reconcileRecords({ actionKey: proposal.id, receipt: observed, actor, reason: 'Inspected stopped authoritative fixture.' });
  const restart = async () => { await runtime.stop(); runtime = await createRuntime(options); return runtime; };
  return { get runtime() { return runtime; }, config, root, intent, receipt, reconcile, restart, sent,
    get calls() { return calls; }, advance: duration => { now += duration; }, runId: result.runId, actionKey: proposal.id };
}

test('records intent is durably inspectable and confirmed commit resumes without repeating a write', async t => {
  const h = await fixture(t);
  assert.deepEqual(await h.runtime.recordsIntent({ actionKey: h.actionKey, actor, reason: 'Inspect uncertain action.' }), h.intent);
  const observed = h.receipt('committed');
  assert.equal((await h.reconcile(observed)).status, 'queued');
  assert.equal((await h.reconcile(observed)).status, 'queued');
  assert.equal(h.calls, 1);
  const resumed = await h.restart();
  assert.equal((await resumed.processMessage(mail)).status, 'completed');
  assert.equal(h.calls, 1);
  assert.equal(h.sent.length, 1);
  await assert.rejects(h.reconcile({ ...observed, recordHash: '0'.repeat(64) }), /Records reconciliation denied/);
});

test('confirmed non-write preserves budgets and requires fresh exact approval', async t => {
  const h = await fixture(t);
  const before = h.runtime.status().runs[0].budget;
  assert.equal((await h.reconcile(h.receipt('not-applied'))).status, 'queued');
  assert.deepEqual(h.runtime.status().runs[0].budget, before);
  assert.equal((await h.runtime.processMessage(mail)).status, 'awaiting_approval');
  assert.equal(h.calls, 1);
  const [proposal] = await h.runtime.approvals();
  await h.runtime.approve({ id: proposal.id, actor, reason: 'Fresh approval after absence proof.' });
  assert.equal((await h.runtime.processMessage(mail)).status, 'uncertain');
  assert.equal(h.calls, 2);
});

test('expired content reconciles the action without restoring mail or retrying', async t => {
  const h = await fixture(t);
  h.advance(3_600_001);
  assert.equal((await h.reconcile(h.receipt('committed'))).status, 'failed');
  assert.equal(h.calls, 1);
  await h.runtime.stop();
  const store = openStore(join(h.root, 'state'), { identity: mailboxIdentity(h.config) });
  try {
    assert.equal(store.getAction(h.actionKey).state, 'completed');
    assert.deepEqual(store.getAction(h.actionKey).domainIntent, h.intent);
    assert.equal(store.getAction(h.actionKey).result, undefined);
    assert.equal(store.getRun(h.runId).mail, undefined);
    assert.equal(store.getRun(h.runId).uncertainty, null);
  } finally { store.close(); }
});

test('revoked policy prevents continuation while a verified commit can be recorded', async t => {
  const h = await fixture(t);
  h.config.policy.senders = [];
  assert.equal((await h.reconcile(h.receipt('committed'))).status, 'failed');
  assert.equal(h.calls, 1);
  assert.equal(h.sent.length, 0);
});

test('unauthorized operator, unknown outcomes and mismatched receipts preserve uncertainty', async t => {
  const h = await fixture(t);
  for (const changed of [{ status: 'unknown' }, { argsHash: '0'.repeat(64) }, { revision: 3 }]) {
    await assert.rejects(h.reconcile({ ...h.receipt('committed'), ...changed }), /Records reconciliation denied/);
  }
  await assert.rejects(h.runtime.reconcileRecords({ actionKey: h.actionKey, receipt: h.receipt('committed'), actor: 'outsider@example.test', reason: 'Untrusted operator.' }), /Records reconciliation denied/);
  assert.equal(h.runtime.status().runs[0].status, 'uncertain');
  assert.equal(h.calls, 1);
});

test('reconciliation rollback preserves the original run and uncertain action', async t => {
  const h = await fixture(t);
  await h.runtime.stop();
  const store = openStore(join(h.root, 'state'), { identity: mailboxIdentity(h.config) });
  try {
    const originalAction = store.getAction(h.actionKey), originalRun = store.getRun(h.runId);
    const originalTransaction = store.transaction;
    const wrapped = { ...store, transaction: callback => originalTransaction(() => { callback(); throw new Error('Synthetic rollback'); }) };
    assert.throws(() => reconcileRecords({ store: wrapped, config: h.config, clock: () => start + 10,
      input: { actionKey: h.actionKey, receipt: h.receipt('committed'), actor, reason: 'Inspect fixture.' },
      audit: (event, run, details) => store.audit(event, run, details) }), /Synthetic rollback/);
    assert.deepEqual(store.getAction(h.actionKey), originalAction);
    assert.deepEqual(store.getRun(h.runId), originalRun);
  } finally { store.close(); }
});

test('resolving one confirmed action preserves another uncertain action on the run', async t => {
  const h = await fixture(t);
  await h.runtime.stop();
  const store = openStore(join(h.root, 'state'), { identity: mailboxIdentity(h.config) });
  try {
    const original = store.getAction(h.actionKey), otherKey = '9'.repeat(64);
    store.saveAction({ ...original, key: otherKey, domainIntent: { ...original.domainIntent, operationId: otherKey, argsHash: '8'.repeat(64) } });
    const result = reconcileRecords({ store, config: h.config, clock: () => start + 10,
      input: { actionKey: h.actionKey, receipt: h.receipt('committed'), actor, reason: 'Inspect fixture.' }, audit: () => {} });
    assert.equal(result.status, 'uncertain');
    assert.equal(store.getAction(h.actionKey).state, 'completed');
    assert.equal(store.getAction(otherKey).state, 'uncertain');
    assert.equal(store.getRun(h.runId).uncertainty.key, otherKey);
  } finally { store.close(); }
});

test('recorded exact reconciliation replay survives retention and non-write receipt age', async t => {
  const committed = await fixture(t), receipt = committed.receipt('committed');
  await committed.reconcile(receipt);
  committed.advance(3_600_001);
  assert.equal((await committed.reconcile(receipt)).status, 'failed');
  assert.equal(committed.calls, 1);
  const absent = await fixture(t), absenceReceipt = absent.receipt('not-applied');
  await absent.reconcile(absenceReceipt);
  absent.advance(300_001);
  assert.equal((await absent.reconcile(absenceReceipt)).status, 'queued');
  assert.equal(absent.calls, 1);
});

test('an outstanding reservation blocks records resolution without changing unknown counters', async t => {
  const h = await fixture(t);
  await h.runtime.stop();
  const store = openStore(join(h.root, 'state'), { identity: mailboxIdentity(h.config) });
  try {
    const run = store.getRun(h.runId);
    run.budget = null;
    run.activeOperation = { reservedMs: null };
    store.saveRun(run);
    assert.throws(() => reconcileRecords({ store, config: h.config, clock: () => start + 10,
      input: { actionKey: h.actionKey, receipt: h.receipt('committed'), actor, reason: 'Inspect fixture.' }, audit: () => {} }), /Records reconciliation denied/);
    assert.deepEqual(store.getRun(h.runId), run);
    assert.equal(store.getAction(h.actionKey).state, 'uncertain');
  } finally { store.close(); }
});
