import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRuntime } from '../src/runtime.mjs';
import { loadConfig } from '../src/config.mjs';
import { parse, stringify } from 'yaml';
import { openStore } from '../src/store.mjs';
import { digest } from '../src/policy.mjs';

function message(overrides = {}) {
  return { id: 'unsupported-1', conversationId: 'thread-1', sender: 'alice@example.org',
    replyTo: 'alice@example.org', to: ['agent@example.org'], cc: [], subject: 'Private subject',
    body: 'Private request', authenticated: true, autoGenerated: false, attachments: true,
    receivedAt: '2026-01-01T00:00:00Z', ...overrides };
}

async function harness(t, options = {}) {
  const root = await mkdtemp(join(tmpdir(), 'ma-unsupported-'));
  const config = { id: 'unsupported', state_root: './state',
    mailbox: { address: 'agent@example.org', tenant_id: 'tenant', client_id: 'client' },
    model: { capabilities: { tools: false } }, mcp: {},
    policy: { senders: ['alice@example.org'], recipients: ['alice@example.org'], approvers: [], tools: {} },
    limits: { model_calls: 6, tool_calls: 10, run_seconds: 120, context_tokens: 16000,
      output_tokens: 2000, queue_messages: 100 }, retention: { content_hours: 24, audit_days: 30 } };
  const sent = [], calls = [], discoveries = [];
  const mail = { reply: async (mail, text) => { sent.push({ mail, text }); return { status: 'accepted' }; }, ...options.mail };
  const settings = { config, root, instructions: 'Help with text requests.', hash: 'synthetic', mail,
    model: { step: async input => { calls.push(input); return { text: 'Text answer', toolCalls: [] }; } },
    mcp: { listTools: async () => { discoveries.push(true); return new Map(); }, close: async () => {} } };
  const runtimes = [await createRuntime(settings)];
  t.after(async () => { for (const runtime of runtimes.reverse()) await runtime.stop(); await rm(root, { recursive: true, force: true }); });
  return { runtime: runtimes[0], config, settings, sent, calls, discoveries, restart: async () => {
    await runtimes.at(-1).stop(); const runtime = await createRuntime(settings); runtimes.push(runtime); return runtime;
  } };
}

test('authorized attachment request gets one deterministic explanation across replay and restart', async t => {
  const h = await harness(t);
  assert.equal((await h.runtime.processMessage(message())).status, 'completed');
  assert.equal(h.calls.length, 0);
  assert.equal(h.discoveries.length, 0);
  assert.equal(h.sent.length, 1);
  assert.match(h.sent[0].text, /plain text|attachments/i);
  assert.ok(h.sent[0].text.length < 512);
  assert.doesNotMatch(h.sent[0].text, /Private subject|Private request/);
  const restarted = await h.restart();
  assert.equal((await restarted.processMessage(message())).status, 'completed');
  assert.equal(h.sent.length, 1);
});

test('unsupported unauthorized, automatic, redirected, CC-only and self mail stays silent', async t => {
  let metadata = 0;
  const h = await harness(t, { mail: { getAttachmentMetadata: async () => { metadata++; return { kind: 'document' }; } } });
  const denied = [{ sender: 'outsider@example.org' }, { authenticated: false }, { authenticated: 'yes' },
    { autoGenerated: true }, { to: [], cc: ['agent@example.org'] }, { replyTo: 'outsider@example.org' }];
  for (const [index, override] of denied.entries()) {
    assert.equal((await h.runtime.processMessage(message({ id: `denied-${index}`, attachments: false, attachmentStatus: 'unknown', ...override }))).status, 'ignored');
  }
  h.config.policy.senders.push('agent@example.org'); h.config.policy.recipients.push('agent@example.org');
  assert.equal((await h.runtime.processMessage(message({ id: 'self', attachments: false, sender: 'agent@example.org', replyTo: 'agent@example.org' }))).status, 'ignored');
  h.config.policy.recipients = [];
  assert.equal((await h.runtime.processMessage(message({ id: 'no-recipient', attachments: false, attachmentStatus: 'unknown' }))).status, 'ignored');
  assert.equal(metadata, 0); assert.equal(h.calls.length, 0); assert.equal(h.sent.length, 0);
});

test('inline and unknown metadata fail closed without inference or attachment contents', async t => {
  for (const kind of ['inline-artifact', 'document', 'unknown']) {
    let metadata = 0;
    const h = await harness(t, { mail: { getAttachmentMetadata: async (id, { signal }) => {
      metadata++; assert.equal(id, 'unsupported-1'); assert.ok(signal); return { kind, count: 1 };
    } } });
    assert.equal((await h.runtime.processMessage(message({ attachments: false, attachmentStatus: 'unknown' }))).status, 'completed');
    assert.equal(metadata, 1); assert.equal(h.calls.length, 0); assert.equal(h.sent.length, 1);
    assert.equal(h.discoveries.length, 0);
  }
});

test('metadata read failure and absent metadata boundary cannot enable inference', async t => {
  for (const mail of [{}, { getAttachmentMetadata: async () => { throw new Error('private provider detail'); } }]) {
    const h = await harness(t, { mail });
    assert.equal((await h.runtime.processMessage(message({ attachments: false, attachmentStatus: 'unknown' }))).status, 'completed');
    assert.equal(h.calls.length, 0); assert.equal(h.sent.length, 1);
    assert.doesNotMatch(h.sent[0].text, /private provider detail/);
  }
});

test('recipient authority is checked again after metadata and before deterministic sending', async t => {
  const h = await harness(t);
  h.settings.mail.getAttachmentMetadata = async () => { h.config.policy.recipients = []; return { kind: 'inline-artifact', count: 1 }; };
  assert.equal((await h.runtime.processMessage(message({ attachments: false, attachmentStatus: 'unknown' }))).status, 'failed');
  assert.equal(h.sent.length, 0); assert.equal(h.calls.length, 0);
});

test('unsupported outbox uses existing uncertainty fence without automatic replay', async t => {
  let attempts = 0;
  const h = await harness(t, { mail: { reply: async () => { attempts++; throw Object.assign(new Error('private'), { uncertain: true }); } } });
  assert.equal((await h.runtime.processMessage(message())).status, 'uncertain');
  const restarted = await h.restart();
  assert.equal((await restarted.processMessage(message())).status, 'uncertain');
  assert.equal(attempts, 1); assert.equal(h.calls.length, 0);
});

test('unsupported runs do not contribute private body or artifact history to later text inference', async t => {
  const h = await harness(t, { });
  h.settings.mcp.listTools = async () => new Map();
  await h.runtime.processMessage(message());
  assert.equal((await h.runtime.processMessage(message({ id: 'text-followup', attachments: false, subject: 'Follow up', body: 'Hello' }))).status, 'completed');
  assert.equal(h.calls.length, 1);
  assert.doesNotMatch(JSON.stringify(h.calls[0].messages), /Private request|Private subject/);
});

test('non-text and empty requests get deterministic explanation without inference', async t => {
  const h = await harness(t);
  for (const [index, override] of [{ bodyFormat: 'html' }, { body: '  ' }].entries()) {
    assert.equal((await h.runtime.processMessage(message({ id: `format-${index}`, attachments: false, ...override }))).status, 'completed');
  }
  assert.equal(h.calls.length, 0); assert.equal(h.sent.length, 2);
  assert.equal(h.discoveries.length, 0);
});

test('initial mailbox baseline never probes old attachment metadata or replies', async t => {
  let probes = 0, page = 0;
  const h = await harness(t, { mail: {
    getAttachmentMetadata: async () => { probes++; return { kind: 'inline-artifact', count: 1 }; },
    poll: async () => ({ messages: [message({ id: `page-${++page}`, attachments: false, attachmentStatus: 'unknown' })],
      cursor: JSON.stringify({ url: 'synthetic', initialComplete: page >= 2 }) })
  } });
  await h.runtime.start({ once: true });
  await h.runtime.start({ once: true });
  assert.equal(probes, 0); assert.equal(h.sent.length, 0);
  await h.runtime.start({ once: true });
  assert.equal(probes, 1); assert.equal(h.sent.length, 1); assert.equal(h.calls.length, 0);
});

test('metadata-confirmed text remains supported but inconsistent metadata cannot enable inference', async t => {
  const h = await harness(t, { mail: { getAttachmentMetadata: async () => ({ kind: 'none', count: 0 }) } });
  assert.equal((await h.runtime.processMessage(message({ attachments: false, attachmentStatus: 'unknown' }))).status, 'completed');
  assert.equal(h.calls.length, 1);
  h.settings.mail.getAttachmentMetadata = async () => ({ kind: 'none', count: 1 });
  assert.equal((await h.runtime.processMessage(message({ id: 'inconsistent', attachments: false, attachmentStatus: 'unknown' }))).status, 'completed');
  assert.equal(h.calls.length, 1); assert.match(h.sent[1].text, /plain text/i);
});

test('shutdown during metadata retains queued work and checks again after restart', async t => {
  let enter;
  const entered = new Promise(done => { enter = done; });
  const h = await harness(t, { mail: { getAttachmentMetadata: async () => { enter(); return new Promise(() => {}); } } });
  const pending = h.runtime.processMessage(message({ attachments: false, attachmentStatus: 'unknown' }));
  await entered;
  await h.runtime.stop();
  assert.equal((await pending).status, 'queued'); assert.equal(h.sent.length, 0);
  h.settings.mail.getAttachmentMetadata = async () => ({ kind: 'inline-artifact', count: 1 });
  const restarted = await h.restart();
  assert.equal((await restarted.processMessage(message())).status, 'completed');
  assert.equal(h.sent.length, 1); assert.equal(h.calls.length, 0);
});

test('reloaded recipient revocation blocks the unsupported outbox', async t => {
  const h = await harness(t);
  await h.runtime.stop();
  const cfg = parse(await readFile(new URL('../examples/text-inbox/agent.yaml', import.meta.url), 'utf8'));
  cfg.state_root = './reload-state'; cfg.mailbox.address = 'agent@example.org';
  cfg.policy.senders = ['alice@example.org']; cfg.policy.recipients = ['alice@example.org'];
  const filename = join(h.settings.root, 'agent.yaml');
  await writeFile(join(h.settings.root, 'AGENT.md'), 'Text only.');
  await writeFile(filename, stringify(cfg));
  const loaded = await loadConfig(filename);
  const mail = { ...h.settings.mail, getAttachmentMetadata: async () => {
    cfg.policy.recipients = ['bob@example.org']; await writeFile(filename, stringify(cfg));
    return { kind: 'inline-artifact', count: 1 };
  } };
  const runtime = await createRuntime({ ...loaded, mail, model: h.settings.model, mcp: h.settings.mcp });
  try {
    assert.equal((await runtime.processMessage(message({ attachments: false, attachmentStatus: 'unknown' }))).status, 'failed');
    assert.equal(h.sent.length, 0); assert.equal(h.calls.length, 0);
  } finally { await runtime.stop(); }
});

test('recovery of a classified unsupported run cannot fall through to inference', async t => {
  let sends = 0;
  const h = await harness(t, { mail: { reply: async () => {
    sends++; if (sends === 1) throw Object.assign(new Error('definitely rejected'), { uncertain: false });
    return { status: 'accepted' };
  } } });
  const first = await h.runtime.processMessage(message());
  assert.equal(first.status, 'ready_to_send');
  await h.runtime.stop();
  const identity = digest([h.config.id, h.config.mailbox.tenant_id, h.config.mailbox.client_id, h.config.mailbox.address]);
  const store = openStore(join(h.settings.root, 'state'), { identity });
  const run = store.getRun(first.runId);
  run.status = 'running'; delete run.reply;
  store.saveRun(run); store.close();
  const restarted = await h.restart();
  assert.equal((await restarted.processMessage(message())).status, 'completed');
  assert.equal(h.calls.length, 0); assert.equal(h.discoveries.length, 0); assert.equal(sends, 2);
});
