import { readFile } from 'node:fs/promises';

export function createFixtureMcp() {
  return {
    async listTools() { return new Map(); },
    async call() { throw new Error('External tools are unavailable in fixture preview'); },
    async close() {},
  };
}

export function createFixtureModel() {
  return {
    async step({ messages }) {
      const latest = messages.filter(message => message.role === 'user').at(-1);
      const content = typeof latest?.content === 'string' ? latest.content : 'Synthetic email request';
      return { text: `Fixture preview: ${content}`, toolCalls: [], usage: { inputTokens: 0, outputTokens: 0 } };
    },
  };
}

export function createFixtureMail() {
  const sent = [];
  const messages = new Map();
  return {
    sent,
    rememberMessage(message) { messages.set(message.id, structuredClone(message)); },
    async poll() { return { messages: [], cursor: null }; },
    async getMessage(id) {
      if (!messages.has(id)) throw new Error(`No fixture mailbox message for ${id}`);
      return structuredClone(messages.get(id));
    },
    async reply(message, text) { sent.push({ id: message.id, text }); return { status: 'accepted' }; },
    async check() { return { mode: 'fixture', connected: false }; },
    async close() {},
  };
}

async function readFixtureText(filename) {
  try { return await readFile(filename, 'utf8'); }
  catch { throw new Error('Fixture request could not be read'); }
}

function parseFixtureText(text) {
  try { return JSON.parse(text); }
  catch { throw new Error('Fixture request must be valid JSON'); }
}

export async function loadFixture(filename) {
  const text = await readFixtureText(filename);
  if (Buffer.byteLength(text) > 262144) throw new Error('Fixture request exceeds 256 KiB');
  const message = parseFixtureText(text);
  const required = ['id', 'conversationId', 'sender', 'subject', 'body', 'receivedAt'];
  for (const key of required) if (typeof message[key] !== 'string' || !message[key]) throw new Error(`Fixture request requires ${key}`);
  for (const key of ['to', 'cc', 'attachments']) if (!Array.isArray(message[key])) throw new Error(`Fixture request requires ${key} array`);
  if (!Number.isFinite(Date.parse(message.receivedAt))) throw new Error('Fixture receivedAt must be an ISO date');
  if (!message.to.every(value => typeof value === 'string') || !message.cc.every(value => typeof value === 'string')) throw new Error('Fixture recipient arrays must contain addresses');
  // Fixture attachment data is discarded; only unsupported-input presence reaches the runtime.
  return { ...message, attachments: message.attachments.length > 0, autoGenerated: Boolean(message.autoGenerated), authenticated: true };
}
