import { IMAGE_BOUNDS, ImageError, imageFail, imageCancelled } from './image-validation.mjs';

function bounded(value, maximum) { return Number.isSafeInteger(value) && value > 0 && value <= maximum; }
function identifier(value) {
  return typeof value === 'string' && value.length > 0 && value.length <= 1024
    && ![...value].some(character => character.charCodeAt(0) < 32 || character.charCodeAt(0) === 127);
}
function settings(value = {}) {
  const limits = {
    maxImages: value.maxImages ?? IMAGE_BOUNDS.count, maxBytes: value.maxBytes ?? IMAGE_BOUNDS.fileBytes,
    maxTotalBytes: value.maxTotalBytes ?? IMAGE_BOUNDS.totalBytes, maxPixels: value.maxPixels ?? IMAGE_BOUNDS.pixels,
  };
  const maxima = { maxImages: IMAGE_BOUNDS.count, maxBytes: IMAGE_BOUNDS.fileBytes, maxTotalBytes: IMAGE_BOUNDS.totalBytes, maxPixels: IMAGE_BOUNDS.hardPixels };
  for (const [name, maximum] of Object.entries(maxima)) if (!bounded(limits[name], maximum)) imageFail('IMAGE_INVALID_LIMITS');
  return limits;
}
function envelope(mail) {
  if (!mail || mail.authenticated !== true || mail.autoGenerated !== false) imageFail('IMAGE_UNAUTHORIZED');
  if (!identifier(mail.id) || !identifier(mail.conversationId) || typeof mail.sender !== 'string') imageFail('IMAGE_UNAUTHORIZED');
  if (mail.replyTo !== undefined && mail.replyTo !== mail.sender) imageFail('IMAGE_UNAUTHORIZED');
}
function attachment(item, limits) {
  if (!identifier(item?.id) || item.type !== 'file' || item.isInline !== false) imageFail('IMAGE_UNSUPPORTED');
  if (!['image/png', 'image/jpeg'].includes(item.contentType)) imageFail('IMAGE_UNSUPPORTED');
  if (!bounded(item.size, limits.maxBytes)) imageFail('IMAGE_TOO_LARGE');
  return { id: item.id, mediaType: item.contentType, size: item.size };
}
function manifest(value, limits) {
  if (value?.complete !== true || !Array.isArray(value.items)) imageFail('IMAGE_UNSUPPORTED');
  if (!value.items.length || value.items.length > limits.maxImages) imageFail('IMAGE_TOO_LARGE');
  const items = value.items.map(item => attachment(item, limits));
  if (new Set(items.map(item => item.id)).size !== items.length) imageFail('IMAGE_UNSUPPORTED');
  if (items.reduce((sum, item) => sum + item.size, 0) > limits.maxTotalBytes) imageFail('IMAGE_TOO_LARGE');
  return items;
}
function readError(error) {
  if (error instanceof ImageError) return error;
  const safe = new ImageError('IMAGE_READ_FAILED');
  if (Number.isSafeInteger(error?.retryNotBefore) && error.retryNotBefore >= 0) {
    safe.code = 'IMAGE_READ_DEFERRED'; safe.retryNotBefore = error.retryNotBefore; safe.deferred = true;
  }
  if ([408, 429, 500, 502, 503, 504].includes(error?.httpStatus)) safe.httpStatus = error.httpStatus;
  safe.retryable = error?.retryable === true;
  return safe;
}
async function cleanup(handles, artifacts) {
  for (const handle of handles) {
    try { await artifacts.remove(handle); }
    catch { /* The run's retention cleanup must remove private remnants. */ }
  }
}

// The runtime must first enforce its current sender, direct-To and recipient policy.
// This boundary cannot derive that authority from attachment metadata or mail content.
export async function prepareImages({ mail, attachments, limits: supplied, artifacts, readAttachment, signal }) {
  imageCancelled(signal); envelope(mail);
  const messageId = mail.id;
  const limits = settings(supplied), items = manifest(attachments, limits), handles = [];
  if (typeof readAttachment !== 'function' || typeof artifacts?.put !== 'function' || typeof artifacts.remove !== 'function') imageFail('IMAGE_INVALID');
  try {
    for (const item of items) {
      imageCancelled(signal);
      const bytes = await readAttachment(messageId, item.id, { maxBytes: item.size, signal });
      imageCancelled(signal);
      if (!(bytes instanceof Uint8Array) || bytes.length !== item.size) imageFail('IMAGE_INVALID');
      const handle = await artifacts.put(bytes, { mediaType: item.mediaType,
        source: { messageId, attachmentId: item.id }, limits: { maxBytes: limits.maxBytes, maxPixels: limits.maxPixels }, signal });
      handles.push(handle); imageCancelled(signal);
    }
    return handles;
  } catch (error) { await cleanup(handles, artifacts); throw readError(error); }
}

export async function imageParts(handles, artifacts, { signal } = {}) {
  if (!Array.isArray(handles) || !handles.length || handles.length > IMAGE_BOUNDS.count) imageFail('IMAGE_INVALID');
  if (new Set(handles.map(handle => handle.id)).size !== handles.length || typeof artifacts?.read !== 'function') imageFail('IMAGE_INVALID');
  const parts = [];
  for (const handle of handles) {
    imageCancelled(signal);
    const bytes = await artifacts.read(handle, { signal }); imageCancelled(signal);
    parts.push({ type: 'file', mediaType: handle.mediaType, data: { type: 'data', data: bytes } });
  }
  return parts;
}
