import { createHash } from 'node:crypto';
import Ajv from 'ajv';

const ajv = new Ajv({ allErrors: false, strict: false });
export const digest = value => createHash('sha256').update(typeof value === 'string' ? value : canonical(value)).digest('hex');
export const address = value => String(value ?? '').trim().toLowerCase();
export function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;
  return JSON.stringify(value);
}

export function admitted(mail, config) {
  if (mail.authenticated !== true || mail.autoGenerated) return false;
  const sender = address(mail.sender);
  if (sender === address(config.mailbox.address)) return false;
  if (!config.policy.senders.includes(sender)) return false;
  if (!config.policy.recipients.includes(sender)) return false;
  if (!mail.to.map(address).includes(address(config.mailbox.address))) return false;
  return !mail.replyTo || address(mail.replyTo) === sender;
}

/** Format support cannot grant sender or reply authority. Inline files are never trusted signatures. */
export function contentClassification(mail) {
  if (mail.attachments) return 'document';
  if (mail.bodyFormat && mail.bodyFormat !== 'text') return 'body-format';
  if (!mail.body.trim()) return 'empty-request';
  if (mail.attachmentStatus === 'unknown') return 'unchecked';
  if (mail.attachmentStatus && mail.attachmentStatus !== 'none') return 'unknown';
  return 'none';
}

export function maySend(run, config) {
  return admitted(run.mail, config) && config.policy.recipients.includes(address(run.mail.sender));
}

export function permittedTool(call, config, tool) {
  if (!tool || !config.model.capabilities.tools) throw new Error('Tool is not permitted.');
  const policy = config.policy.tools[call.name];
  if (!policy) throw new Error('Tool is not permitted.');
  if (!call.args || typeof call.args !== 'object' || Array.isArray(call.args)) throw new Error('Tool arguments are invalid.');
  if (!ajv.validate(tool.inputSchema ?? { type: 'object' }, call.args)) throw new Error('Tool arguments are invalid.');
  if (policy.constraints && !ajv.validate(policy.constraints, call.args)) throw new Error('Tool arguments are outside policy.');
  requireWriteBounds(policy);
  return policy;
}

function requireWriteBounds(policy) {
  if (policy.effect !== 'write' || policy.authorization !== 'automatic') return;
  if (!policy.constraints) throw new Error('Automatic writes require bounded constraints.');
}

export function policyDigest(config) { return digest(config.policy); }
